use crate::presentation::http::v1::requests::task as dto;
use crate::application::inputs::task as input;

impl From<dto::Task> for input::Task {
    fn from(value: dto::Task) -> Self {
        match value {
            dto::Task::AnyToAny => input::Task::AnyToAny,
            dto::Task::AutomaticSpeechRecognition => input::Task::AutomaticSpeechRecognition,
            dto::Task::AudioToAudio => input::Task::AudioToAudio,
            dto::Task::AudioClassification => input::Task::AudioClassification,
            dto::Task::AudioTextToText => input::Task::AudioTextToText,
            dto::Task::DepthEstimation => input::Task::DepthEstimation,
            dto::Task::DocumentQuestionAnswering => input::Task::DocumentQuestionAnswering,
            dto::Task::FeatureExtraction => input::Task::FeatureExtraction,
            dto::Task::FillMask => input::Task::FillMask,
            dto::Task::ImageFeatureExtraction => input::Task::ImageFeatureExtraction,
            dto::Task::ImageTextToText => input::Task::ImageTextToText,
            dto::Task::ImageToVideo => input::Task::ImageToVideo,
            dto::Task::ImageSegmentation => input::Task::ImageSegmentation,
            dto::Task::ImageClassification => input::Task::ImageClassification,
            dto::Task::ImageTo3d => input::Task::ImageTo3d,
            dto::Task::ImageToImage => input::Task::ImageToImage,
            dto::Task::ImageToText => input::Task::ImageToText,
            dto::Task::KeypointDetection => input::Task::KeypointDetection,
            dto::Task::MaskGeneration => input::Task::MaskGeneration,
            dto::Task::ObjectDetection => input::Task::ObjectDetection,
            dto::Task::QuestionAnswering => input::Task::QuestionAnswering,
            dto::Task::ReinforcementLearning => input::Task::ReinforcementLearning,
            dto::Task::SentenceSimilarity => input::Task::SentenceSimilarity,
            dto::Task::Summarization => input::Task::Summarization,
            dto::Task::TableQuestionAnswering => input::Task::TableQuestionAnswering,
            dto::Task::TextGeneration => input::Task::TextGeneration,
            dto::Task::TextRanking => input::Task::TextRanking,
            dto::Task::TabularClassification => input::Task::TabularClassification,
            dto::Task::TextTo3d => input::Task::TextTo3d,
            dto::Task::TextClassification => input::Task::TextClassification,
            dto::Task::TextToImage => input::Task::TextToImage,
            dto::Task::Translation => input::Task::Translation,
            dto::Task::TabularRegression => input::Task::TabularRegression,
            dto::Task::TextToSpeech => input::Task::TextToSpeech,
            dto::Task::TextToVideo => input::Task::TextToVideo,
            dto::Task::TokenClassification => input::Task::TokenClassification,
            dto::Task::UnconditionalImageGeneration => input::Task::UnconditionalImageGeneration,
            dto::Task::VideoClassification => input::Task::VideoClassification,
            dto::Task::VideoTextToText => input::Task::VideoTextToText,
            dto::Task::VideoToVideo => input::Task::VideoToVideo,
            dto::Task::VisualQuestionAnswering => input::Task::VisualQuestionAnswering,
            dto::Task::VisualDocumentRetrieval => input::Task::VisualDocumentRetrieval,
            dto::Task::ZeroShotClassification => input::Task::ZeroShotClassification,
            dto::Task::ZeroShotImageClassification => input::Task::ZeroShotClassification,
            dto::Task::ZeroShotObjectDetection => input::Task::ZeroShotObjectDetection,
        }
    }
}