#!/usr/bin/env bash

projectRoot=$1
if [[ -z $projectRoot ]]; then
    echo ❌ Must provide the path to the project root
    exit 1
fi

docker run \
    -it \
    --rm \
    --mount type=bind,source="$projectRoot/sdks/typescript-sdk/gen,target=/src/sdks/typescript-sdk/gen" \
    --mount type=bind,source="$projectRoot/services/models/spec/v1/openapi.json",target=/src/services/models/spec/v1/openapi.json \
    --mount type=bind,source="$projectRoot/services/deployments/spec/v1/openapi.json",target=/src/services/deployments/spec/v1/openapi.json \
    tapis/mlhub-typescript-sdk:local