#!/usr/bin/env bash

projectRoot=$1
if [[ -z $projectRoot ]]; then
    echo ❌ Must provide the path to the project root
    exit 1
fi

docker run \
    --rm \
    --mount type=bind,source="$projectRoot/sdks/typescript-sdk/gen,target=/src/sdks/typescript-sdk/gen" \
    --mount type=bind,source="$projectRoot/specs",target=/src/specs \
    tapis/mlhub-typescript-sdk:local \
    -c \
    "chmod +x ./generate_all && ./generate_all"
