apiVersion: v1
kind: ConfigMap
metadata:
  name: mlhub-traefik-dynamic-config
data:
  dynamic-config.yaml: |-
    http:
      middlewares:
        cors:
          headers:
            accessControlAllowOriginList:
              - http://localhost:3000
            accessControlAllowMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            accessControlAllowHeaders:
              - Content-Type
              - Authorization
              - X-Tapis-Token
            accessControlAllowCredentials: true
      routers:
        dashboard:
          rule: (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
          service: api@internal

        models-api:
          rule: "PathPrefix(`/models-api`)"
          service: models-api
          middlewares:
            - cors
        
        datasets-api:
          rule: "PathPrefix(`/datasets-api`)"
          service: datasets-api
          middlewares:
            - cors

        deployments-api:
          rule: "PathPrefix(`/deployments-api`)"
          service: deployments-api
          middlewares:
            - cors

        training-api:
          rule: "PathPrefix(`/training-api`)"
          service: training-api
          middlewares:
            - cors

      services:
        models-api:
          loadBalancer:
            servers:
            - url: http://mlhub-models-api-service:8000
        deployments-api:
          loadBalancer:
            servers:
            - url: http://mlhub-deployments-api-service:8000
        datasets-api:
          loadBalancer:
            servers:
            - url: http://mlhub-datasets-api-service:8000
        training-api:
          loadBalancer:
            servers:
            - url: http://mlhub-training-api-service:8000