# Stage 1: Compile the code
# Digest refers to rust:1.93.1-trixie
FROM rust@sha256:80302520b7199f0504975bca59a914015e9fee088f759875dbbc238ca9509ee1 AS builder

ARG SERVICE_NAME
ARG SERVICE_DIR
ARG LIBS_DIR
ARG SDKS_DIR

# Create 
RUN mkdir -p /usr/local/mlhub/services/${SERVICE_NAME} /usr/local/mlhub/libs /usr/local/mlhub/sdks

# Copy shared libraries code
WORKDIR /usr/local/mlhub/libs
COPY ${LIBS_DIR} .

WORKDIR /usr/local/mlhub/sdks
COPY ${SDKS_DIR} .

# Copy service code
WORKDIR /usr/local/mlhub/services/${SERVICE_NAME}
COPY ${SERVICE_DIR} .

# Install
RUN cargo install --path .

# Stage 2: Copy the binary to a slim Linux image
FROM debian:trixie-slim

ARG SERVICE_NAME

RUN apt-get update && rm -rf /var/lib/apt/lists/*
RUN apt update
RUN apt install libssl3
RUN apt-get install -y --no-install-recommends ca-certificates git git-lfs
RUN update-ca-certificates
COPY --from=builder /usr/local/mlhub/services/${SERVICE_NAME}/target/release/${SERVICE_NAME} /usr/local/bin/mlhub

ENV RUST_LOG=debug,shared=debug

CMD ["mlhub"]

# FROM debian:trixie-slim

# ARG SERVICE_NAME

# # Remove unnecessary bins
# RUN apt-get update && rm -rf /var/lib/apt/lists/*
# RUN apt update
# RUN apt install libssl3
# RUN apt-get install -y --no-install-recommends ca-certificates git git-lfs
# RUN update-ca-certificates

# # Copy the binary
# COPY src/components/${SERVICE_NAME}/target/release/${SERVICE_NAME} /usr/local/bin/mlhub

# ENV RUST_LOG=debug

# CMD ["mlhub"]