use crate::infra::persistence::mongo::documents::domains as documents;
use crate::domain::entities::domains as entities;

impl From<documents::Domain> for entities::Domain {
    fn from(value: documents::Domain) -> Self {
        match value {
            documents::Domain::Automation => entities::Domain::Automation,
            documents::Domain::Automotive => entities::Domain::Automotive,
            documents::Domain::AutonomousVehicles => entities::Domain::AutonomousVehicles,
            documents::Domain::Banking => entities::Domain::Banking,
            documents::Domain::Bioinformatics => entities::Domain::Bioinformatics,
            documents::Domain::Biotechnology => entities::Domain::Biotechnology,
            documents::Domain::CommunicationSystems => entities::Domain::CommunicationSystems,
            documents::Domain::CompensationAndBenefits => entities::Domain::CompensationAndBenefits,
            documents::Domain::ConsumerGoods => entities::Domain::ConsumerGoods,
            documents::Domain::ContentModeration => entities::Domain::ContentModeration,
            documents::Domain::CurriculumDesign => entities::Domain::CurriculumDesign,
            documents::Domain::DataPrivacy => entities::Domain::DataPrivacy,
            documents::Domain::ELearning => entities::Domain::ELearning,
            documents::Domain::Education => entities::Domain::Education,
            documents::Domain::EducationalTechnology => entities::Domain::EducationalTechnology,
            documents::Domain::EmployeeRelations => entities::Domain::EmployeeRelations,
            documents::Domain::Finance => entities::Domain::Finance,
            documents::Domain::FinanceAndBusiness => entities::Domain::FinanceAndBusiness,
            documents::Domain::FraudPrevention => entities::Domain::FraudPrevention,
            documents::Domain::Freight => entities::Domain::Freight,
            documents::Domain::Genomics => entities::Domain::Genomics,
            documents::Domain::HealthInformationSystems => entities::Domain::HealthInformationSystems,
            documents::Domain::Healthcare => entities::Domain::Healthcare,
            documents::Domain::HealthcareInformatics => entities::Domain::HealthcareInformatics,
            documents::Domain::HrAnalytics => entities::Domain::HrAnalytics,
            documents::Domain::HumanResources => entities::Domain::HumanResources,
            documents::Domain::IndustrialManufacturing => entities::Domain::IndustrialManufacturing,
            documents::Domain::InformationTechnology => entities::Domain::InformationTechnology,
            documents::Domain::InternetOfThings => entities::Domain::InternetOfThings,
            documents::Domain::InvestmentServices => entities::Domain::InvestmentServices,
            documents::Domain::LeanManufacturing => entities::Domain::LeanManufacturing,
            documents::Domain::LearningManagementSystems => entities::Domain::LearningManagementSystems,
            documents::Domain::LifeScience => entities::Domain::LifeScience,
            documents::Domain::Logistics => entities::Domain::Logistics,
            documents::Domain::MedicalTechnology => entities::Domain::MedicalTechnology,
            documents::Domain::MolecularBiology => entities::Domain::MolecularBiology,
            documents::Domain::NetworkManagement => entities::Domain::NetworkManagement,
            documents::Domain::NetworkOperations => entities::Domain::NetworkOperations,
            documents::Domain::Networking => entities::Domain::Networking,
            documents::Domain::OnlineSafety => entities::Domain::OnlineSafety,
            documents::Domain::PatientManagementSystems => entities::Domain::PatientManagementSystems,
            documents::Domain::Pedagogy => entities::Domain::Pedagogy,
            documents::Domain::PharmaceuticalResearch => entities::Domain::PharmaceuticalResearch,
            documents::Domain::ProcessEngineering => entities::Domain::ProcessEngineering,
            documents::Domain::PublicTransit => entities::Domain::PublicTransit,
            documents::Domain::Recruitment => entities::Domain::Recruitment,
            documents::Domain::Retail => entities::Domain::Retail,
            documents::Domain::RiskManagement => entities::Domain::RiskManagement,
            documents::Domain::Robotics => entities::Domain::Robotics,
            documents::Domain::Security => entities::Domain::Security,
            documents::Domain::SoftwareEngineering => entities::Domain::SoftwareEngineering,
            documents::Domain::SupplyChain => entities::Domain::SupplyChain,
            documents::Domain::SupplyChainManagement => entities::Domain::SupplyChainManagement,
            documents::Domain::Technology => entities::Domain::Technology,
            documents::Domain::Telemedicine => entities::Domain::Telemedicine,
            documents::Domain::TrainingAndDevelopment => entities::Domain::TrainingAndDevelopment,
            documents::Domain::Transportation => entities::Domain::Transportation,
            documents::Domain::TrustAndSafety => entities::Domain::TrustAndSafety,
        }
    }
}