use crate::infra::persistence::mongo::documents::domains as documents;
use crate::domain::entities::domain as entities;

impl From<entities::Domain> for documents::Domain {
    fn from(value: entities::Domain) -> Self {
        match value {
            entities::Domain::Automation => documents::Domain::Automation,
            entities::Domain::Automotive => documents::Domain::Automotive,
            entities::Domain::AutonomousVehicles => documents::Domain::AutonomousVehicles,
            entities::Domain::Banking => documents::Domain::Banking,
            entities::Domain::Bioinformatics => documents::Domain::Bioinformatics,
            entities::Domain::Biotechnology => documents::Domain::Biotechnology,
            entities::Domain::CommunicationSystems => documents::Domain::CommunicationSystems,
            entities::Domain::CompensationAndBenefits => documents::Domain::CompensationAndBenefits,
            entities::Domain::ConsumerGoods => documents::Domain::ConsumerGoods,
            entities::Domain::ContentModeration => documents::Domain::ContentModeration,
            entities::Domain::CurriculumDesign => documents::Domain::CurriculumDesign,
            entities::Domain::DataPrivacy => documents::Domain::DataPrivacy,
            entities::Domain::ELearning => documents::Domain::ELearning,
            entities::Domain::Education => documents::Domain::Education,
            entities::Domain::EducationalTechnology => documents::Domain::EducationalTechnology,
            entities::Domain::EmployeeRelations => documents::Domain::EmployeeRelations,
            entities::Domain::Finance => documents::Domain::Finance,
            entities::Domain::FinanceAndBusiness => documents::Domain::FinanceAndBusiness,
            entities::Domain::FraudPrevention => documents::Domain::FraudPrevention,
            entities::Domain::Freight => documents::Domain::Freight,
            entities::Domain::Genomics => documents::Domain::Genomics,
            entities::Domain::HealthInformationSystems => documents::Domain::HealthInformationSystems,
            entities::Domain::Healthcare => documents::Domain::Healthcare,
            entities::Domain::HealthcareInformatics => documents::Domain::HealthcareInformatics,
            entities::Domain::HrAnalytics => documents::Domain::HrAnalytics,
            entities::Domain::HumanResources => documents::Domain::HumanResources,
            entities::Domain::IndustrialManufacturing => documents::Domain::IndustrialManufacturing,
            entities::Domain::InformationTechnology => documents::Domain::InformationTechnology,
            entities::Domain::InternetOfThings => documents::Domain::InternetOfThings,
            entities::Domain::InvestmentServices => documents::Domain::InvestmentServices,
            entities::Domain::LeanManufacturing => documents::Domain::LeanManufacturing,
            entities::Domain::LearningManagementSystems => documents::Domain::LearningManagementSystems,
            entities::Domain::LifeScience => documents::Domain::LifeScience,
            entities::Domain::Logistics => documents::Domain::Logistics,
            entities::Domain::MedicalTechnology => documents::Domain::MedicalTechnology,
            entities::Domain::MolecularBiology => documents::Domain::MolecularBiology,
            entities::Domain::NetworkManagement => documents::Domain::NetworkManagement,
            entities::Domain::NetworkOperations => documents::Domain::NetworkOperations,
            entities::Domain::Networking => documents::Domain::Networking,
            entities::Domain::OnlineSafety => documents::Domain::OnlineSafety,
            entities::Domain::PatientManagementSystems => documents::Domain::PatientManagementSystems,
            entities::Domain::Pedagogy => documents::Domain::Pedagogy,
            entities::Domain::PharmaceuticalResearch => documents::Domain::PharmaceuticalResearch,
            entities::Domain::ProcessEngineering => documents::Domain::ProcessEngineering,
            entities::Domain::PublicTransit => documents::Domain::PublicTransit,
            entities::Domain::Recruitment => documents::Domain::Recruitment,
            entities::Domain::Retail => documents::Domain::Retail,
            entities::Domain::RiskManagement => documents::Domain::RiskManagement,
            entities::Domain::Robotics => documents::Domain::Robotics,
            entities::Domain::Security => documents::Domain::Security,
            entities::Domain::SoftwareEngineering => documents::Domain::SoftwareEngineering,
            entities::Domain::SupplyChain => documents::Domain::SupplyChain,
            entities::Domain::SupplyChainManagement => documents::Domain::SupplyChainManagement,
            entities::Domain::Technology => documents::Domain::Technology,
            entities::Domain::Telemedicine => documents::Domain::Telemedicine,
            entities::Domain::TrainingAndDevelopment => documents::Domain::TrainingAndDevelopment,
            entities::Domain::Transportation => documents::Domain::Transportation,
            entities::Domain::TrustAndSafety => documents::Domain::TrustAndSafety,
        }
    }
}