[workspace]
members = [
    # "src/agents",
    # "src/apis/datasets",
    "src/deployments",
    "src/models",
    "src/models-migrator",
    "src/artifact-ingester",
    "src/artifact-publisher",
    "src/libs/client-provider",
    "src/libs/clients",
    "src/libs/git-lfs-client",
    "src/libs/github-lfs-client",
    "src/libs/huggingface-client",
    "src/libs/patra-client",
    "src/libs/s3-client",
    "src/libs/shared",
    "src/libs/huggingface-tasks",
    "src/libs/tapis-client",
    "src/sdks/agntcy-sdk",
    "src/hf-model-etl",
    "src/model-deployment-controller",
]
