use client_provider::Platform;
use shared::presentation::http::v1::responses::{Artifact, ArtifactPublication, ArtifactIngestion};
use utoipa::OpenApi;
use crate::config::VERSION;

// Here we are import the helper function generated by utoipa to generate docs for
// handlers
use super::handlers::create_model_metadata::__path_create_model_metadata;
use super::handlers::discover_models_by_platform::__path_discover_models_by_platform;
use super::handlers::get_model_artifact::__path_get_model_artifact;
use super::handlers::get_model_by_platform::__path_get_model_by_platform;
use super::handlers::get_model_ingestion::__path_get_model_ingestion;
use super::handlers::get_model_publication::__path_get_model_publication;
use super::handlers::ingest_external_model::__path_ingest_external_model;
use super::handlers::publish_model_artifact::__path_publish_model_artifact;
use super::handlers::list_model_artifacts::__path_list_model_artifacts;
use super::handlers::list_model_ingestions::__path_list_model_ingestions;
use super::handlers::list_model_publications::__path_list_model_publications;
use super::handlers::list_models_by_platform::__path_list_models_by_platform;
use super::handlers::list_platforms::__path_list_platforms;
use super::handlers::list_publications_for_artifact::__path_list_publications_for_artifact;

#[derive(OpenApi)]
#[openapi(
    paths(
        get_model_by_platform,
        get_model_artifact,
        create_model_metadata,
        discover_models_by_platform,
        get_model_ingestion,
        get_model_publication,
        list_publications_for_artifact,
        ingest_external_model,
        publish_model_artifact,
        list_model_artifacts,
        list_model_ingestions,
        list_model_publications,
        list_models_by_platform,
        list_platforms,
    ),
    components(
        schemas(
            Platform,
            Artifact,
            ArtifactPublication,
            ArtifactIngestion
        )
    ),
    info(title = "MLHub Models API", version=VERSION)
)]
pub struct ApiDoc;