apiVersion: batch/v1
kind: Job
metadata:
  name: mlhub-models-migrator
spec:
  backoffLimit: 0
  template:
    metadata:
      name: mlhub-models-migrator
    spec:
      restartPolicy: Never
      containers:
        - env:
            - name: ARTIFACTS_DB_HOST
              value: mlhub-artifact-db-service
            - name: ARTIFACTS_DB_PORT
              value: "27017"
            - name: ARTIFACTS_DB_NAME
              value: mlhub
            - name: ARTIFACTS_DB_PASSWORD
              value: password
            - name: ARTIFACTS_DB_USERNAME
              value: mlhub
            - name: ARTIFACT_OP_MQ_HOST
              value: mlhub-artifact-mq-service
            - name: ARTIFACT_OP_MQ_PASSWORD
              value: dev
            - name: ARTIFACT_OP_MQ_PORT
              value: "5672"
            - name: ARTIFACT_OP_MQ_USER
              value: dev
            - name: RUST_LOG
              value: debug
            - name: SHARED_DATA
              value: /srv/mlhub
          image: tapis/models-migrator:local
          imagePullPolicy: Never
          name: models-migrator
          resources: {}
