kind: Deployment
apiVersion: apps/v1
metadata:
  name: mlhub-traefik-deployment
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: mlhub-traefik-account
      containers:
        - name: traefik
          image: traefik:v3.2
          args:
            - --api.insecure
            - --providers.kubernetesingress
            - --accesslog=true
            - --providers.file.directory=/etc/traefik
            # - --providers.file.filename=/etc/traefik/dynamic-config.yaml
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
          volumeMounts:
          - name: dynamic-config
            mountPath: /etc/traefik/dynamic-config.yaml
            subPath: dynamic-config.yaml
      volumes:
      - name: dynamic-config
        configMap:
          name: mlhub-traefik-dynamic-config