apiVersion: v1
kind: ConfigMap
metadata:
  name: mlhub-traefik-dynamic-config
data:
  dynamic-config.yaml: |-
    http:
      routers:
        dashboard:
          rule: (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
          service: api@internal

        models-api:
          rule: "PathPrefix(`/models-api`)"
          service: models-api
        
        datasets-api:
          rule: "PathPrefix(`/datasets-api`)"
          service: datasets-api

        inference-api:
          rule: "PathPrefix(`/inference-api`)"
          service: inference-api

        training-api:
          rule: "PathPrefix(`/training-api`)"
          service: training-api

      services:
        models-api:
          loadBalancer:
            servers:
            - url: http://mlhub-models-api-service:8000
        datasets-api:
          loadBalancer:
            servers:
            - url: http://mlhub-datasets-api-service:8000
        inference-api:
          loadBalancer:
            servers:
            - url: http://mlhub-inference-api-service:8000
        training-api:
          loadBalancer:
            servers:
            - url: http://mlhub-training-api-service:8000









