FROM debian:trixie-slim

ARG SERVICE_NAME

# Remove unnecessary bins
RUN apt-get update && rm -rf /var/lib/apt/lists/*
RUN apt update
RUN apt install libssl3
RUN apt-get install -y --no-install-recommends ca-certificates git git-lfs
RUN update-ca-certificates

# Copy the binary
COPY src/components/${SERVICE_NAME}/target/release/${SERVICE_NAME} /usr/local/bin/mlhub

ENV RUST_LOG=debug

CMD ["mlhub"]