#!/usr/bin/env bash

set -e

echo "mlhub:"

here=$(pwd)

# Make data dirs
mkdir -p {{ tapisdatadir }}/mlhub
mkdir -p {{ tapisdatadir }}/mlhub/nfs
mkdir -p {{ tapisdatadir }}/mlhub/models
mkdir -p {{ tapisdatadir }}/mlhub/artifact-ingester
mkdir -p {{ tapisdatadir }}/mlhub/artifact-publisher
mkdir -p {{ tapisdatadir }}/mlhub/mongo
mkdir -p {{ tapisdatadir }}/mlhub/rabbit
# mkdir -p {{ tapisdatadir }}/mlhub/datasets
# mkdir -p {{ tapisdatadir }}/mlhub/inference
# mkdir -p {{ tapisdatadir }}/mlhub/training

cd "$here/traefik"
./burnup.sh

cd "$here/nfs"
./burnup.sh

echo "Waiting 5 seconds for nfs server to start"
sleep 5

cd "$here/mongo"
./burnup.sh

cd "$here/rabbit"
./burnup.sh

cd "$here/artifact-ingester"
./burnup.sh

cd "$here/artifact-publisher"
./burnup.sh

echo "Waiting 5 seconds for artifact suite to start"
sleep 5

echo "Starting Migrations"

cd "$here/migrations"
./run-all.sh

cd "$here/model-deployment-controller"
./burnup.sh

cd "$here/models"
./burnup.sh

cd "$here/deployments"
./burnup.sh

# cd $here/datasets
# ./burnup.sh
