apiVersion: v1
kind: Secret
metadata:
  name: mlhub-deployment-identity-secret
type: Opaque
stringData:
  identifier: 019cb496-4378-7ac4-bad0-029fb77adbd8 # Uuid that provides a unique identity for the entire mlhub deployment
