use crate::application::inputs::domains as inputs;
use crate::domain::entities::domains as entities;

impl From<inputs::Domain> for entities::Domain {
    fn from(value: inputs::Domain) -> Self {
        match value {
            inputs::Domain::Automation => entities::Domain::Automation,
            inputs::Domain::Automotive => entities::Domain::Automotive,
            inputs::Domain::AutonomousVehicles => entities::Domain::AutonomousVehicles,
            inputs::Domain::Banking => entities::Domain::Banking,
            inputs::Domain::Bioinformatics => entities::Domain::Bioinformatics,
            inputs::Domain::Biotechnology => entities::Domain::Biotechnology,
            inputs::Domain::CommunicationSystems => entities::Domain::CommunicationSystems,
            inputs::Domain::CompensationAndBenefits => entities::Domain::CompensationAndBenefits,
            inputs::Domain::ConsumerGoods => entities::Domain::ConsumerGoods,
            inputs::Domain::ContentModeration => entities::Domain::ContentModeration,
            inputs::Domain::CurriculumDesign => entities::Domain::CurriculumDesign,
            inputs::Domain::DataPrivacy => entities::Domain::DataPrivacy,
            inputs::Domain::ELearning => entities::Domain::ELearning,
            inputs::Domain::Education => entities::Domain::Education,
            inputs::Domain::EducationalTechnology => entities::Domain::EducationalTechnology,
            inputs::Domain::EmployeeRelations => entities::Domain::EmployeeRelations,
            inputs::Domain::Finance => entities::Domain::Finance,
            inputs::Domain::FinanceAndBusiness => entities::Domain::FinanceAndBusiness,
            inputs::Domain::FraudPrevention => entities::Domain::FraudPrevention,
            inputs::Domain::Freight => entities::Domain::Freight,
            inputs::Domain::Genomics => entities::Domain::Genomics,
            inputs::Domain::HealthInformationSystems => entities::Domain::HealthInformationSystems,
            inputs::Domain::Healthcare => entities::Domain::Healthcare,
            inputs::Domain::HealthcareInformatics => entities::Domain::HealthcareInformatics,
            inputs::Domain::HrAnalytics => entities::Domain::HrAnalytics,
            inputs::Domain::HumanResources => entities::Domain::HumanResources,
            inputs::Domain::IndustrialManufacturing => entities::Domain::IndustrialManufacturing,
            inputs::Domain::InformationTechnology => entities::Domain::InformationTechnology,
            inputs::Domain::InternetOfThings => entities::Domain::InternetOfThings,
            inputs::Domain::InvestmentServices => entities::Domain::InvestmentServices,
            inputs::Domain::LeanManufacturing => entities::Domain::LeanManufacturing,
            inputs::Domain::LearningManagementSystems => entities::Domain::LearningManagementSystems,
            inputs::Domain::LifeScience => entities::Domain::LifeScience,
            inputs::Domain::Logistics => entities::Domain::Logistics,
            inputs::Domain::MedicalTechnology => entities::Domain::MedicalTechnology,
            inputs::Domain::MolecularBiology => entities::Domain::MolecularBiology,
            inputs::Domain::NetworkManagement => entities::Domain::NetworkManagement,
            inputs::Domain::NetworkOperations => entities::Domain::NetworkOperations,
            inputs::Domain::Networking => entities::Domain::Networking,
            inputs::Domain::OnlineSafety => entities::Domain::OnlineSafety,
            inputs::Domain::PatientManagementSystems => entities::Domain::PatientManagementSystems,
            inputs::Domain::Pedagogy => entities::Domain::Pedagogy,
            inputs::Domain::PharmaceuticalResearch => entities::Domain::PharmaceuticalResearch,
            inputs::Domain::ProcessEngineering => entities::Domain::ProcessEngineering,
            inputs::Domain::PublicTransit => entities::Domain::PublicTransit,
            inputs::Domain::Recruitment => entities::Domain::Recruitment,
            inputs::Domain::Retail => entities::Domain::Retail,
            inputs::Domain::RiskManagement => entities::Domain::RiskManagement,
            inputs::Domain::Robotics => entities::Domain::Robotics,
            inputs::Domain::Security => entities::Domain::Security,
            inputs::Domain::SoftwareEngineering => entities::Domain::SoftwareEngineering,
            inputs::Domain::SupplyChain => entities::Domain::SupplyChain,
            inputs::Domain::SupplyChainManagement => entities::Domain::SupplyChainManagement,
            inputs::Domain::Technology => entities::Domain::Technology,
            inputs::Domain::Telemedicine => entities::Domain::Telemedicine,
            inputs::Domain::TrainingAndDevelopment => entities::Domain::TrainingAndDevelopment,
            inputs::Domain::Transportation => entities::Domain::Transportation,
            inputs::Domain::TrustAndSafety => entities::Domain::TrustAndSafety,
        }
    }
}