/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AssociateModelBody,
    AssociateModelBodyFromJSON,
    AssociateModelBodyToJSON,
    AssociateModelResponse,
    AssociateModelResponseFromJSON,
    AssociateModelResponseToJSON,
    BadRequestResponse,
    BadRequestResponseFromJSON,
    BadRequestResponseToJSON,
    ConflictResponse,
    ConflictResponseFromJSON,
    ConflictResponseToJSON,
    GetModelArtifactResponse,
    GetModelArtifactResponseFromJSON,
    GetModelArtifactResponseToJSON,
    ListModelArtifactResponse,
    ListModelArtifactResponseFromJSON,
    ListModelArtifactResponseToJSON,
    NotFoundResponse,
    NotFoundResponseFromJSON,
    NotFoundResponseToJSON,
    ServerErrorResponse,
    ServerErrorResponseFromJSON,
    ServerErrorResponseToJSON,
} from '../models';

export interface AssociateModelWithArtifactRequest {
    artifactId: string;
    associateModelBody: AssociateModelBody;
}

export interface GetModelArtifactRequest {
    artifactId: string;
}

/**
 * 
 */
export class ArtifactsApi extends runtime.BaseAPI {

    /**
     * Associate an owned model with an artifact
     */
    async associateModelWithArtifactRaw(requestParameters: AssociateModelWithArtifactRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AssociateModelResponse>> {
        if (requestParameters.artifactId === null || requestParameters.artifactId === undefined) {
            throw new runtime.RequiredError('artifactId','Required parameter requestParameters.artifactId was null or undefined when calling associateModelWithArtifact.');
        }

        if (requestParameters.associateModelBody === null || requestParameters.associateModelBody === undefined) {
            throw new runtime.RequiredError('associateModelBody','Required parameter requestParameters.associateModelBody was null or undefined when calling associateModelWithArtifact.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/models-api/artifacts/{artifact_id}/model`.replace(`{${"artifact_id"}}`, encodeURIComponent(String(requestParameters.artifactId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssociateModelBodyToJSON(requestParameters.associateModelBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssociateModelResponseFromJSON(jsonValue));
    }

    /**
     * Associate an owned model with an artifact
     */
    async associateModelWithArtifact(requestParameters: AssociateModelWithArtifactRequest, initOverrides?: RequestInit): Promise<AssociateModelResponse> {
        const response = await this.associateModelWithArtifactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetches the model artifact by the provided id
     */
    async getModelArtifactRaw(requestParameters: GetModelArtifactRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetModelArtifactResponse>> {
        if (requestParameters.artifactId === null || requestParameters.artifactId === undefined) {
            throw new runtime.RequiredError('artifactId','Required parameter requestParameters.artifactId was null or undefined when calling getModelArtifact.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models-api/artifacts/{artifact_id}`.replace(`{${"artifact_id"}}`, encodeURIComponent(String(requestParameters.artifactId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetModelArtifactResponseFromJSON(jsonValue));
    }

    /**
     * Fetches the model artifact by the provided id
     */
    async getModelArtifact(requestParameters: GetModelArtifactRequest, initOverrides?: RequestInit): Promise<GetModelArtifactResponse> {
        const response = await this.getModelArtifactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all model artifacts
     */
    async listModelArtifactsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListModelArtifactResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models-api/artifacts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelArtifactResponseFromJSON(jsonValue));
    }

    /**
     * List all model artifacts
     */
    async listModelArtifacts(initOverrides?: RequestInit): Promise<ListModelArtifactResponse> {
        const response = await this.listModelArtifactsRaw(initOverrides);
        return await response.value();
    }

}
