/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BadRequestResponse,
    BadRequestResponseFromJSON,
    BadRequestResponseToJSON,
    DiscoverExternalModelsBody,
    DiscoverExternalModelsBodyFromJSON,
    DiscoverExternalModelsBodyToJSON,
    DiscoverExternalModelsResponse,
    DiscoverExternalModelsResponseFromJSON,
    DiscoverExternalModelsResponseToJSON,
    GetExternalModelResponse,
    GetExternalModelResponseFromJSON,
    GetExternalModelResponseToJSON,
    ListExternalModelDeploymentOptionsResponse,
    ListExternalModelDeploymentOptionsResponseFromJSON,
    ListExternalModelDeploymentOptionsResponseToJSON,
    NotFoundResponse,
    NotFoundResponseFromJSON,
    NotFoundResponseToJSON,
    ServerErrorResponse,
    ServerErrorResponseFromJSON,
    ServerErrorResponseToJSON,
} from '../models';

export interface DiscoverExternalModelsRequest {
    discoverExternalModelsBody: DiscoverExternalModelsBody;
    limit?: number;
    cursor?: string;
    includeCount?: boolean;
}

export interface GetExternalModelRequest {
    externalModelId: string;
}

export interface ListExternalModelDeploymentOptionsRequest {
    externalModelId: string;
    limit?: number;
    cursor?: string;
    includeCount?: boolean;
}

/**
 * 
 */
export class ExternalModelsApi extends runtime.BaseAPI {

    /**
     * Search the external model catalog
     */
    async discoverExternalModelsRaw(requestParameters: DiscoverExternalModelsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<DiscoverExternalModelsResponse>> {
        if (requestParameters.discoverExternalModelsBody === null || requestParameters.discoverExternalModelsBody === undefined) {
            throw new runtime.RequiredError('discoverExternalModelsBody','Required parameter requestParameters.discoverExternalModelsBody was null or undefined when calling discoverExternalModels.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.includeCount !== undefined) {
            queryParameters['include_count'] = requestParameters.includeCount;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/models-api/external-models/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DiscoverExternalModelsBodyToJSON(requestParameters.discoverExternalModelsBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DiscoverExternalModelsResponseFromJSON(jsonValue));
    }

    /**
     * Search the external model catalog
     */
    async discoverExternalModels(requestParameters: DiscoverExternalModelsRequest, initOverrides?: RequestInit): Promise<DiscoverExternalModelsResponse> {
        const response = await this.discoverExternalModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get an external model
     */
    async getExternalModelRaw(requestParameters: GetExternalModelRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetExternalModelResponse>> {
        if (requestParameters.externalModelId === null || requestParameters.externalModelId === undefined) {
            throw new runtime.RequiredError('externalModelId','Required parameter requestParameters.externalModelId was null or undefined when calling getExternalModel.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models-api/external-models/{external_model_id}`.replace(`{${"external_model_id"}}`, encodeURIComponent(String(requestParameters.externalModelId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetExternalModelResponseFromJSON(jsonValue));
    }

    /**
     * Get an external model
     */
    async getExternalModel(requestParameters: GetExternalModelRequest, initOverrides?: RequestInit): Promise<GetExternalModelResponse> {
        const response = await this.getExternalModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List deployment options for an external model
     */
    async listExternalModelDeploymentOptionsRaw(requestParameters: ListExternalModelDeploymentOptionsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListExternalModelDeploymentOptionsResponse>> {
        if (requestParameters.externalModelId === null || requestParameters.externalModelId === undefined) {
            throw new runtime.RequiredError('externalModelId','Required parameter requestParameters.externalModelId was null or undefined when calling listExternalModelDeploymentOptions.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.includeCount !== undefined) {
            queryParameters['include_count'] = requestParameters.includeCount;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models-api/external-models/{external_model_id}/deployment-options`.replace(`{${"external_model_id"}}`, encodeURIComponent(String(requestParameters.externalModelId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListExternalModelDeploymentOptionsResponseFromJSON(jsonValue));
    }

    /**
     * List deployment options for an external model
     */
    async listExternalModelDeploymentOptions(requestParameters: ListExternalModelDeploymentOptionsRequest, initOverrides?: RequestInit): Promise<ListExternalModelDeploymentOptionsResponse> {
        const response = await this.listExternalModelDeploymentOptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
