/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BadRequestResponse,
    BadRequestResponseFromJSON,
    BadRequestResponseToJSON,
    ConflictResponse,
    ConflictResponseFromJSON,
    ConflictResponseToJSON,
    CreateModelBody,
    CreateModelBodyFromJSON,
    CreateModelBodyToJSON,
    CreateModelResponse,
    CreateModelResponseFromJSON,
    CreateModelResponseToJSON,
    GetModelResponse,
    GetModelResponseFromJSON,
    GetModelResponseToJSON,
    ListModelsResponse,
    ListModelsResponseFromJSON,
    ListModelsResponseToJSON,
    NotFoundResponse,
    NotFoundResponseFromJSON,
    NotFoundResponseToJSON,
    ServerErrorResponse,
    ServerErrorResponseFromJSON,
    ServerErrorResponseToJSON,
} from '../models';

export interface CreateModelRequest {
    createModelBody: CreateModelBody;
}

export interface GetModelRequest {
    modelId: string;
}

export interface ListModelsRequest {
    scope?: ListModelsScopeEnum;
    limit?: number;
    cursor?: string;
    includeCount?: boolean;
}

/**
 * 
 */
export class ModelsApi extends runtime.BaseAPI {

    /**
     * Add an external model to the user\'s collection
     */
    async createModelRaw(requestParameters: CreateModelRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateModelResponse>> {
        if (requestParameters.createModelBody === null || requestParameters.createModelBody === undefined) {
            throw new runtime.RequiredError('createModelBody','Required parameter requestParameters.createModelBody was null or undefined when calling createModel.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/models-api/models`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateModelBodyToJSON(requestParameters.createModelBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateModelResponseFromJSON(jsonValue));
    }

    /**
     * Add an external model to the user\'s collection
     */
    async createModel(requestParameters: CreateModelRequest, initOverrides?: RequestInit): Promise<CreateModelResponse> {
        const response = await this.createModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a model from a tenant collection
     */
    async getModelRaw(requestParameters: GetModelRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetModelResponse>> {
        if (requestParameters.modelId === null || requestParameters.modelId === undefined) {
            throw new runtime.RequiredError('modelId','Required parameter requestParameters.modelId was null or undefined when calling getModel.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models-api/models/{model_id}`.replace(`{${"model_id"}}`, encodeURIComponent(String(requestParameters.modelId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetModelResponseFromJSON(jsonValue));
    }

    /**
     * Get a model from a tenant collection
     */
    async getModel(requestParameters: GetModelRequest, initOverrides?: RequestInit): Promise<GetModelResponse> {
        const response = await this.getModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List owned or shared models
     */
    async listModelsRaw(requestParameters: ListModelsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListModelsResponse>> {
        const queryParameters: any = {};

        if (requestParameters.scope !== undefined) {
            queryParameters['scope'] = requestParameters.scope;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.includeCount !== undefined) {
            queryParameters['include_count'] = requestParameters.includeCount;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models-api/models`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelsResponseFromJSON(jsonValue));
    }

    /**
     * List owned or shared models
     */
    async listModels(requestParameters: ListModelsRequest, initOverrides?: RequestInit): Promise<ListModelsResponse> {
        const response = await this.listModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ListModelsScopeEnum {
    Owned = 'Owned',
    Shared = 'Shared'
}
