/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BadRequestResponse,
    BadRequestResponseFromJSON,
    BadRequestResponseToJSON,
    GetModelPublicationResponse,
    GetModelPublicationResponseFromJSON,
    GetModelPublicationResponseToJSON,
    ListModelPublicationsForArtifactResponse,
    ListModelPublicationsForArtifactResponseFromJSON,
    ListModelPublicationsForArtifactResponseToJSON,
    ListModelPublicationsResponse,
    ListModelPublicationsResponseFromJSON,
    ListModelPublicationsResponseToJSON,
    NotFoundResponse,
    NotFoundResponseFromJSON,
    NotFoundResponseToJSON,
    PublishArtifactRequest,
    PublishArtifactRequestFromJSON,
    PublishArtifactRequestToJSON,
    PublishModelArtifactResponse,
    PublishModelArtifactResponseFromJSON,
    PublishModelArtifactResponseToJSON,
    ServerErrorResponse,
    ServerErrorResponseFromJSON,
    ServerErrorResponseToJSON,
} from '../models';

export interface GetModelPublicationRequest {
    publicationId: string;
}

export interface ListPublicationsForArtifactRequest {
    artifactId: string;
}

export interface PublishModelArtifactRequest {
    artifactId: string;
    publishArtifactRequest: PublishArtifactRequest;
}

/**
 * 
 */
export class PublicationsApi extends runtime.BaseAPI {

    /**
     * Fetch a publication by id
     */
    async getModelPublicationRaw(requestParameters: GetModelPublicationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetModelPublicationResponse>> {
        if (requestParameters.publicationId === null || requestParameters.publicationId === undefined) {
            throw new runtime.RequiredError('publicationId','Required parameter requestParameters.publicationId was null or undefined when calling getModelPublication.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models-api/publications/{publication_id}`.replace(`{${"publication_id"}}`, encodeURIComponent(String(requestParameters.publicationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetModelPublicationResponseFromJSON(jsonValue));
    }

    /**
     * Fetch a publication by id
     */
    async getModelPublication(requestParameters: GetModelPublicationRequest, initOverrides?: RequestInit): Promise<GetModelPublicationResponse> {
        const response = await this.getModelPublicationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all model publications
     */
    async listModelPublicationsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListModelPublicationsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models-api/publications`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelPublicationsResponseFromJSON(jsonValue));
    }

    /**
     * List all model publications
     */
    async listModelPublications(initOverrides?: RequestInit): Promise<ListModelPublicationsResponse> {
        const response = await this.listModelPublicationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all publications for an artifact
     */
    async listPublicationsForArtifactRaw(requestParameters: ListPublicationsForArtifactRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListModelPublicationsForArtifactResponse>> {
        if (requestParameters.artifactId === null || requestParameters.artifactId === undefined) {
            throw new runtime.RequiredError('artifactId','Required parameter requestParameters.artifactId was null or undefined when calling listPublicationsForArtifact.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/models-api/artifacts/{artifact_id}/publications`.replace(`{${"artifact_id"}}`, encodeURIComponent(String(requestParameters.artifactId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelPublicationsForArtifactResponseFromJSON(jsonValue));
    }

    /**
     * List all publications for an artifact
     */
    async listPublicationsForArtifact(requestParameters: ListPublicationsForArtifactRequest, initOverrides?: RequestInit): Promise<ListModelPublicationsForArtifactResponse> {
        const response = await this.listPublicationsForArtifactRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Publish a model artifact to an external platform
     */
    async publishModelArtifactRaw(requestParameters: PublishModelArtifactRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<PublishModelArtifactResponse>> {
        if (requestParameters.artifactId === null || requestParameters.artifactId === undefined) {
            throw new runtime.RequiredError('artifactId','Required parameter requestParameters.artifactId was null or undefined when calling publishModelArtifact.');
        }

        if (requestParameters.publishArtifactRequest === null || requestParameters.publishArtifactRequest === undefined) {
            throw new runtime.RequiredError('publishArtifactRequest','Required parameter requestParameters.publishArtifactRequest was null or undefined when calling publishModelArtifact.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/models-api/artifacts/{artifact_id}/publications`.replace(`{${"artifact_id"}}`, encodeURIComponent(String(requestParameters.artifactId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PublishArtifactRequestToJSON(requestParameters.publishArtifactRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishModelArtifactResponseFromJSON(jsonValue));
    }

    /**
     * Publish a model artifact to an external platform
     */
    async publishModelArtifact(requestParameters: PublishModelArtifactRequest, initOverrides?: RequestInit): Promise<PublishModelArtifactResponse> {
        const response = await this.publishModelArtifactRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
