/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AgentArtifactType {
    Binary = 'Binary',
    DockerImage = 'DockerImage',
    HelmChart = 'HelmChart',
    PythonPackage = 'PythonPackage',
    SourceCode = 'SourceCode',
    Unspecified = 'Unspecified'
}

export function AgentArtifactTypeFromJSON(json: any): AgentArtifactType {
    return AgentArtifactTypeFromJSONTyped(json, false);
}

export function AgentArtifactTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentArtifactType {
    return json as AgentArtifactType;
}

export function AgentArtifactTypeToJSON(value?: AgentArtifactType | null): any {
    return value as any;
}

