/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AgentDeploymentModality {
    Persistent = 'Persistent',
    OnDemand = 'OnDemand'
}

export function AgentDeploymentModalityFromJSON(json: any): AgentDeploymentModality {
    return AgentDeploymentModalityFromJSONTyped(json, false);
}

export function AgentDeploymentModalityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentDeploymentModality {
    return json as AgentDeploymentModality;
}

export function AgentDeploymentModalityToJSON(value?: AgentDeploymentModality | null): any {
    return value as any;
}

