/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentSkill
 */
export interface AgentSkill {
    /**
     * 
     * @type {string}
     * @memberof AgentSkill
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AgentSkill
     */
    examples: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AgentSkill
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AgentSkill
     */
    input_modes?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AgentSkill
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AgentSkill
     */
    output_modes?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AgentSkill
     */
    tags: Array<string>;
}

export function AgentSkillFromJSON(json: any): AgentSkill {
    return AgentSkillFromJSONTyped(json, false);
}

export function AgentSkillFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentSkill {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'examples': json['examples'],
        'id': json['id'],
        'input_modes': !exists(json, 'input_modes') ? undefined : json['input_modes'],
        'name': json['name'],
        'output_modes': !exists(json, 'output_modes') ? undefined : json['output_modes'],
        'tags': json['tags'],
    };
}

export function AgentSkillToJSON(value?: AgentSkill | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'examples': value.examples,
        'id': value.id,
        'input_modes': value.input_modes,
        'name': value.name,
        'output_modes': value.output_modes,
        'tags': value.tags,
    };
}

