/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AgentDeploymentModality,
    AgentDeploymentModalityFromJSON,
    AgentDeploymentModalityFromJSONTyped,
    AgentDeploymentModalityToJSON,
    AgentLiveness,
    AgentLivenessFromJSON,
    AgentLivenessFromJSONTyped,
    AgentLivenessToJSON,
    Endpoint,
    EndpointFromJSON,
    EndpointFromJSONTyped,
    EndpointToJSON,
    RestHttpAgentEndpoint,
    RestHttpAgentEndpointFromJSON,
    RestHttpAgentEndpointFromJSONTyped,
    RestHttpAgentEndpointToJSON,
    RpcAgentEndpoint,
    RpcAgentEndpointFromJSON,
    RpcAgentEndpointFromJSONTyped,
    RpcAgentEndpointToJSON,
    StdioAgentEndpoint,
    StdioAgentEndpointFromJSON,
    StdioAgentEndpointFromJSONTyped,
    StdioAgentEndpointToJSON,
    Visibility,
    VisibilityFromJSON,
    VisibilityFromJSONTyped,
    VisibilityToJSON,
} from './';

/**
 * 
 * @export
 * @interface Agent
 */
export interface Agent {
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    agent_record_id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Agent
     */
    consecutive_missed_heartbeats: number;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    created_at: string;
    /**
     * 
     * @type {AgentDeploymentModality}
     * @memberof Agent
     */
    deployment_modality: AgentDeploymentModality;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    description: string;
    /**
     * 
     * @type {Array<Endpoint>}
     * @memberof Agent
     */
    endpoints: Array<Endpoint>;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    last_missed_heartbeat?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    last_modified: string;
    /**
     * 
     * @type {AgentLiveness}
     * @memberof Agent
     */
    liveness: AgentLiveness;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    owner: string;
    /**
     * 
     * @type {Array<RestHttpAgentEndpoint>}
     * @memberof Agent
     */
    rest_http_endpoints: Array<RestHttpAgentEndpoint>;
    /**
     * 
     * @type {Array<RpcAgentEndpoint>}
     * @memberof Agent
     */
    rpc_endpoints: Array<RpcAgentEndpoint>;
    /**
     * 
     * @type {Array<StdioAgentEndpoint>}
     * @memberof Agent
     */
    stdio_endpoints: Array<StdioAgentEndpoint>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Agent
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    tenant_id: string;
    /**
     * 
     * @type {Visibility}
     * @memberof Agent
     */
    visibility: Visibility;
}

export function AgentFromJSON(json: any): Agent {
    return AgentFromJSONTyped(json, false);
}

export function AgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Agent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agent_record_id': !exists(json, 'agent_record_id') ? undefined : json['agent_record_id'],
        'consecutive_missed_heartbeats': json['consecutive_missed_heartbeats'],
        'created_at': json['created_at'],
        'deployment_modality': AgentDeploymentModalityFromJSON(json['deployment_modality']),
        'description': json['description'],
        'endpoints': ((json['endpoints'] as Array<any>).map(EndpointFromJSON)),
        'id': json['id'],
        'last_missed_heartbeat': !exists(json, 'last_missed_heartbeat') ? undefined : json['last_missed_heartbeat'],
        'last_modified': json['last_modified'],
        'liveness': AgentLivenessFromJSON(json['liveness']),
        'name': json['name'],
        'owner': json['owner'],
        'rest_http_endpoints': ((json['rest_http_endpoints'] as Array<any>).map(RestHttpAgentEndpointFromJSON)),
        'rpc_endpoints': ((json['rpc_endpoints'] as Array<any>).map(RpcAgentEndpointFromJSON)),
        'stdio_endpoints': ((json['stdio_endpoints'] as Array<any>).map(StdioAgentEndpointFromJSON)),
        'tags': json['tags'],
        'tenant_id': json['tenant_id'],
        'visibility': VisibilityFromJSON(json['visibility']),
    };
}

export function AgentToJSON(value?: Agent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agent_record_id': value.agent_record_id,
        'consecutive_missed_heartbeats': value.consecutive_missed_heartbeats,
        'created_at': value.created_at,
        'deployment_modality': AgentDeploymentModalityToJSON(value.deployment_modality),
        'description': value.description,
        'endpoints': ((value.endpoints as Array<any>).map(EndpointToJSON)),
        'id': value.id,
        'last_missed_heartbeat': value.last_missed_heartbeat,
        'last_modified': value.last_modified,
        'liveness': AgentLivenessToJSON(value.liveness),
        'name': value.name,
        'owner': value.owner,
        'rest_http_endpoints': ((value.rest_http_endpoints as Array<any>).map(RestHttpAgentEndpointToJSON)),
        'rpc_endpoints': ((value.rpc_endpoints as Array<any>).map(RpcAgentEndpointToJSON)),
        'stdio_endpoints': ((value.stdio_endpoints as Array<any>).map(StdioAgentEndpointToJSON)),
        'tags': value.tags,
        'tenant_id': value.tenant_id,
        'visibility': VisibilityToJSON(value.visibility),
    };
}

