/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AgentLiveness {
    Alive = 'Alive',
    Dead = 'Dead'
}

export function AgentLivenessFromJSON(json: any): AgentLiveness {
    return AgentLivenessFromJSONTyped(json, false);
}

export function AgentLivenessFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentLiveness {
    return json as AgentLiveness;
}

export function AgentLivenessToJSON(value?: AgentLiveness | null): any {
    return value as any;
}

