/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Capabilities
 */
export interface Capabilities {
    /**
     * 
     * @type {boolean}
     * @memberof Capabilities
     */
    push_notifications: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Capabilities
     */
    streaming: boolean;
}

export function CapabilitiesFromJSON(json: any): Capabilities {
    return CapabilitiesFromJSONTyped(json, false);
}

export function CapabilitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Capabilities {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'push_notifications': json['push_notifications'],
        'streaming': json['streaming'],
    };
}

export function CapabilitiesToJSON(value?: Capabilities | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'push_notifications': value.push_notifications,
        'streaming': value.streaming,
    };
}

