/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AgentRecord,
    AgentRecordFromJSON,
    AgentRecordFromJSONTyped,
    AgentRecordToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateAgentRecordResponse
 */
export interface CreateAgentRecordResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRecordResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof CreateAgentRecordResponse
     */
    metadata: object;
    /**
     * 
     * @type {AgentRecord}
     * @memberof CreateAgentRecordResponse
     */
    result: AgentRecord;
    /**
     * 
     * @type {number}
     * @memberof CreateAgentRecordResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentRecordResponse
     */
    version: string;
}

export function CreateAgentRecordResponseFromJSON(json: any): CreateAgentRecordResponse {
    return CreateAgentRecordResponseFromJSONTyped(json, false);
}

export function CreateAgentRecordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAgentRecordResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': AgentRecordFromJSON(json['result']),
        'status': json['status'],
        'version': json['version'],
    };
}

export function CreateAgentRecordResponseToJSON(value?: CreateAgentRecordResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': AgentRecordToJSON(value.result),
        'status': value.status,
        'version': value.version,
    };
}

