/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Agent,
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateAgentResponse
 */
export interface CreateAgentResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateAgentResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof CreateAgentResponse
     */
    metadata: object;
    /**
     * 
     * @type {Agent}
     * @memberof CreateAgentResponse
     */
    result: Agent;
    /**
     * 
     * @type {number}
     * @memberof CreateAgentResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentResponse
     */
    version: string;
}

export function CreateAgentResponseFromJSON(json: any): CreateAgentResponse {
    return CreateAgentResponseFromJSONTyped(json, false);
}

export function CreateAgentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAgentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': AgentFromJSON(json['result']),
        'status': json['status'],
        'version': json['version'],
    };
}

export function CreateAgentResponseToJSON(value?: CreateAgentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': AgentToJSON(value.result),
        'status': value.status,
        'version': value.version,
    };
}

