/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Agent,
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListAgentsResponse
 */
export interface ListAgentsResponse {
    /**
     * 
     * @type {string}
     * @memberof ListAgentsResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ListAgentsResponse
     */
    metadata: object;
    /**
     * 
     * @type {Array<Agent>}
     * @memberof ListAgentsResponse
     */
    result: Array<Agent>;
    /**
     * 
     * @type {number}
     * @memberof ListAgentsResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListAgentsResponse
     */
    version: string;
}

export function ListAgentsResponseFromJSON(json: any): ListAgentsResponse {
    return ListAgentsResponseFromJSONTyped(json, false);
}

export function ListAgentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAgentsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ((json['result'] as Array<any>).map(AgentFromJSON)),
        'status': json['status'],
        'version': json['version'],
    };
}

export function ListAgentsResponseToJSON(value?: ListAgentsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ((value.result as Array<any>).map(AgentToJSON)),
        'status': value.status,
        'version': value.version,
    };
}

