/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AgentRecord,
    AgentRecordFromJSON,
    AgentRecordFromJSONTyped,
    AgentRecordToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListAgentRecordsResponse
 */
export interface ListAgentRecordsResponse {
    /**
     * 
     * @type {string}
     * @memberof ListAgentRecordsResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ListAgentRecordsResponse
     */
    metadata: object;
    /**
     * 
     * @type {Array<AgentRecord>}
     * @memberof ListAgentRecordsResponse
     */
    result: Array<AgentRecord>;
    /**
     * 
     * @type {number}
     * @memberof ListAgentRecordsResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListAgentRecordsResponse
     */
    version: string;
}

export function ListAgentRecordsResponseFromJSON(json: any): ListAgentRecordsResponse {
    return ListAgentRecordsResponseFromJSONTyped(json, false);
}

export function ListAgentRecordsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAgentRecordsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ((json['result'] as Array<any>).map(AgentRecordFromJSON)),
        'status': json['status'],
        'version': json['version'],
    };
}

export function ListAgentRecordsResponseToJSON(value?: ListAgentRecordsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ((value.result as Array<any>).map(AgentRecordToJSON)),
        'status': value.status,
        'version': value.version,
    };
}

