/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MessageBinding {
    HttpJson = 'HttpJson',
    JsonRpc20 = 'JsonRpc2_0',
    Grpc = 'Grpc'
}

export function MessageBindingFromJSON(json: any): MessageBinding {
    return MessageBindingFromJSONTyped(json, false);
}

export function MessageBindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageBinding {
    return json as MessageBinding;
}

export function MessageBindingToJSON(value?: MessageBinding | null): any {
    return value as any;
}

