/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RestHttpLivenessProbe
 */
export interface RestHttpLivenessProbe {
    /**
     * 
     * @type {number}
     * @memberof RestHttpLivenessProbe
     */
    initial_delay_seconds: number;
    /**
     * 
     * @type {number}
     * @memberof RestHttpLivenessProbe
     */
    interval_seconds: number;
    /**
     * 
     * @type {number}
     * @memberof RestHttpLivenessProbe
     */
    missed_heartbeat_threshold: number;
    /**
     * 
     * @type {string}
     * @memberof RestHttpLivenessProbe
     */
    route: string;
    /**
     * 
     * @type {number}
     * @memberof RestHttpLivenessProbe
     */
    timeout_seconds: number;
}

export function RestHttpLivenessProbeFromJSON(json: any): RestHttpLivenessProbe {
    return RestHttpLivenessProbeFromJSONTyped(json, false);
}

export function RestHttpLivenessProbeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestHttpLivenessProbe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'initial_delay_seconds': json['initial_delay_seconds'],
        'interval_seconds': json['interval_seconds'],
        'missed_heartbeat_threshold': json['missed_heartbeat_threshold'],
        'route': json['route'],
        'timeout_seconds': json['timeout_seconds'],
    };
}

export function RestHttpLivenessProbeToJSON(value?: RestHttpLivenessProbe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'initial_delay_seconds': value.initial_delay_seconds,
        'interval_seconds': value.interval_seconds,
        'missed_heartbeat_threshold': value.missed_heartbeat_threshold,
        'route': value.route,
        'timeout_seconds': value.timeout_seconds,
    };
}

