/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MessageBinding,
    MessageBindingFromJSON,
    MessageBindingFromJSONTyped,
    MessageBindingToJSON,
} from './';

/**
 * 
 * @export
 * @interface RpcAgentInterface
 */
export interface RpcAgentInterface {
    /**
     * 
     * @type {string}
     * @memberof RpcAgentInterface
     */
    description?: string | null;
    /**
     * 
     * @type {MessageBinding}
     * @memberof RpcAgentInterface
     */
    message_binding?: MessageBinding;
    /**
     * 
     * @type {string}
     * @memberof RpcAgentInterface
     */
    name: string;
}

export function RpcAgentInterfaceFromJSON(json: any): RpcAgentInterface {
    return RpcAgentInterfaceFromJSONTyped(json, false);
}

export function RpcAgentInterfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcAgentInterface {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'message_binding': !exists(json, 'message_binding') ? undefined : MessageBindingFromJSON(json['message_binding']),
        'name': json['name'],
    };
}

export function RpcAgentInterfaceToJSON(value?: RpcAgentInterface | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'message_binding': MessageBindingToJSON(value.message_binding),
        'name': value.name,
    };
}

