/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MessageBinding,
    MessageBindingFromJSON,
    MessageBindingFromJSONTyped,
    MessageBindingToJSON,
} from './';

/**
 * 
 * @export
 * @interface StdioAgentEndpoint
 */
export interface StdioAgentEndpoint {
    /**
     * 
     * @type {string}
     * @memberof StdioAgentEndpoint
     */
    base_url?: string | null;
    /**
     * 
     * @type {MessageBinding}
     * @memberof StdioAgentEndpoint
     */
    message_binding?: MessageBinding;
    /**
     * 
     * @type {string}
     * @memberof StdioAgentEndpoint
     */
    name?: string | null;
}

export function StdioAgentEndpointFromJSON(json: any): StdioAgentEndpoint {
    return StdioAgentEndpointFromJSONTyped(json, false);
}

export function StdioAgentEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): StdioAgentEndpoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'base_url': !exists(json, 'base_url') ? undefined : json['base_url'],
        'message_binding': !exists(json, 'message_binding') ? undefined : MessageBindingFromJSON(json['message_binding']),
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function StdioAgentEndpointToJSON(value?: StdioAgentEndpoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'base_url': value.base_url,
        'message_binding': MessageBindingToJSON(value.message_binding),
        'name': value.name,
    };
}

