# Stage 1: Compile the code
FROM rust:1.88.0 AS builder

ARG SERVICE_NAME
ARG SERVICE_DIR
ARG LIBS_DIR
ARG SDKS_DIR

# Create 
RUN mkdir -p /usr/local/mlhub/services/${SERVICE_NAME} /usr/local/mlhub/libs /usr/local/mlhub/sdks

# Copy shared libraries code
WORKDIR /usr/local/mlhub/libs
COPY ${LIBS_DIR} .

WORKDIR /usr/local/mlhub/sdks
COPY ${SDKS_DIR} .

# Copy service code
WORKDIR /usr/local/mlhub/services/${SERVICE_NAME}
COPY ${SERVICE_DIR} .

# Install
RUN cargo build --release

# Stage 2: Copy the binary to a slim Linux image
FROM debian:bookworm-slim

ARG SERVICE_NAME

RUN apt-get update && rm -rf /var/lib/apt/lists/*
RUN apt update
RUN apt install libssl3
RUN apt-get install -y --no-install-recommends ca-certificates
RUN update-ca-certificates

COPY --from=builder /usr/local/mlhub/services/${SERVICE_NAME}/target/release/${SERVICE_NAME} /usr/local/bin/mlhub

ENV RUST_LOG=debug,shared=debug

CMD ["mlhub"]