use crate::config::VERSION;
use platforms::Platform;
use shared::presentation::http::v1::responses::artifacts::{
    ingestions::ArtifactIngestion, publications::ArtifactPublication, Artifact,
};
use utoipa::OpenApi;

// Here we are import the helper function generated by utoipa to generate docs for
// handlers
use super::handlers::associate_model_with_artifact::__path_associate_model_with_artifact;
use super::handlers::create_model::__path_create_model;
use super::handlers::discover_external_models::__path_discover_external_models;
use super::handlers::get_external_model::__path_get_external_model;
use super::handlers::get_model::__path_get_model;
use super::handlers::get_model_artifact::__path_get_model_artifact;
use super::handlers::get_model_ingestion::__path_get_model_ingestion;
use super::handlers::get_model_publication::__path_get_model_publication;
use super::handlers::list_model_artifacts::__path_list_model_artifacts;
use super::handlers::list_model_ingestions::__path_list_model_ingestions;
use super::handlers::list_model_publications::__path_list_model_publications;
use super::handlers::list_models::__path_list_models;
use super::handlers::list_platforms::__path_list_platforms;
use super::handlers::list_publications_for_artifact::__path_list_publications_for_artifact;
use super::handlers::list_tasks::__path_list_tasks;
use super::handlers::publish_model_artifact::__path_publish_model_artifact;

#[derive(OpenApi)]
#[openapi(
    info(title = "MLHub Models API", version=VERSION),
    paths(
        get_model,
        list_models,
        get_external_model,
        discover_external_models,
        get_model_artifact,
        associate_model_with_artifact,
        get_model_ingestion,
        get_model_publication,
        list_publications_for_artifact,
        publish_model_artifact,
        list_model_artifacts,
        list_model_ingestions,
        list_model_publications,
        list_platforms,
        list_tasks,
        create_model,
    ),
    components(
        schemas(
            Platform,
            Artifact,
            ArtifactPublication,
            ArtifactIngestion
        )
    ),
)]
pub struct ApiDoc;
