#!/usr/bin/env bash

set -e

here=$(dirname "${BASH_SOURCE[0]}")

source $here/utils

specsDir=$here/specs/latest
genDir=$(get_gen_dir $here)
templatesDir=$here/templates

mkdir -p $specsDir
mkdir -p $genDir

# This array determines which APIs get called to fetch the schema
taxa=("tasks")

# Fetch OASF Domains, Skills, and Modules and pretty-print them into the specs dir
for taxon in "${taxa[@]}"; do
    echo "Fetching $taxon"
    output=$(curl -X 'GET' "https://huggingface.co/api/${taxon}" -H 'accept: application/json' -s)
    echo $output | jq . > $specsDir/$taxon.json
    python3 $here/scripts/generate.py $here/specs/latest/$taxon.json $genDir $templatesDir
done
