use crate::infra::persistence::mongo::documents::domains as documents;
use crate::application::inputs::domains as inputs;

impl From<inputs::Domain> for documents::Domain {
    fn from(value: inputs::Domain) -> Self {
        match value {
            inputs::Domain::Automation => documents::Domain::Automation,
            inputs::Domain::Automotive => documents::Domain::Automotive,
            inputs::Domain::AutonomousVehicles => documents::Domain::AutonomousVehicles,
            inputs::Domain::Banking => documents::Domain::Banking,
            inputs::Domain::Bioinformatics => documents::Domain::Bioinformatics,
            inputs::Domain::Biotechnology => documents::Domain::Biotechnology,
            inputs::Domain::CommunicationSystems => documents::Domain::CommunicationSystems,
            inputs::Domain::CompensationAndBenefits => documents::Domain::CompensationAndBenefits,
            inputs::Domain::ConsumerGoods => documents::Domain::ConsumerGoods,
            inputs::Domain::ContentModeration => documents::Domain::ContentModeration,
            inputs::Domain::CurriculumDesign => documents::Domain::CurriculumDesign,
            inputs::Domain::DataPrivacy => documents::Domain::DataPrivacy,
            inputs::Domain::ELearning => documents::Domain::ELearning,
            inputs::Domain::Education => documents::Domain::Education,
            inputs::Domain::EducationalTechnology => documents::Domain::EducationalTechnology,
            inputs::Domain::EmployeeRelations => documents::Domain::EmployeeRelations,
            inputs::Domain::Finance => documents::Domain::Finance,
            inputs::Domain::FinanceAndBusiness => documents::Domain::FinanceAndBusiness,
            inputs::Domain::FraudPrevention => documents::Domain::FraudPrevention,
            inputs::Domain::Freight => documents::Domain::Freight,
            inputs::Domain::Genomics => documents::Domain::Genomics,
            inputs::Domain::HealthInformationSystems => documents::Domain::HealthInformationSystems,
            inputs::Domain::Healthcare => documents::Domain::Healthcare,
            inputs::Domain::HealthcareInformatics => documents::Domain::HealthcareInformatics,
            inputs::Domain::HrAnalytics => documents::Domain::HrAnalytics,
            inputs::Domain::HumanResources => documents::Domain::HumanResources,
            inputs::Domain::IndustrialManufacturing => documents::Domain::IndustrialManufacturing,
            inputs::Domain::InformationTechnology => documents::Domain::InformationTechnology,
            inputs::Domain::InternetOfThings => documents::Domain::InternetOfThings,
            inputs::Domain::InvestmentServices => documents::Domain::InvestmentServices,
            inputs::Domain::LeanManufacturing => documents::Domain::LeanManufacturing,
            inputs::Domain::LearningManagementSystems => documents::Domain::LearningManagementSystems,
            inputs::Domain::LifeScience => documents::Domain::LifeScience,
            inputs::Domain::Logistics => documents::Domain::Logistics,
            inputs::Domain::MedicalTechnology => documents::Domain::MedicalTechnology,
            inputs::Domain::MolecularBiology => documents::Domain::MolecularBiology,
            inputs::Domain::NetworkManagement => documents::Domain::NetworkManagement,
            inputs::Domain::NetworkOperations => documents::Domain::NetworkOperations,
            inputs::Domain::Networking => documents::Domain::Networking,
            inputs::Domain::OnlineSafety => documents::Domain::OnlineSafety,
            inputs::Domain::PatientManagementSystems => documents::Domain::PatientManagementSystems,
            inputs::Domain::Pedagogy => documents::Domain::Pedagogy,
            inputs::Domain::PharmaceuticalResearch => documents::Domain::PharmaceuticalResearch,
            inputs::Domain::ProcessEngineering => documents::Domain::ProcessEngineering,
            inputs::Domain::PublicTransit => documents::Domain::PublicTransit,
            inputs::Domain::Recruitment => documents::Domain::Recruitment,
            inputs::Domain::Retail => documents::Domain::Retail,
            inputs::Domain::RiskManagement => documents::Domain::RiskManagement,
            inputs::Domain::Robotics => documents::Domain::Robotics,
            inputs::Domain::Security => documents::Domain::Security,
            inputs::Domain::SoftwareEngineering => documents::Domain::SoftwareEngineering,
            inputs::Domain::SupplyChain => documents::Domain::SupplyChain,
            inputs::Domain::SupplyChainManagement => documents::Domain::SupplyChainManagement,
            inputs::Domain::Technology => documents::Domain::Technology,
            inputs::Domain::Telemedicine => documents::Domain::Telemedicine,
            inputs::Domain::TrainingAndDevelopment => documents::Domain::TrainingAndDevelopment,
            inputs::Domain::Transportation => documents::Domain::Transportation,
            inputs::Domain::TrustAndSafety => documents::Domain::TrustAndSafety,
        }
    }
}