kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlhub-artifact-op-mq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi