#!/usr/bin/env bash

set -e

here=$(dirname "${BASH_SOURCE[0]}")

source $here/utils

genDir=$(get_gen_dir $here)

# Even with 10+ years of Linux experience, I DELETED A FULL DAY'S WORTH OF CODE BY NOT REPSECTING THE LINE BELOW
rm -rf $here/src

if [ -f $here/Cargo.toml ]; then
    rm $here/Cargo.toml
fi

cargo init --lib --name agntcy-sdk --vcs none $here

# Replace the 0.1.0 with the current version of the OASF API
sed -i "s/^version = \"0.1.0\"/version = \"$(get_oasf_version)\"/" $here/Cargo.toml

: > $here/src/lib.rs

echo >> $here/Cargo.toml
echo "[features]" >> $here/Cargo.toml

default_features_string="default = ["
default_features=""
features=""
for file in "$genDir"/*; do
    filename=$(basename $file)
    taxon=${filename%.*}
    mkdir -p $here/src/$taxon
    cp $genDir/$taxon.rs $here/src/$taxon/mod.rs
    echo "pub mod $taxon;" >> $here/src/lib.rs
    default_features+="\"$taxon\", "
    features+="$taxon = []\n"
done

features+="identify = []"

default_features_string="$default_features_string $default_features]"
echo $default_features_string >> $here/Cargo.toml
echo -e $features >> $here/Cargo.toml
