pub mod agntcy_domain_to_domain;

#[doc = "Distinct fields of application and knowledge areas"]
pub enum Domain {
    #[doc = "Software platforms for delivering, tracking, and managing educational courses and training programs. Subdomains: User Experience Design, Content Management, Reporting and Analytics, and System Integration."]
    LearningManagementSystems,
    #[doc = "Mobile networks, 5G/6G technology, wireless protocols, and cellular services"]
    WirelessCommunications,
    #[doc = "Safeguarding personal information from unauthorized access and ensuring compliance with privacy laws and regulations. Subdomains: Privacy Regulations Compliance, Data Encryption, Data Anonymization, and User Consent Management."]
    DataPrivacy,
    #[doc = "Hotel operations, reservations, guest services, and property management systems"]
    HotelManagement,
    #[doc = "Production of digital and traditional media content including video, audio, and written material."]
    ContentCreation,
    #[doc = "Lab operations, equipment management, safety protocols, and laboratory information systems"]
    LaboratoryManagement,
    #[doc = "Care, breeding, and management of farm animals and livestock operations."]
    LivestockManagement,
    #[doc = "Maintaining positive relationships between the employer and employees to foster a productive work environment. Subdomains: Conflict Resolution, Employee Engagement, Workplace Culture, and Labor Relations."]
    EmployeeRelations,
    #[doc = "Communication technologies that use electromagnetic waves to transmit data without physical connections."]
    WirelessCommunication,
    #[doc = "Attracting, screening, and selecting qualified candidates for job openings within an organization. Subdomains: Talent Acquisition, Candidate Sourcing, Interviewing Techniques, and Onboarding Processes."]
    Recruitment,
    #[doc = "Intelligent power distribution networks with automated monitoring and control."]
    SmartGrids,
    #[doc = "Claims management, loss adjustment, claims automation, and settlement processes"]
    ClaimsProcessing,
    #[doc = "The application of biological systems and organisms to develop or create products and technologies that improve the quality of human life. Subdomains: Medical Biotechnology, Agricultural Biotechnology, Industrial Biotechnology, and Environmental Biotechnology."]
    Biotechnology,
    #[doc = "Property investment strategies, portfolio management, and real estate finance."]
    RealEstateInvestment,
    #[doc = "Integrating digital tools and resources to enhance teaching and learning experiences. Subdomains: EdTech Innovations, Classroom Technology, Digital Content, and Gamification in Education."]
    EducationalTechnology,
    #[doc = "Cybersecurity protection of network infrastructure and data from unauthorized access, misuse, or attacks."]
    CyberNetworkSecurity,
    #[doc = "Self-executing contracts with terms directly written into code, running on blockchain networks."]
    SmartContracts,
    #[doc = "Using technology to perform processes with minimal human intervention. Subdomains: Automated Manufacturing, Control Systems, Industrial IoT, and Process Automation."]
    Automation,
    #[doc = "Ensuring adherence to laws, regulations, and industry standards."]
    RegulatoryCompliance,
    #[doc = "Design, management, and security of computer networks."]
    Networking,
    #[doc = "On-demand video and audio streaming platforms and content delivery."]
    StreamingServices,
    #[doc = "Research funding, grant applications, project budgeting, and compliance reporting"]
    GrantManagement,
    #[doc = "Use of technology to perform processes or procedures with minimal human intervention."]
    ProcessAutomation,
    #[doc = "Environmentally responsible agricultural practices and organic farming methods."]
    SustainableFarming,
    #[doc = "the application of computational techniques to analyze and interpret biological data. Subdomains: Sequence Analysis, Systems Biology, Data Mining, and Structural Bioinformatics."]
    Bioinformatics,
    #[doc = "Physical devices embedded with sensors, software, and connectivity to collect and exchange data."]
    IotDevices,
    #[doc = "Connecting everyday objects to the internet for data exchange and automation."]
    InternetOfThings,
    #[doc = "Voice over IP, video conferencing, unified communications platforms, and collaboration tools"]
    VoipAndUnifiedCommunications,
    #[doc = "Marketing metrics, ROI analysis, attribution modeling, and performance tracking"]
    MarketingAnalytics,
    #[doc = "Innovations and devices used to improve the diagnosis, treatment, and management of health conditions. Subdomains: Medical Devices, Diagnostic Equipment, Wearable Health Tech, and Biotech Innovations."]
    MedicalTechnology,
    #[doc = "Rules and standards that govern communication between devices in a network."]
    NetworkProtocols,
    #[doc = "Technologies for transmitting and receiving information over various media."]
    CommunicationSystems,
    #[doc = "Transmission of information over long distances using electronic and digital technologies."]
    Telecommunication,
    #[doc = "Automation of business processes through the use of software to reduce manual work and improve efficiency."]
    WorkflowAutomation,
    #[doc = "ISP operations, broadband services, internet connectivity, and access technologies"]
    InternetServices,
    #[doc = "Cloud computing service created by Microsoft for building, testing, deploying, and managing applications."]
    Azure,
    #[doc = "Practices that combine software development and IT operations to shorten development cycles and improve deployment reliability."]
    Devops,
    #[doc = "IoT applications in industrial settings for automation, monitoring, and optimization."]
    IndustrialIot,
    #[doc = "Process of designing, creating, testing, and maintaining software applications and systems."]
    SoftwareDevelopment,
    #[doc = "Performance metrics, game analysis, player statistics, and sports data science"]
    SportsAnalytics,
    #[doc = "Systems for managing healthcare data to support clinical and administrative decision-making. Subdomains: Hospital Information Systems, Clinical Decision Support, Health Data Security, and Interoperability Solutions."]
    HealthInformationSystems,
    #[doc = "The design, development, manufacturing, and marketing of motor vehicles. Subdomains: Vehicle Design, Automotive Engineering, Electric Vehicles, and Vehicle Manufacturing."]
    Automotive,
    #[doc = "Book, magazine, and digital publishing operations and distribution."]
    Publishing,
    #[doc = "Protection of digital data from unauthorized access, corruption, or theft throughout its lifecycle."]
    DataSecurity,
    #[doc = "Protection of IoT devices, networks, and data from cyber threats and vulnerabilities."]
    IotSecurity,
    #[doc = "City planning, zoning, and urban development strategies."]
    UrbanPlanning,
    #[doc = "Ecosystem science, ecological modeling, population dynamics, and environmental interactions"]
    Ecology,
    #[doc = "Building construction, project management, and construction technology."]
    Construction,
    #[doc = "Restaurant management, catering services, menu planning, and culinary operations"]
    FoodAndBeverage,
    #[doc = "Performance training, coaching, workout programs, and athlete development"]
    AthleticTraining,
    #[doc = "Vehicles equipped with technology to navigate and operate without human control. Subdomains: Self-Driving Cars, Autonomous Trucks, Sensor Technology, and Vehicle AI."]
    AutonomousVehicles,
    #[doc = "Operations of financial institutions involved in accepting deposits, lending money, and other financial services. Subdomains: Retail Banking, Investment Banking, Corporate Banking, and Digital Banking."]
    Banking,
    #[doc = "Exploration, extraction, refining, and distribution of petroleum products."]
    OilAndGas,
    #[doc = "Disability support, accessibility services, assistive technology, and disability advocacy"]
    DisabilityServices,
    #[doc = "Management and maintenance of database systems and data storage."]
    DatabaseAdministration,
    #[doc = "Large and complex datasets that require advanced tools and techniques for processing and analysis."]
    BigData,
    #[doc = "Protecting systems, data, and networks from cyber threats and vulnerabilities."]
    Security,
    #[doc = "Communication protocols and network infrastructure for connecting IoT devices."]
    IotNetworks,
    #[doc = "Tasks like monitoring, configuring, and optimizing networks."]
    NetworkManagement,
    #[doc = "Managing money, investments, and financial risks within businesses or for individuals. Subdomains: Corporate Finance, Personal Finance, Risk Management, Accounting, and Financial Analysis."]
    Finance,
    #[doc = "Air quality monitoring, water quality testing, pollution tracking, and environmental sensors"]
    EnvironmentalMonitoring,
    #[doc = "Sale of goods and services directly to consumers through various channels. Subdomains: E-commerce, In-store Retail, Inventory Management, Customer Experience, and Omnichannel Retail."]
    Retail,
    #[doc = "Processes and tools for detecting, responding to, and resolving security incidents and IT service disruptions."]
    IncidentManagement,
    #[doc = "Coordinating and managing all activities involved in the production and delivery of goods. Subdomains: Inventory Management, Procurement, Logistics Management, and Demand Forecasting."]
    SupplyChainManagement,
    #[doc = "Designing, implementing, and optimizing industrial processes to improve efficiency and quality. Subdomains: Process Design, Process Optimization, Quality Control, and Safety Engineering."]
    ProcessEngineering,
    #[doc = "Processes and technologies for managing digital identities and controlling access to resources."]
    IdentityManagement,
    #[doc = "The system of production, processing, and distribution of goods. Subdomains: Supplier Management, Production Scheduling, Inventory Control, and Global Supply Chain."]
    SupplyChain,
    #[doc = "Protection and management of patents, trademarks, copyrights, and trade secrets."]
    IntellectualProperty,
    #[doc = "Financial services built on blockchain networks that operate without traditional intermediaries."]
    Defi,
    #[doc = "Design and construction of systems for collecting, storing, and processing data at scale."]
    DataEngineering,
    #[doc = "Application Programming Interfaces and integration technologies that enable different software systems to communicate and work together."]
    ApisIntegration,
    #[doc = "Comprehensive cloud computing platform offered by Amazon."]
    Aws,
    #[doc = "Delivering educational content and instruction through digital platforms and online courses. Subdomains: Online Course Development, Virtual Classrooms, Interactive Learning Tools, and Mobile Learning."]
    ELearning,
    #[doc = "Designing and using robots for manufacturing tasks to enhance productivity and precision. Subdomains: Robotic Process Automation, Industrial Robotics, AI and Robotics, and Collaborative Robots."]
    Robotics,
    #[doc = "Policy administration, renewals, endorsements, and policy lifecycle management"]
    PolicyManagement,
    #[doc = "Management and maintenance of computer systems and servers."]
    SystemAdministration,
    #[doc = "Homeless services, housing support, emergency shelter, and housing programs"]
    HousingAssistance,
    #[doc = "Protecting internet users from various forms of harm to ensure a secure digital environment. Subdomains: Cybersecurity Awareness, Child Online Protection, Identity Protection, and Digital Wellbeing."]
    OnlineSafety,
    #[doc = "Climate modeling, climate change research, atmospheric science, and weather prediction"]
    ClimateScience,
    #[doc = "Marketing platforms, campaign automation, lead nurturing, and marketing technology"]
    MarketingAutomation,
    #[doc = "Actuarial analysis, risk modeling, statistical modeling, and pricing strategies"]
    ActuarialScience,
    #[doc = "Battery systems, pumped hydro, and other energy storage technologies."]
    EnergyStorage,
    #[doc = "Technology that uses software robots to automate repetitive, rule-based tasks typically performed by humans."]
    Rpa,
    #[doc = "Ensures the smooth operation and performance of network infrastructure."]
    NetworkOperations,
    #[doc = "Providing employees with skills and knowledge to enhance their job performance and career growth. Subdomains: Skills Training, Leadership Development, Career Pathing, and E-Learning Platforms."]
    TrainingAndDevelopment,
    #[doc = "New product design, prototyping, testing, and product lifecycle management"]
    ProductDevelopment,
    #[doc = "POS systems, retail checkout, payment processing, and in-store transactions"]
    PointOfSale,
    #[doc = "Digital or virtual currency secured by cryptography, typically operating on blockchain technology."]
    Cryptocurrency,
    #[doc = "Managing financial assets, investment portfolios, and providing advisory services to clients. Subdomains: Asset Management, Hedge Funds, Private Equity, Mutual Funds, and Financial Planning."]
    InvestmentServices,
    #[doc = "Service provisioning, billing systems, customer management, and operations support"]
    TelecomOperations,
    #[doc = "The coordination of complex operations involving people, facilities, and supplies. Subdomains: Warehousing, Distribution Management, Transportation Planning, and Reverse Logistics."]
    Logistics,
    #[doc = "Mental health support, counseling, crisis intervention, and psychological services"]
    MentalHealthServices,
    #[doc = "SEO, SEM, content marketing, social media marketing, and online campaigns"]
    DigitalMarketing,
    #[doc = "Order processing, shipping, logistics, returns management, and last-mile delivery"]
    OrderFulfillment,
    #[doc = "Radio and television broadcasting systems and operations."]
    Broadcasting,
    #[doc = "Social media, blogs, podcasts, and other digital content platforms."]
    DigitalMedia,
    #[doc = "Suite of cloud computing services offered by Google."]
    Gcp,
    #[doc = "Technical support and assistance for end users and IT systems."]
    HelpDeskSupport,
    #[doc = "The transportation of goods in bulk. Subdomains: Freight Forwarding, Cargo Management, Logistics Operations, and Freight Brokerage."]
    Freight,
    #[doc = "Protection of network infrastructure and data from unauthorized access and attacks."]
    NetworkSecurity,
    #[doc = "Environmental regulations, policy development, compliance, and environmental law"]
    EnvironmentalPolicy,
    #[doc = "The methods and practices of teaching, focusing on how best to convey knowledge and skills to learners. Subdomains: Teaching Strategies, Student-Centered Learning, Instructional Theory, and Learning Styles."]
    Pedagogy,
    #[doc = "Wearable devices, performance tracking systems, sports apps, and fitness technology"]
    SportsTechnology,
    #[doc = "Property management systems, booking engines, guest experience platforms, and hospitality software"]
    HospitalityTechnology,
    #[doc = "Legal principles governing agreements and contracts between parties."]
    ContractLaw,
    #[doc = "Data storage, research databases, data sharing, and research informatics"]
    ResearchDataManagement,
    #[doc = "IoT networks, M2M communications, NB-IoT, LoRaWAN, and connected device management"]
    IotConnectivity,
    #[doc = "Brand strategy, brand identity, brand positioning, and reputation management"]
    BrandManagement,
    #[doc = "Fitness programs, wellness coaching, health tracking, and personal training"]
    FitnessAndWellness,
    #[doc = "Solar, wind, hydro, and other sustainable energy sources and technologies."]
    RenewableEnergy,
    #[doc = "Analysis, modification, and synthesis of signals such as sound, images, and sensor data."]
    SignalProcessing,
    #[doc = "Legal proceedings and dispute resolution through court systems."]
    Litigation,
    #[doc = "Policy development, legislative processes, policy analysis, and public affairs"]
    PublicPolicy,
    #[doc = "Methodology focusing on minimizing waste and maximizing efficiency in the production process. Subdomains: Continuous Improvement, Six Sigma, Value Stream Mapping, and Kaizen."]
    LeanManufacturing,
    #[doc = "Systems for distributing audio and video content to large audiences via radio, television, or internet."]
    BroadcastingSystems,
    #[doc = "The delivery of healthcare services through telecommunications technology. Subdomains: Remote Consultation, Telehealth Platforms, Mobile Health, and Virtual Care."]
    Telemedicine,
    #[doc = "E-commerce platforms, online storefronts, digital marketplaces, and web retail"]
    OnlineRetail,
    #[doc = "Using data analysis to improve HR decision-making, workforce planning, and employee performance metrics. Subdomains: People Analytics, Predictive HR, Workforce Metrics, and Data-Driven HR Strategies."]
    HrAnalytics,
    #[doc = "Creation, marketing, and distribution of products intended for personal use. Subdomains: Product Development, Consumer Behavior, Marketing, Retail, and Supply Chain Management."]
    ConsumerGoods,
    #[doc = "Building operations, maintenance, and facility services."]
    FacilitiesManagement,
    #[doc = "Property technology innovations including smart buildings and real estate platforms."]
    Proptech,
    #[doc = "Investigation of legal precedents, statutes, and case law."]
    LegalResearch,
    #[doc = "Team management, sports facilities, event organization, and sports administration"]
    SportsManagement,
    #[doc = "Injury prevention, sports rehabilitation, athletic healthcare, and performance medicine"]
    SportsMedicine,
    #[doc = "Systems, principles, and processes for directing and controlling corporations."]
    CorporateGovernance,
    #[doc = "Sales analytics, customer insights, merchandising analytics, and retail intelligence"]
    RetailAnalytics,
    #[doc = "Designing, developing, and maintaining software applications and systems."]
    SoftwareEngineering,
    #[doc = "Child welfare, family support, foster care, adoption services, and family counseling"]
    ChildAndFamilyServices,
    #[doc = "Graphical representation of information and data using visual elements like charts, graphs, and maps."]
    DataVisualization,
    #[doc = "Risk assessment, policy pricing, underwriting automation, and risk evaluation"]
    Underwriting,
    #[doc = "Analysis and optimization of system performance to ensure efficient operation."]
    PerformanceAnalysis,
    #[doc = "Identifying and stopping fraudulent activities to protect individuals and organizations from financial and reputational damage. Subdomains: Transaction Monitoring, Identity Verification, Fraud Analytics, and Fraud Awareness Training."]
    FraudPrevention,
    #[doc = "Species conservation, habitat protection, biodiversity, and wildlife management"]
    ConservationBiology,
    #[doc = "Agent management, distribution channels, customer acquisition, and sales platforms"]
    InsuranceSales,
    #[doc = "Delivery of computing services including servers, storage, databases, networking, software, and analytics over the internet."]
    CloudComputing,
    #[doc = "Disaster response, emergency planning, crisis management, and public safety coordination"]
    EmergencyManagement,
    #[doc = "The study of genomes to understand genetic structure, function, and evolution. Subdomains: Comparative Genomics, Functional Genomics, Population Genomics, and Metagenomics."]
    Genomics,
    #[doc = "Management of residential and commercial properties including maintenance and tenant relations."]
    PropertyManagement,
    #[doc = "Government operations, administrative processes, civil service, and bureaucratic systems"]
    PublicAdministration,
    #[doc = "Planning, monitoring, and optimizing crop production and yield."]
    CropManagement,
    #[doc = "Destination management, tourist attractions, tourism marketing, and visitor experiences"]
    TourismManagement,
    #[doc = "Design and structure of computer networks including topology, protocols, and components."]
    NetworkArchitecture,
    #[doc = "Software solutions that help healthcare providers manage patient information and clinical processes. Subdomains: Appointment Scheduling, Patient Portals, Billing and Coding, and Health Record Management."]
    PatientManagementSystems,
    #[doc = "Creating structured educational content and learning experiences for students. Subdomains: Instructional Design, Learning Objectives, Assessment Strategies, and Content Development."]
    CurriculumDesign,
    #[doc = "Innovation and technology applications in farming including drones, IoT, and automation."]
    AgriculturalTechnology,
    #[doc = "Data-driven farming using sensors, GPS, and analytics for optimized crop management."]
    PrecisionAgriculture,
    #[doc = "The discovery, development, and testing of new drugs and therapies to treat diseases and improve health outcomes. Subdomains: Drug Discovery, Clinical Trials, Pharmacology, and Regulatory Affairs."]
    PharmaceuticalResearch,
    #[doc = "Client case tracking, service coordination, needs assessment, and case documentation"]
    CaseManagement,
    #[doc = "Personalization, customer service, loyalty programs, and shopping experience optimization"]
    CustomerExperience,
    #[doc = "Reviewing and managing user-generated content to ensure it complies with community guidelines and legal standards. Subdomains: Automated Moderation, Community Guidelines, Human Moderation, and Harmful Content Detection."]
    ContentModeration,
    #[doc = "The management and analysis of healthcare data to improve patient care and operational efficiency. Subdomains: Electronic Health Records, Health Data Analytics, Clinical Informatics, and Health IT Systems."]
    HealthcareInformatics,
    #[doc = "Research methodology, experimental design, data collection, and scientific investigation"]
    ScientificResearch,
    #[doc = "Conference management, event coordination, venue management, and event services"]
    EventPlanning,
    #[doc = "Sustainable practices, carbon footprint reduction, circular economy, and green technology"]
    Sustainability,
    #[doc = "The base domain is a generic domain defining a set of attributes for domain classes."]
    BaseDomain,
    #[doc = "Innovation processes, idea management, technology transfer, and commercialization"]
    InnovationManagement,
    #[doc = "Video game development, esports, and interactive entertainment."]
    Gaming,
    #[doc = "Identifying, assessing, and prioritizing risks to minimize their impact on an organization's objectives and operations. Subdomains: Risk Assessment, Mitigation Strategies, Crisis Management, and Compliance and Auditing."]
    RiskManagement,
    #[doc = "All aspects of managing and supporting technology systems and infrastructure."]
    InformationTechnology,
    #[doc = "Electricity generation from various sources including nuclear, thermal, and renewable."]
    PowerGeneration,
    #[doc = "Set of practices that combines machine learning and DevOps to standardize and streamline the machine learning lifecycle."]
    Mlops,
    #[doc = "Protection of computer systems, networks, and data from digital attacks and unauthorized access."]
    Cybersecurity,
    #[doc = "Ad campaigns, media buying, creative development, and advertising platforms"]
    Advertising,
    #[doc = "Travel booking, itinerary planning, travel agencies, and booking platforms"]
    TravelServices,
    #[doc = "Security measures and practices to protect applications from threats and vulnerabilities."]
    ApplicationSecurity,
    #[doc = "Stock control, warehouse management, inventory tracking, and supply planning"]
    InventoryManagement,
    #[doc = "Distributed ledger technology that maintains a continuously growing list of records secured using cryptography."]
    Blockchain,
    #[doc = "Designing and managing salary structures, bonuses, and benefits to attract and retain employees. Subdomains: Salary Benchmarking, Benefits Administration, Incentive Programs, and Retirement Planning."]
    CompensationAndBenefits,
    #[doc = "Residential environments with IoT devices for automation, monitoring, and control."]
    SmartHomes,
    #[doc = "Consumer research, market analysis, competitive intelligence, and research methodologies"]
    MarketResearch,
    #[doc = "Infrastructure planning, public works, utilities management, and infrastructure maintenance"]
    PublicInfrastructure,
    #[doc = "Digital government services, online portals, citizen engagement platforms, and digital identity"]
    EGovernment,
    #[doc = "Processes and practices to ensure software quality through testing, code review, and quality standards."]
    QualityAssurance,
    #[doc = "Optimization of energy consumption, efficiency programs, and demand response."]
    EnergyManagement,
    #[doc = "Citizen participation, community outreach, public consultation, and participatory governance"]
    CivicEngagement,
    #[doc = "Telecom network design, fiber optics, network equipment, and infrastructure management"]
    NetworkInfrastructure,
    #[doc = "Molecular Biology is the branch of biology that focuses on the structure, function, and interactions of biological macromolecules, such as DNA, RNA, and proteins. Subdomains: Genomics, Gene Expression, and Cell Signaling."]
    MolecularBiology,
    #[doc = "Extracting insights and knowledge from structured and unstructured data using scientific methods, processes, and algorithms."]
    DataScience,
    #[doc = "Insurance technology, digital insurance platforms, telematics, and insurance innovation"]
    Insurtech,
    #[doc = "Community programs, outreach services, community engagement, and local support initiatives"]
    CommunityOutreach,
    #[doc = "Shared transportation services available for the public, such as buses and trains. Subdomains: Urban Transit Planning, Rail Systems, Bus Networks, and Transit Operations."]
    PublicTransit,

}

pub trait Identify {
    fn uid(&self) -> u32;
    fn name(&self) -> String;
}

impl Identify for Domain {
    fn uid(&self) -> u32 {
        match self {
            Domain::LearningManagementSystems => 603,
            Domain::WirelessCommunications => 1606,
            Domain::DataPrivacy => 404,
            Domain::HotelManagement => 1504,
            Domain::ContentCreation => 1302,
            Domain::LaboratoryManagement => 1903,
            Domain::LivestockManagement => 1103,
            Domain::EmployeeRelations => 502,
            Domain::WirelessCommunication => 10802,
            Domain::Recruitment => 501,
            Domain::SmartGrids => 1206,
            Domain::ClaimsProcessing => 2302,
            Domain::Biotechnology => 301,
            Domain::RealEstateInvestment => 1405,
            Domain::EducationalTechnology => 604,
            Domain::CyberNetworkSecurity => 10704,
            Domain::SmartContracts => 10903,
            Domain::Automation => 701,
            Domain::RegulatoryCompliance => 1003,
            Domain::Networking => 103,
            Domain::StreamingServices => 1306,
            Domain::GrantManagement => 1901,
            Domain::ProcessAutomation => 110,
            Domain::SustainableFarming => 1105,
            Domain::Bioinformatics => 304,
            Domain::IotDevices => 10101,
            Domain::InternetOfThings => 101,
            Domain::VoipAndUnifiedCommunications => 1605,
            Domain::MarketingAnalytics => 2405,
            Domain::MedicalTechnology => 901,
            Domain::NetworkProtocols => 10303,
            Domain::CommunicationSystems => 108,
            Domain::Telecommunication => 10801,
            Domain::WorkflowAutomation => 11002,
            Domain::InternetServices => 1601,
            Domain::Azure => 10502,
            Domain::Devops => 10202,
            Domain::IndustrialIot => 10105,
            Domain::SoftwareDevelopment => 10201,
            Domain::SportsAnalytics => 2203,
            Domain::HealthInformationSystems => 905,
            Domain::Automotive => 802,
            Domain::Publishing => 1305,
            Domain::DataSecurity => 10702,
            Domain::IotSecurity => 10102,
            Domain::UrbanPlanning => 1406,
            Domain::Ecology => 1703,
            Domain::Construction => 1401,
            Domain::FoodAndBeverage => 1502,
            Domain::AthleticTraining => 2201,
            Domain::AutonomousVehicles => 806,
            Domain::Banking => 201,
            Domain::OilAndGas => 1203,
            Domain::DisabilityServices => 2104,
            Domain::DatabaseAdministration => 10603,
            Domain::BigData => 10401,
            Domain::Security => 107,
            Domain::IotNetworks => 10103,
            Domain::NetworkManagement => 10302,
            Domain::Finance => 202,
            Domain::EnvironmentalMonitoring => 1704,
            Domain::Retail => 205,
            Domain::IncidentManagement => 10706,
            Domain::SupplyChainManagement => 703,
            Domain::ProcessEngineering => 705,
            Domain::IdentityManagement => 10705,
            Domain::SupplyChain => 804,
            Domain::IntellectualProperty => 1002,
            Domain::Defi => 10902,
            Domain::DataEngineering => 10403,
            Domain::ApisIntegration => 10204,
            Domain::Aws => 10501,
            Domain::ELearning => 601,
            Domain::Robotics => 702,
            Domain::PolicyManagement => 2305,
            Domain::SystemAdministration => 10602,
            Domain::HousingAssistance => 2105,
            Domain::OnlineSafety => 401,
            Domain::ClimateScience => 1701,
            Domain::MarketingAutomation => 2406,
            Domain::ActuarialScience => 2301,
            Domain::EnergyStorage => 1202,
            Domain::Rpa => 11001,
            Domain::NetworkOperations => 10301,
            Domain::TrainingAndDevelopment => 503,
            Domain::ProductDevelopment => 1904,
            Domain::PointOfSale => 2005,
            Domain::Cryptocurrency => 10901,
            Domain::InvestmentServices => 203,
            Domain::TelecomOperations => 1604,
            Domain::Logistics => 801,
            Domain::MentalHealthServices => 2106,
            Domain::DigitalMarketing => 2403,
            Domain::OrderFulfillment => 2004,
            Domain::Broadcasting => 1301,
            Domain::DigitalMedia => 1303,
            Domain::Gcp => 10503,
            Domain::HelpDeskSupport => 10604,
            Domain::Freight => 805,
            Domain::NetworkSecurity => 10305,
            Domain::EnvironmentalPolicy => 1705,
            Domain::Pedagogy => 605,
            Domain::SportsTechnology => 2206,
            Domain::HospitalityTechnology => 1503,
            Domain::ContractLaw => 1001,
            Domain::ResearchDataManagement => 1905,
            Domain::IotConnectivity => 1602,
            Domain::BrandManagement => 2402,
            Domain::FitnessAndWellness => 2202,
            Domain::RenewableEnergy => 1205,
            Domain::SignalProcessing => 10803,
            Domain::Litigation => 1004,
            Domain::PublicPolicy => 1806,
            Domain::LeanManufacturing => 704,
            Domain::BroadcastingSystems => 10804,
            Domain::Telemedicine => 902,
            Domain::OnlineRetail => 2003,
            Domain::HrAnalytics => 505,
            Domain::ConsumerGoods => 204,
            Domain::FacilitiesManagement => 1402,
            Domain::Proptech => 1404,
            Domain::LegalResearch => 1005,
            Domain::SportsManagement => 2204,
            Domain::SportsMedicine => 2205,
            Domain::CorporateGovernance => 1006,
            Domain::RetailAnalytics => 2006,
            Domain::SoftwareEngineering => 102,
            Domain::ChildAndFamilyServices => 2102,
            Domain::DataVisualization => 10402,
            Domain::Underwriting => 2306,
            Domain::PerformanceAnalysis => 10601,
            Domain::FraudPrevention => 403,
            Domain::ConservationBiology => 1702,
            Domain::InsuranceSales => 2303,
            Domain::CloudComputing => 105,
            Domain::EmergencyManagement => 1803,
            Domain::Genomics => 303,
            Domain::PropertyManagement => 1403,
            Domain::PublicAdministration => 1804,
            Domain::CropManagement => 1102,
            Domain::TourismManagement => 1505,
            Domain::NetworkArchitecture => 10304,
            Domain::PatientManagementSystems => 904,
            Domain::CurriculumDesign => 602,
            Domain::AgriculturalTechnology => 1101,
            Domain::PrecisionAgriculture => 1104,
            Domain::PharmaceuticalResearch => 302,
            Domain::CaseManagement => 2101,
            Domain::CustomerExperience => 2001,
            Domain::ContentModeration => 402,
            Domain::HealthcareInformatics => 903,
            Domain::ScientificResearch => 1906,
            Domain::EventPlanning => 1501,
            Domain::Sustainability => 1706,
            Domain::BaseDomain => 0,
            Domain::InnovationManagement => 1902,
            Domain::Gaming => 1304,
            Domain::RiskManagement => 405,
            Domain::InformationTechnology => 106,
            Domain::PowerGeneration => 1204,
            Domain::Mlops => 10205,
            Domain::Cybersecurity => 10701,
            Domain::Advertising => 2401,
            Domain::TravelServices => 1506,
            Domain::ApplicationSecurity => 10703,
            Domain::InventoryManagement => 2002,
            Domain::Blockchain => 109,
            Domain::CompensationAndBenefits => 504,
            Domain::SmartHomes => 10104,
            Domain::MarketResearch => 2404,
            Domain::PublicInfrastructure => 1805,
            Domain::EGovernment => 1802,
            Domain::QualityAssurance => 10203,
            Domain::EnergyManagement => 1201,
            Domain::CivicEngagement => 1801,
            Domain::NetworkInfrastructure => 1603,
            Domain::MolecularBiology => 305,
            Domain::DataScience => 104,
            Domain::Insurtech => 2304,
            Domain::CommunityOutreach => 2103,
            Domain::PublicTransit => 803,

        }
    }
    fn name(&self) -> String {
        match self {
            Domain::LearningManagementSystems => "learning_management_systems",
            Domain::WirelessCommunications => "wireless_communications",
            Domain::DataPrivacy => "data_privacy",
            Domain::HotelManagement => "hotel_management",
            Domain::ContentCreation => "content_creation",
            Domain::LaboratoryManagement => "laboratory_management",
            Domain::LivestockManagement => "livestock_management",
            Domain::EmployeeRelations => "employee_relations",
            Domain::WirelessCommunication => "wireless_communication",
            Domain::Recruitment => "recruitment",
            Domain::SmartGrids => "smart_grids",
            Domain::ClaimsProcessing => "claims_processing",
            Domain::Biotechnology => "biotechnology",
            Domain::RealEstateInvestment => "real_estate_investment",
            Domain::EducationalTechnology => "educational_technology",
            Domain::CyberNetworkSecurity => "cyber_network_security",
            Domain::SmartContracts => "smart_contracts",
            Domain::Automation => "automation",
            Domain::RegulatoryCompliance => "regulatory_compliance",
            Domain::Networking => "networking",
            Domain::StreamingServices => "streaming_services",
            Domain::GrantManagement => "grant_management",
            Domain::ProcessAutomation => "process_automation",
            Domain::SustainableFarming => "sustainable_farming",
            Domain::Bioinformatics => "bioinformatics",
            Domain::IotDevices => "iot_devices",
            Domain::InternetOfThings => "internet_of_things",
            Domain::VoipAndUnifiedCommunications => "voip_and_unified_communications",
            Domain::MarketingAnalytics => "marketing_analytics",
            Domain::MedicalTechnology => "medical_technology",
            Domain::NetworkProtocols => "network_protocols",
            Domain::CommunicationSystems => "communication_systems",
            Domain::Telecommunication => "telecommunication",
            Domain::WorkflowAutomation => "workflow_automation",
            Domain::InternetServices => "internet_services",
            Domain::Azure => "azure",
            Domain::Devops => "devops",
            Domain::IndustrialIot => "industrial_iot",
            Domain::SoftwareDevelopment => "software_development",
            Domain::SportsAnalytics => "sports_analytics",
            Domain::HealthInformationSystems => "health_information_systems",
            Domain::Automotive => "automotive",
            Domain::Publishing => "publishing",
            Domain::DataSecurity => "data_security",
            Domain::IotSecurity => "iot_security",
            Domain::UrbanPlanning => "urban_planning",
            Domain::Ecology => "ecology",
            Domain::Construction => "construction",
            Domain::FoodAndBeverage => "food_and_beverage",
            Domain::AthleticTraining => "athletic_training",
            Domain::AutonomousVehicles => "autonomous_vehicles",
            Domain::Banking => "banking",
            Domain::OilAndGas => "oil_and_gas",
            Domain::DisabilityServices => "disability_services",
            Domain::DatabaseAdministration => "database_administration",
            Domain::BigData => "big_data",
            Domain::Security => "security",
            Domain::IotNetworks => "iot_networks",
            Domain::NetworkManagement => "network_management",
            Domain::Finance => "finance",
            Domain::EnvironmentalMonitoring => "environmental_monitoring",
            Domain::Retail => "retail",
            Domain::IncidentManagement => "incident_management",
            Domain::SupplyChainManagement => "supply_chain_management",
            Domain::ProcessEngineering => "process_engineering",
            Domain::IdentityManagement => "identity_management",
            Domain::SupplyChain => "supply_chain",
            Domain::IntellectualProperty => "intellectual_property",
            Domain::Defi => "defi",
            Domain::DataEngineering => "data_engineering",
            Domain::ApisIntegration => "apis_integration",
            Domain::Aws => "aws",
            Domain::ELearning => "e_learning",
            Domain::Robotics => "robotics",
            Domain::PolicyManagement => "policy_management",
            Domain::SystemAdministration => "system_administration",
            Domain::HousingAssistance => "housing_assistance",
            Domain::OnlineSafety => "online_safety",
            Domain::ClimateScience => "climate_science",
            Domain::MarketingAutomation => "marketing_automation",
            Domain::ActuarialScience => "actuarial_science",
            Domain::EnergyStorage => "energy_storage",
            Domain::Rpa => "rpa",
            Domain::NetworkOperations => "network_operations",
            Domain::TrainingAndDevelopment => "training_and_development",
            Domain::ProductDevelopment => "product_development",
            Domain::PointOfSale => "point_of_sale",
            Domain::Cryptocurrency => "cryptocurrency",
            Domain::InvestmentServices => "investment_services",
            Domain::TelecomOperations => "telecom_operations",
            Domain::Logistics => "logistics",
            Domain::MentalHealthServices => "mental_health_services",
            Domain::DigitalMarketing => "digital_marketing",
            Domain::OrderFulfillment => "order_fulfillment",
            Domain::Broadcasting => "broadcasting",
            Domain::DigitalMedia => "digital_media",
            Domain::Gcp => "gcp",
            Domain::HelpDeskSupport => "help_desk_support",
            Domain::Freight => "freight",
            Domain::NetworkSecurity => "network_security",
            Domain::EnvironmentalPolicy => "environmental_policy",
            Domain::Pedagogy => "pedagogy",
            Domain::SportsTechnology => "sports_technology",
            Domain::HospitalityTechnology => "hospitality_technology",
            Domain::ContractLaw => "contract_law",
            Domain::ResearchDataManagement => "research_data_management",
            Domain::IotConnectivity => "iot_connectivity",
            Domain::BrandManagement => "brand_management",
            Domain::FitnessAndWellness => "fitness_and_wellness",
            Domain::RenewableEnergy => "renewable_energy",
            Domain::SignalProcessing => "signal_processing",
            Domain::Litigation => "litigation",
            Domain::PublicPolicy => "public_policy",
            Domain::LeanManufacturing => "lean_manufacturing",
            Domain::BroadcastingSystems => "broadcasting_systems",
            Domain::Telemedicine => "telemedicine",
            Domain::OnlineRetail => "online_retail",
            Domain::HrAnalytics => "hr_analytics",
            Domain::ConsumerGoods => "consumer_goods",
            Domain::FacilitiesManagement => "facilities_management",
            Domain::Proptech => "proptech",
            Domain::LegalResearch => "legal_research",
            Domain::SportsManagement => "sports_management",
            Domain::SportsMedicine => "sports_medicine",
            Domain::CorporateGovernance => "corporate_governance",
            Domain::RetailAnalytics => "retail_analytics",
            Domain::SoftwareEngineering => "software_engineering",
            Domain::ChildAndFamilyServices => "child_and_family_services",
            Domain::DataVisualization => "data_visualization",
            Domain::Underwriting => "underwriting",
            Domain::PerformanceAnalysis => "performance_analysis",
            Domain::FraudPrevention => "fraud_prevention",
            Domain::ConservationBiology => "conservation_biology",
            Domain::InsuranceSales => "insurance_sales",
            Domain::CloudComputing => "cloud_computing",
            Domain::EmergencyManagement => "emergency_management",
            Domain::Genomics => "genomics",
            Domain::PropertyManagement => "property_management",
            Domain::PublicAdministration => "public_administration",
            Domain::CropManagement => "crop_management",
            Domain::TourismManagement => "tourism_management",
            Domain::NetworkArchitecture => "network_architecture",
            Domain::PatientManagementSystems => "patient_management_systems",
            Domain::CurriculumDesign => "curriculum_design",
            Domain::AgriculturalTechnology => "agricultural_technology",
            Domain::PrecisionAgriculture => "precision_agriculture",
            Domain::PharmaceuticalResearch => "pharmaceutical_research",
            Domain::CaseManagement => "case_management",
            Domain::CustomerExperience => "customer_experience",
            Domain::ContentModeration => "content_moderation",
            Domain::HealthcareInformatics => "healthcare_informatics",
            Domain::ScientificResearch => "scientific_research",
            Domain::EventPlanning => "event_planning",
            Domain::Sustainability => "sustainability",
            Domain::BaseDomain => "base_domain",
            Domain::InnovationManagement => "innovation_management",
            Domain::Gaming => "gaming",
            Domain::RiskManagement => "risk_management",
            Domain::InformationTechnology => "information_technology",
            Domain::PowerGeneration => "power_generation",
            Domain::Mlops => "mlops",
            Domain::Cybersecurity => "cybersecurity",
            Domain::Advertising => "advertising",
            Domain::TravelServices => "travel_services",
            Domain::ApplicationSecurity => "application_security",
            Domain::InventoryManagement => "inventory_management",
            Domain::Blockchain => "blockchain",
            Domain::CompensationAndBenefits => "compensation_and_benefits",
            Domain::SmartHomes => "smart_homes",
            Domain::MarketResearch => "market_research",
            Domain::PublicInfrastructure => "public_infrastructure",
            Domain::EGovernment => "e_government",
            Domain::QualityAssurance => "quality_assurance",
            Domain::EnergyManagement => "energy_management",
            Domain::CivicEngagement => "civic_engagement",
            Domain::NetworkInfrastructure => "network_infrastructure",
            Domain::MolecularBiology => "molecular_biology",
            Domain::DataScience => "data_science",
            Domain::Insurtech => "insurtech",
            Domain::CommunityOutreach => "community_outreach",
            Domain::PublicTransit => "public_transit",

        }.to_string()
    }
}

impl From<Domain> for String {
    fn from(value: Domain) -> String {
        match value {
            Domain::LearningManagementSystems => "learning_management_systems",
            Domain::WirelessCommunications => "wireless_communications",
            Domain::DataPrivacy => "data_privacy",
            Domain::HotelManagement => "hotel_management",
            Domain::ContentCreation => "content_creation",
            Domain::LaboratoryManagement => "laboratory_management",
            Domain::LivestockManagement => "livestock_management",
            Domain::EmployeeRelations => "employee_relations",
            Domain::WirelessCommunication => "wireless_communication",
            Domain::Recruitment => "recruitment",
            Domain::SmartGrids => "smart_grids",
            Domain::ClaimsProcessing => "claims_processing",
            Domain::Biotechnology => "biotechnology",
            Domain::RealEstateInvestment => "real_estate_investment",
            Domain::EducationalTechnology => "educational_technology",
            Domain::CyberNetworkSecurity => "cyber_network_security",
            Domain::SmartContracts => "smart_contracts",
            Domain::Automation => "automation",
            Domain::RegulatoryCompliance => "regulatory_compliance",
            Domain::Networking => "networking",
            Domain::StreamingServices => "streaming_services",
            Domain::GrantManagement => "grant_management",
            Domain::ProcessAutomation => "process_automation",
            Domain::SustainableFarming => "sustainable_farming",
            Domain::Bioinformatics => "bioinformatics",
            Domain::IotDevices => "iot_devices",
            Domain::InternetOfThings => "internet_of_things",
            Domain::VoipAndUnifiedCommunications => "voip_and_unified_communications",
            Domain::MarketingAnalytics => "marketing_analytics",
            Domain::MedicalTechnology => "medical_technology",
            Domain::NetworkProtocols => "network_protocols",
            Domain::CommunicationSystems => "communication_systems",
            Domain::Telecommunication => "telecommunication",
            Domain::WorkflowAutomation => "workflow_automation",
            Domain::InternetServices => "internet_services",
            Domain::Azure => "azure",
            Domain::Devops => "devops",
            Domain::IndustrialIot => "industrial_iot",
            Domain::SoftwareDevelopment => "software_development",
            Domain::SportsAnalytics => "sports_analytics",
            Domain::HealthInformationSystems => "health_information_systems",
            Domain::Automotive => "automotive",
            Domain::Publishing => "publishing",
            Domain::DataSecurity => "data_security",
            Domain::IotSecurity => "iot_security",
            Domain::UrbanPlanning => "urban_planning",
            Domain::Ecology => "ecology",
            Domain::Construction => "construction",
            Domain::FoodAndBeverage => "food_and_beverage",
            Domain::AthleticTraining => "athletic_training",
            Domain::AutonomousVehicles => "autonomous_vehicles",
            Domain::Banking => "banking",
            Domain::OilAndGas => "oil_and_gas",
            Domain::DisabilityServices => "disability_services",
            Domain::DatabaseAdministration => "database_administration",
            Domain::BigData => "big_data",
            Domain::Security => "security",
            Domain::IotNetworks => "iot_networks",
            Domain::NetworkManagement => "network_management",
            Domain::Finance => "finance",
            Domain::EnvironmentalMonitoring => "environmental_monitoring",
            Domain::Retail => "retail",
            Domain::IncidentManagement => "incident_management",
            Domain::SupplyChainManagement => "supply_chain_management",
            Domain::ProcessEngineering => "process_engineering",
            Domain::IdentityManagement => "identity_management",
            Domain::SupplyChain => "supply_chain",
            Domain::IntellectualProperty => "intellectual_property",
            Domain::Defi => "defi",
            Domain::DataEngineering => "data_engineering",
            Domain::ApisIntegration => "apis_integration",
            Domain::Aws => "aws",
            Domain::ELearning => "e_learning",
            Domain::Robotics => "robotics",
            Domain::PolicyManagement => "policy_management",
            Domain::SystemAdministration => "system_administration",
            Domain::HousingAssistance => "housing_assistance",
            Domain::OnlineSafety => "online_safety",
            Domain::ClimateScience => "climate_science",
            Domain::MarketingAutomation => "marketing_automation",
            Domain::ActuarialScience => "actuarial_science",
            Domain::EnergyStorage => "energy_storage",
            Domain::Rpa => "rpa",
            Domain::NetworkOperations => "network_operations",
            Domain::TrainingAndDevelopment => "training_and_development",
            Domain::ProductDevelopment => "product_development",
            Domain::PointOfSale => "point_of_sale",
            Domain::Cryptocurrency => "cryptocurrency",
            Domain::InvestmentServices => "investment_services",
            Domain::TelecomOperations => "telecom_operations",
            Domain::Logistics => "logistics",
            Domain::MentalHealthServices => "mental_health_services",
            Domain::DigitalMarketing => "digital_marketing",
            Domain::OrderFulfillment => "order_fulfillment",
            Domain::Broadcasting => "broadcasting",
            Domain::DigitalMedia => "digital_media",
            Domain::Gcp => "gcp",
            Domain::HelpDeskSupport => "help_desk_support",
            Domain::Freight => "freight",
            Domain::NetworkSecurity => "network_security",
            Domain::EnvironmentalPolicy => "environmental_policy",
            Domain::Pedagogy => "pedagogy",
            Domain::SportsTechnology => "sports_technology",
            Domain::HospitalityTechnology => "hospitality_technology",
            Domain::ContractLaw => "contract_law",
            Domain::ResearchDataManagement => "research_data_management",
            Domain::IotConnectivity => "iot_connectivity",
            Domain::BrandManagement => "brand_management",
            Domain::FitnessAndWellness => "fitness_and_wellness",
            Domain::RenewableEnergy => "renewable_energy",
            Domain::SignalProcessing => "signal_processing",
            Domain::Litigation => "litigation",
            Domain::PublicPolicy => "public_policy",
            Domain::LeanManufacturing => "lean_manufacturing",
            Domain::BroadcastingSystems => "broadcasting_systems",
            Domain::Telemedicine => "telemedicine",
            Domain::OnlineRetail => "online_retail",
            Domain::HrAnalytics => "hr_analytics",
            Domain::ConsumerGoods => "consumer_goods",
            Domain::FacilitiesManagement => "facilities_management",
            Domain::Proptech => "proptech",
            Domain::LegalResearch => "legal_research",
            Domain::SportsManagement => "sports_management",
            Domain::SportsMedicine => "sports_medicine",
            Domain::CorporateGovernance => "corporate_governance",
            Domain::RetailAnalytics => "retail_analytics",
            Domain::SoftwareEngineering => "software_engineering",
            Domain::ChildAndFamilyServices => "child_and_family_services",
            Domain::DataVisualization => "data_visualization",
            Domain::Underwriting => "underwriting",
            Domain::PerformanceAnalysis => "performance_analysis",
            Domain::FraudPrevention => "fraud_prevention",
            Domain::ConservationBiology => "conservation_biology",
            Domain::InsuranceSales => "insurance_sales",
            Domain::CloudComputing => "cloud_computing",
            Domain::EmergencyManagement => "emergency_management",
            Domain::Genomics => "genomics",
            Domain::PropertyManagement => "property_management",
            Domain::PublicAdministration => "public_administration",
            Domain::CropManagement => "crop_management",
            Domain::TourismManagement => "tourism_management",
            Domain::NetworkArchitecture => "network_architecture",
            Domain::PatientManagementSystems => "patient_management_systems",
            Domain::CurriculumDesign => "curriculum_design",
            Domain::AgriculturalTechnology => "agricultural_technology",
            Domain::PrecisionAgriculture => "precision_agriculture",
            Domain::PharmaceuticalResearch => "pharmaceutical_research",
            Domain::CaseManagement => "case_management",
            Domain::CustomerExperience => "customer_experience",
            Domain::ContentModeration => "content_moderation",
            Domain::HealthcareInformatics => "healthcare_informatics",
            Domain::ScientificResearch => "scientific_research",
            Domain::EventPlanning => "event_planning",
            Domain::Sustainability => "sustainability",
            Domain::BaseDomain => "base_domain",
            Domain::InnovationManagement => "innovation_management",
            Domain::Gaming => "gaming",
            Domain::RiskManagement => "risk_management",
            Domain::InformationTechnology => "information_technology",
            Domain::PowerGeneration => "power_generation",
            Domain::Mlops => "mlops",
            Domain::Cybersecurity => "cybersecurity",
            Domain::Advertising => "advertising",
            Domain::TravelServices => "travel_services",
            Domain::ApplicationSecurity => "application_security",
            Domain::InventoryManagement => "inventory_management",
            Domain::Blockchain => "blockchain",
            Domain::CompensationAndBenefits => "compensation_and_benefits",
            Domain::SmartHomes => "smart_homes",
            Domain::MarketResearch => "market_research",
            Domain::PublicInfrastructure => "public_infrastructure",
            Domain::EGovernment => "e_government",
            Domain::QualityAssurance => "quality_assurance",
            Domain::EnergyManagement => "energy_management",
            Domain::CivicEngagement => "civic_engagement",
            Domain::NetworkInfrastructure => "network_infrastructure",
            Domain::MolecularBiology => "molecular_biology",
            Domain::DataScience => "data_science",
            Domain::Insurtech => "insurtech",
            Domain::CommunityOutreach => "community_outreach",
            Domain::PublicTransit => "public_transit",

        }.to_string()
    }
}


impl From<Domain> for u32 {
    fn from(value: Domain) -> u32 {
        match value {
            Domain::LearningManagementSystems => 603,
            Domain::WirelessCommunications => 1606,
            Domain::DataPrivacy => 404,
            Domain::HotelManagement => 1504,
            Domain::ContentCreation => 1302,
            Domain::LaboratoryManagement => 1903,
            Domain::LivestockManagement => 1103,
            Domain::EmployeeRelations => 502,
            Domain::WirelessCommunication => 10802,
            Domain::Recruitment => 501,
            Domain::SmartGrids => 1206,
            Domain::ClaimsProcessing => 2302,
            Domain::Biotechnology => 301,
            Domain::RealEstateInvestment => 1405,
            Domain::EducationalTechnology => 604,
            Domain::CyberNetworkSecurity => 10704,
            Domain::SmartContracts => 10903,
            Domain::Automation => 701,
            Domain::RegulatoryCompliance => 1003,
            Domain::Networking => 103,
            Domain::StreamingServices => 1306,
            Domain::GrantManagement => 1901,
            Domain::ProcessAutomation => 110,
            Domain::SustainableFarming => 1105,
            Domain::Bioinformatics => 304,
            Domain::IotDevices => 10101,
            Domain::InternetOfThings => 101,
            Domain::VoipAndUnifiedCommunications => 1605,
            Domain::MarketingAnalytics => 2405,
            Domain::MedicalTechnology => 901,
            Domain::NetworkProtocols => 10303,
            Domain::CommunicationSystems => 108,
            Domain::Telecommunication => 10801,
            Domain::WorkflowAutomation => 11002,
            Domain::InternetServices => 1601,
            Domain::Azure => 10502,
            Domain::Devops => 10202,
            Domain::IndustrialIot => 10105,
            Domain::SoftwareDevelopment => 10201,
            Domain::SportsAnalytics => 2203,
            Domain::HealthInformationSystems => 905,
            Domain::Automotive => 802,
            Domain::Publishing => 1305,
            Domain::DataSecurity => 10702,
            Domain::IotSecurity => 10102,
            Domain::UrbanPlanning => 1406,
            Domain::Ecology => 1703,
            Domain::Construction => 1401,
            Domain::FoodAndBeverage => 1502,
            Domain::AthleticTraining => 2201,
            Domain::AutonomousVehicles => 806,
            Domain::Banking => 201,
            Domain::OilAndGas => 1203,
            Domain::DisabilityServices => 2104,
            Domain::DatabaseAdministration => 10603,
            Domain::BigData => 10401,
            Domain::Security => 107,
            Domain::IotNetworks => 10103,
            Domain::NetworkManagement => 10302,
            Domain::Finance => 202,
            Domain::EnvironmentalMonitoring => 1704,
            Domain::Retail => 205,
            Domain::IncidentManagement => 10706,
            Domain::SupplyChainManagement => 703,
            Domain::ProcessEngineering => 705,
            Domain::IdentityManagement => 10705,
            Domain::SupplyChain => 804,
            Domain::IntellectualProperty => 1002,
            Domain::Defi => 10902,
            Domain::DataEngineering => 10403,
            Domain::ApisIntegration => 10204,
            Domain::Aws => 10501,
            Domain::ELearning => 601,
            Domain::Robotics => 702,
            Domain::PolicyManagement => 2305,
            Domain::SystemAdministration => 10602,
            Domain::HousingAssistance => 2105,
            Domain::OnlineSafety => 401,
            Domain::ClimateScience => 1701,
            Domain::MarketingAutomation => 2406,
            Domain::ActuarialScience => 2301,
            Domain::EnergyStorage => 1202,
            Domain::Rpa => 11001,
            Domain::NetworkOperations => 10301,
            Domain::TrainingAndDevelopment => 503,
            Domain::ProductDevelopment => 1904,
            Domain::PointOfSale => 2005,
            Domain::Cryptocurrency => 10901,
            Domain::InvestmentServices => 203,
            Domain::TelecomOperations => 1604,
            Domain::Logistics => 801,
            Domain::MentalHealthServices => 2106,
            Domain::DigitalMarketing => 2403,
            Domain::OrderFulfillment => 2004,
            Domain::Broadcasting => 1301,
            Domain::DigitalMedia => 1303,
            Domain::Gcp => 10503,
            Domain::HelpDeskSupport => 10604,
            Domain::Freight => 805,
            Domain::NetworkSecurity => 10305,
            Domain::EnvironmentalPolicy => 1705,
            Domain::Pedagogy => 605,
            Domain::SportsTechnology => 2206,
            Domain::HospitalityTechnology => 1503,
            Domain::ContractLaw => 1001,
            Domain::ResearchDataManagement => 1905,
            Domain::IotConnectivity => 1602,
            Domain::BrandManagement => 2402,
            Domain::FitnessAndWellness => 2202,
            Domain::RenewableEnergy => 1205,
            Domain::SignalProcessing => 10803,
            Domain::Litigation => 1004,
            Domain::PublicPolicy => 1806,
            Domain::LeanManufacturing => 704,
            Domain::BroadcastingSystems => 10804,
            Domain::Telemedicine => 902,
            Domain::OnlineRetail => 2003,
            Domain::HrAnalytics => 505,
            Domain::ConsumerGoods => 204,
            Domain::FacilitiesManagement => 1402,
            Domain::Proptech => 1404,
            Domain::LegalResearch => 1005,
            Domain::SportsManagement => 2204,
            Domain::SportsMedicine => 2205,
            Domain::CorporateGovernance => 1006,
            Domain::RetailAnalytics => 2006,
            Domain::SoftwareEngineering => 102,
            Domain::ChildAndFamilyServices => 2102,
            Domain::DataVisualization => 10402,
            Domain::Underwriting => 2306,
            Domain::PerformanceAnalysis => 10601,
            Domain::FraudPrevention => 403,
            Domain::ConservationBiology => 1702,
            Domain::InsuranceSales => 2303,
            Domain::CloudComputing => 105,
            Domain::EmergencyManagement => 1803,
            Domain::Genomics => 303,
            Domain::PropertyManagement => 1403,
            Domain::PublicAdministration => 1804,
            Domain::CropManagement => 1102,
            Domain::TourismManagement => 1505,
            Domain::NetworkArchitecture => 10304,
            Domain::PatientManagementSystems => 904,
            Domain::CurriculumDesign => 602,
            Domain::AgriculturalTechnology => 1101,
            Domain::PrecisionAgriculture => 1104,
            Domain::PharmaceuticalResearch => 302,
            Domain::CaseManagement => 2101,
            Domain::CustomerExperience => 2001,
            Domain::ContentModeration => 402,
            Domain::HealthcareInformatics => 903,
            Domain::ScientificResearch => 1906,
            Domain::EventPlanning => 1501,
            Domain::Sustainability => 1706,
            Domain::BaseDomain => 0,
            Domain::InnovationManagement => 1902,
            Domain::Gaming => 1304,
            Domain::RiskManagement => 405,
            Domain::InformationTechnology => 106,
            Domain::PowerGeneration => 1204,
            Domain::Mlops => 10205,
            Domain::Cybersecurity => 10701,
            Domain::Advertising => 2401,
            Domain::TravelServices => 1506,
            Domain::ApplicationSecurity => 10703,
            Domain::InventoryManagement => 2002,
            Domain::Blockchain => 109,
            Domain::CompensationAndBenefits => 504,
            Domain::SmartHomes => 10104,
            Domain::MarketResearch => 2404,
            Domain::PublicInfrastructure => 1805,
            Domain::EGovernment => 1802,
            Domain::QualityAssurance => 10203,
            Domain::EnergyManagement => 1201,
            Domain::CivicEngagement => 1801,
            Domain::NetworkInfrastructure => 1603,
            Domain::MolecularBiology => 305,
            Domain::DataScience => 104,
            Domain::Insurtech => 2304,
            Domain::CommunityOutreach => 2103,
            Domain::PublicTransit => 803,

        }
    }
}