use crate::presentation::http::v1::requests::domains as requests;
use crate::application::inputs::domains as inputs;

impl From<requests::Domain> for inputs::Domain {
    fn from(value: requests::Domain) -> Self {
        match value {
            requests::Domain::Automation => inputs::Domain::Automation,
            requests::Domain::Automotive => inputs::Domain::Automotive,
            requests::Domain::AutonomousVehicles => inputs::Domain::AutonomousVehicles,
            requests::Domain::Banking => inputs::Domain::Banking,
            requests::Domain::Bioinformatics => inputs::Domain::Bioinformatics,
            requests::Domain::Biotechnology => inputs::Domain::Biotechnology,
            requests::Domain::CommunicationSystems => inputs::Domain::CommunicationSystems,
            requests::Domain::CompensationAndBenefits => inputs::Domain::CompensationAndBenefits,
            requests::Domain::ConsumerGoods => inputs::Domain::ConsumerGoods,
            requests::Domain::ContentModeration => inputs::Domain::ContentModeration,
            requests::Domain::CurriculumDesign => inputs::Domain::CurriculumDesign,
            requests::Domain::DataPrivacy => inputs::Domain::DataPrivacy,
            requests::Domain::ELearning => inputs::Domain::ELearning,
            requests::Domain::Education => inputs::Domain::Education,
            requests::Domain::EducationalTechnology => inputs::Domain::EducationalTechnology,
            requests::Domain::EmployeeRelations => inputs::Domain::EmployeeRelations,
            requests::Domain::Finance => inputs::Domain::Finance,
            requests::Domain::FinanceAndBusiness => inputs::Domain::FinanceAndBusiness,
            requests::Domain::FraudPrevention => inputs::Domain::FraudPrevention,
            requests::Domain::Freight => inputs::Domain::Freight,
            requests::Domain::Genomics => inputs::Domain::Genomics,
            requests::Domain::HealthInformationSystems => inputs::Domain::HealthInformationSystems,
            requests::Domain::Healthcare => inputs::Domain::Healthcare,
            requests::Domain::HealthcareInformatics => inputs::Domain::HealthcareInformatics,
            requests::Domain::HrAnalytics => inputs::Domain::HrAnalytics,
            requests::Domain::HumanResources => inputs::Domain::HumanResources,
            requests::Domain::IndustrialManufacturing => inputs::Domain::IndustrialManufacturing,
            requests::Domain::InformationTechnology => inputs::Domain::InformationTechnology,
            requests::Domain::InternetOfThings => inputs::Domain::InternetOfThings,
            requests::Domain::InvestmentServices => inputs::Domain::InvestmentServices,
            requests::Domain::LeanManufacturing => inputs::Domain::LeanManufacturing,
            requests::Domain::LearningManagementSystems => inputs::Domain::LearningManagementSystems,
            requests::Domain::LifeScience => inputs::Domain::LifeScience,
            requests::Domain::Logistics => inputs::Domain::Logistics,
            requests::Domain::MedicalTechnology => inputs::Domain::MedicalTechnology,
            requests::Domain::MolecularBiology => inputs::Domain::MolecularBiology,
            requests::Domain::NetworkManagement => inputs::Domain::NetworkManagement,
            requests::Domain::NetworkOperations => inputs::Domain::NetworkOperations,
            requests::Domain::Networking => inputs::Domain::Networking,
            requests::Domain::OnlineSafety => inputs::Domain::OnlineSafety,
            requests::Domain::PatientManagementSystems => inputs::Domain::PatientManagementSystems,
            requests::Domain::Pedagogy => inputs::Domain::Pedagogy,
            requests::Domain::PharmaceuticalResearch => inputs::Domain::PharmaceuticalResearch,
            requests::Domain::ProcessEngineering => inputs::Domain::ProcessEngineering,
            requests::Domain::PublicTransit => inputs::Domain::PublicTransit,
            requests::Domain::Recruitment => inputs::Domain::Recruitment,
            requests::Domain::Retail => inputs::Domain::Retail,
            requests::Domain::RiskManagement => inputs::Domain::RiskManagement,
            requests::Domain::Robotics => inputs::Domain::Robotics,
            requests::Domain::Security => inputs::Domain::Security,
            requests::Domain::SoftwareEngineering => inputs::Domain::SoftwareEngineering,
            requests::Domain::SupplyChain => inputs::Domain::SupplyChain,
            requests::Domain::SupplyChainManagement => inputs::Domain::SupplyChainManagement,
            requests::Domain::Technology => inputs::Domain::Technology,
            requests::Domain::Telemedicine => inputs::Domain::Telemedicine,
            requests::Domain::TrainingAndDevelopment => inputs::Domain::TrainingAndDevelopment,
            requests::Domain::Transportation => inputs::Domain::Transportation,
            requests::Domain::TrustAndSafety => inputs::Domain::TrustAndSafety,
        }
    }
}