/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BadRequestResponse,
    BadRequestResponseFromJSON,
    BadRequestResponseToJSON,
    DeployModelWithOptionBody,
    DeployModelWithOptionBodyFromJSON,
    DeployModelWithOptionBodyToJSON,
    ListModelDeploymentsResponse,
    ListModelDeploymentsResponseFromJSON,
    ListModelDeploymentsResponseToJSON,
    ModelDeploymentResponse,
    ModelDeploymentResponseFromJSON,
    ModelDeploymentResponseToJSON,
    NotFoundResponse,
    NotFoundResponseFromJSON,
    NotFoundResponseToJSON,
    ServerErrorResponse,
    ServerErrorResponseFromJSON,
    ServerErrorResponseToJSON,
} from '../models';

export interface DeployModelWithOptionRequest {
    deployModelWithOptionBody: DeployModelWithOptionBody;
}

export interface StartModelDeploymentRequest {
    deploymentId: string;
}

export interface StopModelDeploymentRequest {
    deploymentId: string;
}

export interface UndeployModelDeploymentRequest {
    deploymentId: string;
}

/**
 * 
 */
export class DeploymentsApi extends runtime.BaseAPI {

    /**
     * Deploy an ExternalModel with a deployment option
     */
    async deployModelWithOptionRaw(requestParameters: DeployModelWithOptionRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ModelDeploymentResponse>> {
        if (requestParameters.deployModelWithOptionBody === null || requestParameters.deployModelWithOptionBody === undefined) {
            throw new runtime.RequiredError('deployModelWithOptionBody','Required parameter requestParameters.deployModelWithOptionBody was null or undefined when calling deployModelWithOption.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/deployments-api/deployments`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeployModelWithOptionBodyToJSON(requestParameters.deployModelWithOptionBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelDeploymentResponseFromJSON(jsonValue));
    }

    /**
     * Deploy an ExternalModel with a deployment option
     */
    async deployModelWithOption(requestParameters: DeployModelWithOptionRequest, initOverrides?: RequestInit): Promise<ModelDeploymentResponse> {
        const response = await this.deployModelWithOptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all available deployments
     */
    async listModelDeploymentsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListModelDeploymentsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/deployments-api/deployments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListModelDeploymentsResponseFromJSON(jsonValue));
    }

    /**
     * Lists all available deployments
     */
    async listModelDeployments(initOverrides?: RequestInit): Promise<ListModelDeploymentsResponse> {
        const response = await this.listModelDeploymentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Start a model deployment on its selected target
     */
    async startModelDeploymentRaw(requestParameters: StartModelDeploymentRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ModelDeploymentResponse>> {
        if (requestParameters.deploymentId === null || requestParameters.deploymentId === undefined) {
            throw new runtime.RequiredError('deploymentId','Required parameter requestParameters.deploymentId was null or undefined when calling startModelDeployment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/deployments-api/deployments/{deployment_id}/start`.replace(`{${"deployment_id"}}`, encodeURIComponent(String(requestParameters.deploymentId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelDeploymentResponseFromJSON(jsonValue));
    }

    /**
     * Start a model deployment on its selected target
     */
    async startModelDeployment(requestParameters: StartModelDeploymentRequest, initOverrides?: RequestInit): Promise<ModelDeploymentResponse> {
        const response = await this.startModelDeploymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop a Model Deployment
     */
    async stopModelDeploymentRaw(requestParameters: StopModelDeploymentRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ModelDeploymentResponse>> {
        if (requestParameters.deploymentId === null || requestParameters.deploymentId === undefined) {
            throw new runtime.RequiredError('deploymentId','Required parameter requestParameters.deploymentId was null or undefined when calling stopModelDeployment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/deployments-api/deployments/{deployment_id}/stop`.replace(`{${"deployment_id"}}`, encodeURIComponent(String(requestParameters.deploymentId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelDeploymentResponseFromJSON(jsonValue));
    }

    /**
     * Stop a Model Deployment
     */
    async stopModelDeployment(requestParameters: StopModelDeploymentRequest, initOverrides?: RequestInit): Promise<ModelDeploymentResponse> {
        const response = await this.stopModelDeploymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Undeploy a Model Deployment
     */
    async undeployModelDeploymentRaw(requestParameters: UndeployModelDeploymentRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ModelDeploymentResponse>> {
        if (requestParameters.deploymentId === null || requestParameters.deploymentId === undefined) {
            throw new runtime.RequiredError('deploymentId','Required parameter requestParameters.deploymentId was null or undefined when calling undeployModelDeployment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/deployments-api/deployments/{deployment_id}/undeploy`.replace(`{${"deployment_id"}}`, encodeURIComponent(String(requestParameters.deploymentId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelDeploymentResponseFromJSON(jsonValue));
    }

    /**
     * Undeploy a Model Deployment
     */
    async undeployModelDeployment(requestParameters: UndeployModelDeploymentRequest, initOverrides?: RequestInit): Promise<ModelDeploymentResponse> {
        const response = await this.undeployModelDeploymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
