/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BadRequestResponse,
    BadRequestResponseFromJSON,
    BadRequestResponseToJSON,
    ListDeploymentStrategiesResponse,
    ListDeploymentStrategiesResponseFromJSON,
    ListDeploymentStrategiesResponseToJSON,
    NotFoundResponse,
    NotFoundResponseFromJSON,
    NotFoundResponseToJSON,
    ServerErrorResponse,
    ServerErrorResponseFromJSON,
    ServerErrorResponseToJSON,
} from '../models';

/**
 * 
 */
export class StrategiesApi extends runtime.BaseAPI {

    /**
     * Lists all available deployment strategies for all platforms
     */
    async listStrategiesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListDeploymentStrategiesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/deployments-api/strategies`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListDeploymentStrategiesResponseFromJSON(jsonValue));
    }

    /**
     * Lists all available deployment strategies for all platforms
     */
    async listStrategies(initOverrides?: RequestInit): Promise<ListDeploymentStrategiesResponse> {
        const response = await this.listStrategiesRaw(initOverrides);
        return await response.value();
    }

}
