/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GetHpcClusterResponse,
    GetHpcClusterResponseFromJSON,
    GetHpcClusterResponseToJSON,
    ListHpcClustersResponse,
    ListHpcClustersResponseFromJSON,
    ListHpcClustersResponseToJSON,
} from '../models';

export interface GetHpcClusterRequest {
    dataCenter: GetHpcClusterDataCenterEnum;
    hpcClusterId: string;
}

export interface ListHpcClustersRequest {
    dataCenter: ListHpcClustersDataCenterEnum;
    limit?: number;
    cursor?: string;
    includeCount?: boolean;
}

/**
 * 
 */
export class TargetsApi extends runtime.BaseAPI {

    /**
     * Get an HPC cluster
     */
    async getHpcClusterRaw(requestParameters: GetHpcClusterRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetHpcClusterResponse>> {
        if (requestParameters.dataCenter === null || requestParameters.dataCenter === undefined) {
            throw new runtime.RequiredError('dataCenter','Required parameter requestParameters.dataCenter was null or undefined when calling getHpcCluster.');
        }

        if (requestParameters.hpcClusterId === null || requestParameters.hpcClusterId === undefined) {
            throw new runtime.RequiredError('hpcClusterId','Required parameter requestParameters.hpcClusterId was null or undefined when calling getHpcCluster.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/deployments-api/data-centers/{data_center}/hpc-clusters/{hpc_cluster_id}`.replace(`{${"data_center"}}`, encodeURIComponent(String(requestParameters.dataCenter))).replace(`{${"hpc_cluster_id"}}`, encodeURIComponent(String(requestParameters.hpcClusterId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHpcClusterResponseFromJSON(jsonValue));
    }

    /**
     * Get an HPC cluster
     */
    async getHpcCluster(requestParameters: GetHpcClusterRequest, initOverrides?: RequestInit): Promise<GetHpcClusterResponse> {
        const response = await this.getHpcClusterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List HPC clusters in a data center
     */
    async listHpcClustersRaw(requestParameters: ListHpcClustersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListHpcClustersResponse>> {
        if (requestParameters.dataCenter === null || requestParameters.dataCenter === undefined) {
            throw new runtime.RequiredError('dataCenter','Required parameter requestParameters.dataCenter was null or undefined when calling listHpcClusters.');
        }

        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.includeCount !== undefined) {
            queryParameters['include_count'] = requestParameters.includeCount;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/deployments-api/data-centers/{data_center}/hpc-clusters`.replace(`{${"data_center"}}`, encodeURIComponent(String(requestParameters.dataCenter))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListHpcClustersResponseFromJSON(jsonValue));
    }

    /**
     * List HPC clusters in a data center
     */
    async listHpcClusters(requestParameters: ListHpcClustersRequest, initOverrides?: RequestInit): Promise<ListHpcClustersResponse> {
        const response = await this.listHpcClustersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum GetHpcClusterDataCenterEnum {
    Tacc = 'Tacc'
}
/**
    * @export
    * @enum {string}
    */
export enum ListHpcClustersDataCenterEnum {
    Tacc = 'Tacc'
}
