use crate::presentation::http::v1::requests::domains as dtos;
use crate::domain::entities::domain as entities;

impl From<entities::Domain> for dtos::Domain {
    fn from(value: entities::Domain) -> Self {
        match value {
            entities::Domain::Automation => dtos::Domain::Automation,
            entities::Domain::Automotive => dtos::Domain::Automotive,
            entities::Domain::AutonomousVehicles => dtos::Domain::AutonomousVehicles,
            entities::Domain::Banking => dtos::Domain::Banking,
            entities::Domain::Bioinformatics => dtos::Domain::Bioinformatics,
            entities::Domain::Biotechnology => dtos::Domain::Biotechnology,
            entities::Domain::CommunicationSystems => dtos::Domain::CommunicationSystems,
            entities::Domain::CompensationAndBenefits => dtos::Domain::CompensationAndBenefits,
            entities::Domain::ConsumerGoods => dtos::Domain::ConsumerGoods,
            entities::Domain::ContentModeration => dtos::Domain::ContentModeration,
            entities::Domain::CurriculumDesign => dtos::Domain::CurriculumDesign,
            entities::Domain::DataPrivacy => dtos::Domain::DataPrivacy,
            entities::Domain::ELearning => dtos::Domain::ELearning,
            entities::Domain::Education => dtos::Domain::Education,
            entities::Domain::EducationalTechnology => dtos::Domain::EducationalTechnology,
            entities::Domain::EmployeeRelations => dtos::Domain::EmployeeRelations,
            entities::Domain::Finance => dtos::Domain::Finance,
            entities::Domain::FinanceAndBusiness => dtos::Domain::FinanceAndBusiness,
            entities::Domain::FraudPrevention => dtos::Domain::FraudPrevention,
            entities::Domain::Freight => dtos::Domain::Freight,
            entities::Domain::Genomics => dtos::Domain::Genomics,
            entities::Domain::HealthInformationSystems => dtos::Domain::HealthInformationSystems,
            entities::Domain::Healthcare => dtos::Domain::Healthcare,
            entities::Domain::HealthcareInformatics => dtos::Domain::HealthcareInformatics,
            entities::Domain::HrAnalytics => dtos::Domain::HrAnalytics,
            entities::Domain::HumanResources => dtos::Domain::HumanResources,
            entities::Domain::IndustrialManufacturing => dtos::Domain::IndustrialManufacturing,
            entities::Domain::InformationTechnology => dtos::Domain::InformationTechnology,
            entities::Domain::InternetOfThings => dtos::Domain::InternetOfThings,
            entities::Domain::InvestmentServices => dtos::Domain::InvestmentServices,
            entities::Domain::LeanManufacturing => dtos::Domain::LeanManufacturing,
            entities::Domain::LearningManagementSystems => dtos::Domain::LearningManagementSystems,
            entities::Domain::LifeScience => dtos::Domain::LifeScience,
            entities::Domain::Logistics => dtos::Domain::Logistics,
            entities::Domain::MedicalTechnology => dtos::Domain::MedicalTechnology,
            entities::Domain::MolecularBiology => dtos::Domain::MolecularBiology,
            entities::Domain::NetworkManagement => dtos::Domain::NetworkManagement,
            entities::Domain::NetworkOperations => dtos::Domain::NetworkOperations,
            entities::Domain::Networking => dtos::Domain::Networking,
            entities::Domain::OnlineSafety => dtos::Domain::OnlineSafety,
            entities::Domain::PatientManagementSystems => dtos::Domain::PatientManagementSystems,
            entities::Domain::Pedagogy => dtos::Domain::Pedagogy,
            entities::Domain::PharmaceuticalResearch => dtos::Domain::PharmaceuticalResearch,
            entities::Domain::ProcessEngineering => dtos::Domain::ProcessEngineering,
            entities::Domain::PublicTransit => dtos::Domain::PublicTransit,
            entities::Domain::Recruitment => dtos::Domain::Recruitment,
            entities::Domain::Retail => dtos::Domain::Retail,
            entities::Domain::RiskManagement => dtos::Domain::RiskManagement,
            entities::Domain::Robotics => dtos::Domain::Robotics,
            entities::Domain::Security => dtos::Domain::Security,
            entities::Domain::SoftwareEngineering => dtos::Domain::SoftwareEngineering,
            entities::Domain::SupplyChain => dtos::Domain::SupplyChain,
            entities::Domain::SupplyChainManagement => dtos::Domain::SupplyChainManagement,
            entities::Domain::Technology => dtos::Domain::Technology,
            entities::Domain::Telemedicine => dtos::Domain::Telemedicine,
            entities::Domain::TrainingAndDevelopment => dtos::Domain::TrainingAndDevelopment,
            entities::Domain::Transportation => dtos::Domain::Transportation,
            entities::Domain::TrustAndSafety => dtos::Domain::TrustAndSafety,
        }
    }
}