# Stage 1: Compile the code
FROM rust:1.91.1 AS builder

ARG SERVICE_NAME
ARG SERVICE_DIR
ARG LIBS_DIR
ARG SDKS_DIR

# Create 
RUN mkdir -p /usr/local/mlhub/${SERVICE_NAME} /usr/local/mlhub/libs /usr/local/mlhub/sdks

# Copy shared libraries code
WORKDIR /usr/local/mlhub/libs
COPY ${LIBS_DIR} .

WORKDIR /usr/local/mlhub/sdks
COPY ${SDKS_DIR} .

# Copy service code
WORKDIR /usr/local/mlhub/${SERVICE_NAME}
COPY ${SERVICE_DIR} .

# Install
RUN cargo install --path .

# Stage 2: Copy the binary to a slim Linux image
FROM debian:bookworm-slim

ARG SERVICE_NAME

COPY --from=builder /usr/local/mlhub/${SERVICE_NAME}/target/release/${SERVICE_NAME} /usr/local/bin/mlhub

ENV RUST_LOG=debug,shared=debug

CMD ["mlhub"]