use crate::application::inputs::task as inputs;
use crate::domain::entities::task as entities;

impl From<inputs::Task> for entities::Task {
    fn from(value: inputs::Task) -> Self {
        match value {
            inputs::Task::AnyToAny => entities::Task::AnyToAny,
            inputs::Task::AutomaticSpeechRecognition => entities::Task::AutomaticSpeechRecognition,
            inputs::Task::AudioToAudio => entities::Task::AudioToAudio,
            inputs::Task::AudioClassification => entities::Task::AudioClassification,
            inputs::Task::AudioTextToText => entities::Task::AudioTextToText,
            inputs::Task::DepthEstimation => entities::Task::DepthEstimation,
            inputs::Task::DocumentQuestionAnswering => entities::Task::DocumentQuestionAnswering,
            inputs::Task::FeatureExtraction => entities::Task::FeatureExtraction,
            inputs::Task::FillMask => entities::Task::FillMask,
            inputs::Task::ImageFeatureExtraction => entities::Task::ImageFeatureExtraction,
            inputs::Task::ImageTextToText => entities::Task::ImageTextToText,
            inputs::Task::ImageToVideo => entities::Task::ImageToVideo,
            inputs::Task::ImageSegmentation => entities::Task::ImageSegmentation,
            inputs::Task::ImageClassification => entities::Task::ImageClassification,
            inputs::Task::ImageTo3d => entities::Task::ImageTo3d,
            inputs::Task::ImageToImage => entities::Task::ImageToImage,
            inputs::Task::ImageToText => entities::Task::ImageToText,
            inputs::Task::KeypointDetection => entities::Task::KeypointDetection,
            inputs::Task::MaskGeneration => entities::Task::MaskGeneration,
            inputs::Task::ObjectDetection => entities::Task::ObjectDetection,
            inputs::Task::QuestionAnswering => entities::Task::QuestionAnswering,
            inputs::Task::ReinforcementLearning => entities::Task::ReinforcementLearning,
            inputs::Task::SentenceSimilarity => entities::Task::SentenceSimilarity,
            inputs::Task::Summarization => entities::Task::Summarization,
            inputs::Task::TableQuestionAnswering => entities::Task::TableQuestionAnswering,
            inputs::Task::TextGeneration => entities::Task::TextGeneration,
            inputs::Task::TextRanking => entities::Task::TextRanking,
            inputs::Task::TabularClassification => entities::Task::TabularClassification,
            inputs::Task::TextTo3d => entities::Task::TextTo3d,
            inputs::Task::TextClassification => entities::Task::TextClassification,
            inputs::Task::TextToImage => entities::Task::TextToImage,
            inputs::Task::Translation => entities::Task::Translation,
            inputs::Task::TabularRegression => entities::Task::TabularRegression,
            inputs::Task::TextToSpeech => entities::Task::TextToSpeech,
            inputs::Task::TextToVideo => entities::Task::TextToVideo,
            inputs::Task::TokenClassification => entities::Task::TokenClassification,
            inputs::Task::UnconditionalImageGeneration => entities::Task::UnconditionalImageGeneration,
            inputs::Task::VideoClassification => entities::Task::VideoClassification,
            inputs::Task::VideoTextToText => entities::Task::VideoTextToText,
            inputs::Task::VideoToVideo => entities::Task::VideoToVideo,
            inputs::Task::VisualQuestionAnswering => entities::Task::VisualQuestionAnswering,
            inputs::Task::VisualDocumentRetrieval => entities::Task::VisualDocumentRetrieval,
            inputs::Task::ZeroShotClassification => entities::Task::ZeroShotClassification,
            inputs::Task::ZeroShotImageClassification => entities::Task::ZeroShotClassification,
            inputs::Task::ZeroShotObjectDetection => entities::Task::ZeroShotObjectDetection,
        }
    }
}