use utoipa::OpenApi;
use crate::config::VERSION;

// Here we are import the helper function generated by utoipa to generate docs for
// handlers
use super::handlers::list_strategies::__path_list_strategies;

#[derive(OpenApi)]
#[openapi(
    paths(
        list_strategies
    ),
    components(
        schemas(
            
        )
    ),
    info(title = "MLHub Deployments API", version=VERSION)
)]
pub struct ApiDoc;