use utoipa::OpenApi;
use crate::config::VERSION;

// Here we are import the helper function generated by utoipa to generate docs for
// handlers
use super::handlers::list_strategies::__path_list_strategies;
use super::handlers::deploy_model_with_strategy::__path_deploy_model_with_strategy;

#[derive(OpenApi)]
#[openapi(
    paths(
        list_strategies,
        deploy_model_with_strategy,
    ),
    components(
        schemas(
            
        )
    ),
    info(title = "MLHub Deployments API", version=VERSION)
)]
pub struct ApiDoc;