use crate::domain::external::agntcy::domain as agntcy;
use crate::domain::entities::domains as entities;

impl From<agntcy::Domain> for entities::Domain {
    fn from(value: agntcy::Domain) -> Self {
        match value {
            agntcy::Domain::Automation => entities::Domain::Automation,
            agntcy::Domain::Automotive => entities::Domain::Automotive,
            agntcy::Domain::AutonomousVehicles => entities::Domain::AutonomousVehicles,
            agntcy::Domain::Banking => entities::Domain::Banking,
            agntcy::Domain::Bioinformatics => entities::Domain::Bioinformatics,
            agntcy::Domain::Biotechnology => entities::Domain::Biotechnology,
            agntcy::Domain::CommunicationSystems => entities::Domain::CommunicationSystems,
            agntcy::Domain::CompensationAndBenefits => entities::Domain::CompensationAndBenefits,
            agntcy::Domain::ConsumerGoods => entities::Domain::ConsumerGoods,
            agntcy::Domain::ContentModeration => entities::Domain::ContentModeration,
            agntcy::Domain::CurriculumDesign => entities::Domain::CurriculumDesign,
            agntcy::Domain::DataPrivacy => entities::Domain::DataPrivacy,
            agntcy::Domain::ELearning => entities::Domain::ELearning,
            agntcy::Domain::Education => entities::Domain::Education,
            agntcy::Domain::EducationalTechnology => entities::Domain::EducationalTechnology,
            agntcy::Domain::EmployeeRelations => entities::Domain::EmployeeRelations,
            agntcy::Domain::Finance => entities::Domain::Finance,
            agntcy::Domain::FinanceAndBusiness => entities::Domain::FinanceAndBusiness,
            agntcy::Domain::FraudPrevention => entities::Domain::FraudPrevention,
            agntcy::Domain::Freight => entities::Domain::Freight,
            agntcy::Domain::Genomics => entities::Domain::Genomics,
            agntcy::Domain::HealthInformationSystems => entities::Domain::HealthInformationSystems,
            agntcy::Domain::Healthcare => entities::Domain::Healthcare,
            agntcy::Domain::HealthcareInformatics => entities::Domain::HealthcareInformatics,
            agntcy::Domain::HrAnalytics => entities::Domain::HrAnalytics,
            agntcy::Domain::HumanResources => entities::Domain::HumanResources,
            agntcy::Domain::IndustrialManufacturing => entities::Domain::IndustrialManufacturing,
            agntcy::Domain::InformationTechnology => entities::Domain::InformationTechnology,
            agntcy::Domain::InternetOfThings => entities::Domain::InternetOfThings,
            agntcy::Domain::InvestmentServices => entities::Domain::InvestmentServices,
            agntcy::Domain::LeanManufacturing => entities::Domain::LeanManufacturing,
            agntcy::Domain::LearningManagementSystems => entities::Domain::LearningManagementSystems,
            agntcy::Domain::LifeScience => entities::Domain::LifeScience,
            agntcy::Domain::Logistics => entities::Domain::Logistics,
            agntcy::Domain::MedicalTechnology => entities::Domain::MedicalTechnology,
            agntcy::Domain::MolecularBiology => entities::Domain::MolecularBiology,
            agntcy::Domain::NetworkManagement => entities::Domain::NetworkManagement,
            agntcy::Domain::NetworkOperations => entities::Domain::NetworkOperations,
            agntcy::Domain::Networking => entities::Domain::Networking,
            agntcy::Domain::OnlineSafety => entities::Domain::OnlineSafety,
            agntcy::Domain::PatientManagementSystems => entities::Domain::PatientManagementSystems,
            agntcy::Domain::Pedagogy => entities::Domain::Pedagogy,
            agntcy::Domain::PharmaceuticalResearch => entities::Domain::PharmaceuticalResearch,
            agntcy::Domain::ProcessEngineering => entities::Domain::ProcessEngineering,
            agntcy::Domain::PublicTransit => entities::Domain::PublicTransit,
            agntcy::Domain::Recruitment => entities::Domain::Recruitment,
            agntcy::Domain::Retail => entities::Domain::Retail,
            agntcy::Domain::RiskManagement => entities::Domain::RiskManagement,
            agntcy::Domain::Robotics => entities::Domain::Robotics,
            agntcy::Domain::Security => entities::Domain::Security,
            agntcy::Domain::SoftwareEngineering => entities::Domain::SoftwareEngineering,
            agntcy::Domain::SupplyChain => entities::Domain::SupplyChain,
            agntcy::Domain::SupplyChainManagement => entities::Domain::SupplyChainManagement,
            agntcy::Domain::Technology => entities::Domain::Technology,
            agntcy::Domain::Telemedicine => entities::Domain::Telemedicine,
            agntcy::Domain::TrainingAndDevelopment => entities::Domain::TrainingAndDevelopment,
            agntcy::Domain::Transportation => entities::Domain::Transportation,
            agntcy::Domain::TrustAndSafety => entities::Domain::TrustAndSafety,
        }
    }
}