#!/usr/bin/env bash

set -e

rm -f Cargo.toml

# Clean the previously generated libraries
rm -rf ./models

cargo ws init

src=$2
if [ -z "$2" ]; then
    src=./specs/spec.yaml
fi

destination=$3
if [ -z "$3" ]; then
    destination=./specs/transformed-spec.yaml
fi

python3 scripts/transform.py $src $destination

libninja gen --output-dir ./gen/models MLHubModels $destination

cargo ws create --lib --name models --edition 2021 models

mv gen/models/src/* models/src

cat template.Cargo.toml >> models/Cargo.toml

cargo add strum_macros@=0.27.2 -p models

cargo ws version patch --allow-branch "*" --no-global-tag

