# Stage 1: Compile the code
# Digest refers to rust:1.93.1-trixie
FROM rust@sha256:80302520b7199f0504975bca59a914015e9fee088f759875dbbc238ca9509ee1 AS builder

ARG SERVICE_NAME

# Set workspace root
WORKDIR /usr/local/mlhub

# Copy EVERYTHING so Cargo sees workspace root
COPY . .

# Build using workspace resolution
RUN cargo build --release -p ${SERVICE_NAME} --locked

# Stage 2: Runtime image
FROM debian:trixie-slim

ARG SERVICE_NAME

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libssl3 ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder \
    /usr/local/mlhub/target/release/${SERVICE_NAME} \
    /usr/local/bin/mlhub

RUN apt-get update && rm -rf /var/lib/apt/lists/*
RUN apt update
RUN apt install libssl3
RUN apt-get install -y --no-install-recommends ca-certificates git git-lfs
RUN update-ca-certificates

ENV RUST_LOG=debug,shared=debug

CMD ["mlhub"]