/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AcceleratorType {
    Gpu = 'Gpu'
}

export function AcceleratorTypeFromJSON(json: any): AcceleratorType {
    return AcceleratorTypeFromJSONTyped(json, false);
}

export function AcceleratorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceleratorType {
    return json as AcceleratorType;
}

export function AcceleratorTypeToJSON(value?: AcceleratorType | null): any {
    return value as any;
}

