/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Argument
 */
export interface Argument {
    /**
     * 
     * @type {string}
     * @memberof Argument
     */
    parameter_name: string;
    /**
     * 
     * @type {string}
     * @memberof Argument
     */
    value: string;
}

export function ArgumentFromJSON(json: any): Argument {
    return ArgumentFromJSONTyped(json, false);
}

export function ArgumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Argument {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parameter_name': json['parameter_name'],
        'value': json['value'],
    };
}

export function ArgumentToJSON(value?: Argument | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parameter_name': value.parameter_name,
        'value': value.value,
    };
}

