/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BillingPolicy,
    BillingPolicyFromJSON,
    BillingPolicyFromJSONTyped,
    BillingPolicyToJSON,
    HardwareProfile,
    HardwareProfileFromJSON,
    HardwareProfileFromJSONTyped,
    HardwareProfileToJSON,
    SchedulerType,
    SchedulerTypeFromJSON,
    SchedulerTypeFromJSONTyped,
    SchedulerTypeToJSON,
    SchedulingPolicy,
    SchedulingPolicyFromJSON,
    SchedulingPolicyFromJSONTyped,
    SchedulingPolicyToJSON,
} from './';

/**
 * 
 * @export
 * @interface BatchSchedulerQueue
 */
export interface BatchSchedulerQueue {
    /**
     * 
     * @type {BillingPolicy}
     * @memberof BatchSchedulerQueue
     */
    billing_policy?: BillingPolicy;
    /**
     * 
     * @type {string}
     * @memberof BatchSchedulerQueue
     */
    cluster_id: string;
    /**
     * 
     * @type {HardwareProfile}
     * @memberof BatchSchedulerQueue
     */
    hardware_profile: HardwareProfile;
    /**
     * 
     * @type {string}
     * @memberof BatchSchedulerQueue
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BatchSchedulerQueue
     */
    name: string;
    /**
     * 
     * @type {SchedulerType}
     * @memberof BatchSchedulerQueue
     */
    scheduler_type: SchedulerType;
    /**
     * 
     * @type {SchedulingPolicy}
     * @memberof BatchSchedulerQueue
     */
    scheduling_policy: SchedulingPolicy;
}

export function BatchSchedulerQueueFromJSON(json: any): BatchSchedulerQueue {
    return BatchSchedulerQueueFromJSONTyped(json, false);
}

export function BatchSchedulerQueueFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchSchedulerQueue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'billing_policy': !exists(json, 'billing_policy') ? undefined : BillingPolicyFromJSON(json['billing_policy']),
        'cluster_id': json['cluster_id'],
        'hardware_profile': HardwareProfileFromJSON(json['hardware_profile']),
        'id': json['id'],
        'name': json['name'],
        'scheduler_type': SchedulerTypeFromJSON(json['scheduler_type']),
        'scheduling_policy': SchedulingPolicyFromJSON(json['scheduling_policy']),
    };
}

export function BatchSchedulerQueueToJSON(value?: BatchSchedulerQueue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'billing_policy': BillingPolicyToJSON(value.billing_policy),
        'cluster_id': value.cluster_id,
        'hardware_profile': HardwareProfileToJSON(value.hardware_profile),
        'id': value.id,
        'name': value.name,
        'scheduler_type': SchedulerTypeToJSON(value.scheduler_type),
        'scheduling_policy': SchedulingPolicyToJSON(value.scheduling_policy),
    };
}

