/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BillingMetric {
    PerNodeHour = 'PerNodeHour',
    PerGpuHour = 'PerGpuHour',
    PerCoreHour = 'PerCoreHour'
}

export function BillingMetricFromJSON(json: any): BillingMetric {
    return BillingMetricFromJSONTyped(json, false);
}

export function BillingMetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingMetric {
    return json as BillingMetric;
}

export function BillingMetricToJSON(value?: BillingMetric | null): any {
    return value as any;
}

