/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BillingMetric,
    BillingMetricFromJSON,
    BillingMetricFromJSONTyped,
    BillingMetricToJSON,
} from './';

/**
 * 
 * @export
 * @interface BillingPolicy
 */
export interface BillingPolicy {
    /**
     * 
     * @type {BillingMetric}
     * @memberof BillingPolicy
     */
    metric: BillingMetric;
    /**
     * 
     * @type {number}
     * @memberof BillingPolicy
     */
    queue_multiplier: number;
}

export function BillingPolicyFromJSON(json: any): BillingPolicy {
    return BillingPolicyFromJSONTyped(json, false);
}

export function BillingPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingPolicy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metric': BillingMetricFromJSON(json['metric']),
        'queue_multiplier': json['queue_multiplier'],
    };
}

export function BillingPolicyToJSON(value?: BillingPolicy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metric': BillingMetricToJSON(value.metric),
        'queue_multiplier': value.queue_multiplier,
    };
}

