/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ContainerRuntime {
    Apptainer = 'Apptainer',
    SingularityCe = 'SingularityCe',
    Enroot = 'Enroot',
    Charliecloud = 'Charliecloud',
    Shifter = 'Shifter',
    Sarus = 'Sarus',
    Podman = 'Podman',
    Docker = 'Docker'
}

export function ContainerRuntimeFromJSON(json: any): ContainerRuntime {
    return ContainerRuntimeFromJSONTyped(json, false);
}

export function ContainerRuntimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerRuntime {
    return json as ContainerRuntime;
}

export function ContainerRuntimeToJSON(value?: ContainerRuntime | null): any {
    return value as any;
}

