/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DataCenter {
    Tacc = 'Tacc'
}

export function DataCenterFromJSON(json: any): DataCenter {
    return DataCenterFromJSONTyped(json, false);
}

export function DataCenterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataCenter {
    return json as DataCenter;
}

export function DataCenterToJSON(value?: DataCenter | null): any {
    return value as any;
}

