/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Argument,
    ArgumentFromJSON,
    ArgumentFromJSONTyped,
    ArgumentToJSON,
    DeploymentModality,
    DeploymentModalityFromJSON,
    DeploymentModalityFromJSONTyped,
    DeploymentModalityToJSON,
    ParallelismStrategy,
    ParallelismStrategyFromJSON,
    ParallelismStrategyFromJSONTyped,
    ParallelismStrategyToJSON,
    Scope,
    ScopeFromJSON,
    ScopeFromJSONTyped,
    ScopeToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeployModelWithStrategyBody
 */
export interface DeployModelWithStrategyBody {
    /**
     * 
     * @type {Array<Argument>}
     * @memberof DeployModelWithStrategyBody
     */
    arguments?: Array<Argument> | null;
    /**
     * 
     * @type {DeploymentModality}
     * @memberof DeployModelWithStrategyBody
     */
    deployment_modality: DeploymentModality;
    /**
     * 
     * @type {string}
     * @memberof DeployModelWithStrategyBody
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeployModelWithStrategyBody
     */
    model_author: string;
    /**
     * 
     * @type {string}
     * @memberof DeployModelWithStrategyBody
     */
    model_name: string;
    /**
     * 
     * @type {string}
     * @memberof DeployModelWithStrategyBody
     */
    name: string;
    /**
     * 
     * @type {Array<ParallelismStrategy>}
     * @memberof DeployModelWithStrategyBody
     */
    parallelism_strategies?: Array<ParallelismStrategy> | null;
    /**
     * 
     * @type {number}
     * @memberof DeployModelWithStrategyBody
     */
    replicas?: number | null;
    /**
     * Selector for global vs tenant-scoped models
     * @type {Scope}
     * @memberof DeployModelWithStrategyBody
     */
    scope?: Scope | null;
}

export function DeployModelWithStrategyBodyFromJSON(json: any): DeployModelWithStrategyBody {
    return DeployModelWithStrategyBodyFromJSONTyped(json, false);
}

export function DeployModelWithStrategyBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployModelWithStrategyBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'arguments': !exists(json, 'arguments') ? undefined : (json['arguments'] === null ? null : (json['arguments'] as Array<any>).map(ArgumentFromJSON)),
        'deployment_modality': DeploymentModalityFromJSON(json['deployment_modality']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'model_author': json['model_author'],
        'model_name': json['model_name'],
        'name': json['name'],
        'parallelism_strategies': !exists(json, 'parallelism_strategies') ? undefined : (json['parallelism_strategies'] === null ? null : (json['parallelism_strategies'] as Array<any>).map(ParallelismStrategyFromJSON)),
        'replicas': !exists(json, 'replicas') ? undefined : json['replicas'],
        'scope': !exists(json, 'scope') ? undefined : ScopeFromJSON(json['scope']),
    };
}

export function DeployModelWithStrategyBodyToJSON(value?: DeployModelWithStrategyBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'arguments': value.arguments === undefined ? undefined : (value.arguments === null ? null : (value.arguments as Array<any>).map(ArgumentToJSON)),
        'deployment_modality': DeploymentModalityToJSON(value.deployment_modality),
        'description': value.description,
        'model_author': value.model_author,
        'model_name': value.model_name,
        'name': value.name,
        'parallelism_strategies': value.parallelism_strategies === undefined ? undefined : (value.parallelism_strategies === null ? null : (value.parallelism_strategies as Array<any>).map(ParallelismStrategyToJSON)),
        'replicas': value.replicas,
        'scope': ScopeToJSON(value.scope),
    };
}

