/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DeploymentModality {
    Batch = 'Batch',
    Service = 'Service'
}

export function DeploymentModalityFromJSON(json: any): DeploymentModality {
    return DeploymentModalityFromJSONTyped(json, false);
}

export function DeploymentModalityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentModality {
    return json as DeploymentModality;
}

export function DeploymentModalityToJSON(value?: DeploymentModality | null): any {
    return value as any;
}

