/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Argument,
    ArgumentFromJSON,
    ArgumentFromJSONTyped,
    ArgumentToJSON,
    DeploymentModality,
    DeploymentModalityFromJSON,
    DeploymentModalityFromJSONTyped,
    DeploymentModalityToJSON,
    ParallelismStrategy,
    ParallelismStrategyFromJSON,
    ParallelismStrategyFromJSONTyped,
    ParallelismStrategyToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeployModelWithOptionBody
 */
export interface DeployModelWithOptionBody {
    /**
     * 
     * @type {Array<Argument>}
     * @memberof DeployModelWithOptionBody
     */
    arguments?: Array<Argument> | null;
    /**
     * 
     * @type {DeploymentModality}
     * @memberof DeployModelWithOptionBody
     */
    deployment_modality: DeploymentModality;
    /**
     * 
     * @type {string}
     * @memberof DeployModelWithOptionBody
     */
    deployment_option_id: string;
    /**
     * 
     * @type {string}
     * @memberof DeployModelWithOptionBody
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeployModelWithOptionBody
     */
    name: string;
    /**
     * 
     * @type {Array<ParallelismStrategy>}
     * @memberof DeployModelWithOptionBody
     */
    parallelism_strategies?: Array<ParallelismStrategy> | null;
    /**
     * 
     * @type {number}
     * @memberof DeployModelWithOptionBody
     */
    replicas?: number | null;
}

export function DeployModelWithOptionBodyFromJSON(json: any): DeployModelWithOptionBody {
    return DeployModelWithOptionBodyFromJSONTyped(json, false);
}

export function DeployModelWithOptionBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployModelWithOptionBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'arguments': !exists(json, 'arguments') ? undefined : (json['arguments'] === null ? null : (json['arguments'] as Array<any>).map(ArgumentFromJSON)),
        'deployment_modality': DeploymentModalityFromJSON(json['deployment_modality']),
        'deployment_option_id': json['deployment_option_id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        'parallelism_strategies': !exists(json, 'parallelism_strategies') ? undefined : (json['parallelism_strategies'] === null ? null : (json['parallelism_strategies'] as Array<any>).map(ParallelismStrategyFromJSON)),
        'replicas': !exists(json, 'replicas') ? undefined : json['replicas'],
    };
}

export function DeployModelWithOptionBodyToJSON(value?: DeployModelWithOptionBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'arguments': value.arguments === undefined ? undefined : (value.arguments === null ? null : (value.arguments as Array<any>).map(ArgumentToJSON)),
        'deployment_modality': DeploymentModalityToJSON(value.deployment_modality),
        'deployment_option_id': value.deployment_option_id,
        'description': value.description,
        'name': value.name,
        'parallelism_strategies': value.parallelism_strategies === undefined ? undefined : (value.parallelism_strategies === null ? null : (value.parallelism_strategies as Array<any>).map(ParallelismStrategyToJSON)),
        'replicas': value.replicas,
    };
}

