/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    HpcCluster,
    HpcClusterFromJSON,
    HpcClusterFromJSONTyped,
    HpcClusterToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetHpcClusterResponse
 */
export interface GetHpcClusterResponse {
    /**
     * 
     * @type {string}
     * @memberof GetHpcClusterResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof GetHpcClusterResponse
     */
    metadata: object;
    /**
     * 
     * @type {HpcCluster}
     * @memberof GetHpcClusterResponse
     */
    result: HpcCluster;
    /**
     * 
     * @type {number}
     * @memberof GetHpcClusterResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof GetHpcClusterResponse
     */
    version: string;
}

export function GetHpcClusterResponseFromJSON(json: any): GetHpcClusterResponse {
    return GetHpcClusterResponseFromJSONTyped(json, false);
}

export function GetHpcClusterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHpcClusterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': HpcClusterFromJSON(json['result']),
        'status': json['status'],
        'version': json['version'],
    };
}

export function GetHpcClusterResponseToJSON(value?: GetHpcClusterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': HpcClusterToJSON(value.result),
        'status': value.status,
        'version': value.version,
    };
}

