/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GpuProfile
 */
export interface GpuProfile {
    /**
     * 
     * @type {number}
     * @memberof GpuProfile
     */
    count_per_node: number;
    /**
     * 
     * @type {number}
     * @memberof GpuProfile
     */
    gpu_memory_gb: number;
    /**
     * 
     * @type {string}
     * @memberof GpuProfile
     */
    gpu_model: string;
    /**
     * 
     * @type {string}
     * @memberof GpuProfile
     */
    gpu_vendor: string;
    /**
     * 
     * @type {boolean}
     * @memberof GpuProfile
     */
    unified_memory: boolean;
}

export function GpuProfileFromJSON(json: any): GpuProfile {
    return GpuProfileFromJSONTyped(json, false);
}

export function GpuProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): GpuProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count_per_node': json['count_per_node'],
        'gpu_memory_gb': json['gpu_memory_gb'],
        'gpu_model': json['gpu_model'],
        'gpu_vendor': json['gpu_vendor'],
        'unified_memory': json['unified_memory'],
    };
}

export function GpuProfileToJSON(value?: GpuProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count_per_node': value.count_per_node,
        'gpu_memory_gb': value.gpu_memory_gb,
        'gpu_model': value.gpu_model,
        'gpu_vendor': value.gpu_vendor,
        'unified_memory': value.unified_memory,
    };
}

