/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AcceleratorType,
    AcceleratorTypeFromJSON,
    AcceleratorTypeFromJSONTyped,
    AcceleratorTypeToJSON,
    GpuProfile,
    GpuProfileFromJSON,
    GpuProfileFromJSONTyped,
    GpuProfileToJSON,
} from './';

/**
 * 
 * @export
 * @interface HardwareProfile
 */
export interface HardwareProfile {
    /**
     * 
     * @type {AcceleratorType}
     * @memberof HardwareProfile
     */
    accelerator_type: AcceleratorType;
    /**
     * 
     * @type {string}
     * @memberof HardwareProfile
     */
    cpu_architecture: string;
    /**
     * 
     * @type {number}
     * @memberof HardwareProfile
     */
    cpu_cores_per_node: number;
    /**
     * 
     * @type {string}
     * @memberof HardwareProfile
     */
    cpu_model: string;
    /**
     * 
     * @type {string}
     * @memberof HardwareProfile
     */
    cpu_vendor: string;
    /**
     * 
     * @type {GpuProfile}
     * @memberof HardwareProfile
     */
    gpu: GpuProfile;
    /**
     * 
     * @type {number}
     * @memberof HardwareProfile
     */
    memory_gb: number;
    /**
     * 
     * @type {number}
     * @memberof HardwareProfile
     */
    total_nodes: number;
}

export function HardwareProfileFromJSON(json: any): HardwareProfile {
    return HardwareProfileFromJSONTyped(json, false);
}

export function HardwareProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): HardwareProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accelerator_type': AcceleratorTypeFromJSON(json['accelerator_type']),
        'cpu_architecture': json['cpu_architecture'],
        'cpu_cores_per_node': json['cpu_cores_per_node'],
        'cpu_model': json['cpu_model'],
        'cpu_vendor': json['cpu_vendor'],
        'gpu': GpuProfileFromJSON(json['gpu']),
        'memory_gb': json['memory_gb'],
        'total_nodes': json['total_nodes'],
    };
}

export function HardwareProfileToJSON(value?: HardwareProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accelerator_type': AcceleratorTypeToJSON(value.accelerator_type),
        'cpu_architecture': value.cpu_architecture,
        'cpu_cores_per_node': value.cpu_cores_per_node,
        'cpu_model': value.cpu_model,
        'cpu_vendor': value.cpu_vendor,
        'gpu': GpuProfileToJSON(value.gpu),
        'memory_gb': value.memory_gb,
        'total_nodes': value.total_nodes,
    };
}

