/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DataCenter,
    DataCenterFromJSON,
    DataCenterFromJSONTyped,
    DataCenterToJSON,
} from './';

/**
 * 
 * @export
 * @interface HpcClusterSummary
 */
export interface HpcClusterSummary {
    /**
     * 
     * @type {DataCenter}
     * @memberof HpcClusterSummary
     */
    data_center: DataCenter;
    /**
     * 
     * @type {boolean}
     * @memberof HpcClusterSummary
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof HpcClusterSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HpcClusterSummary
     */
    name: string;
}

export function HpcClusterSummaryFromJSON(json: any): HpcClusterSummary {
    return HpcClusterSummaryFromJSONTyped(json, false);
}

export function HpcClusterSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): HpcClusterSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data_center': DataCenterFromJSON(json['data_center']),
        'enabled': json['enabled'],
        'id': json['id'],
        'name': json['name'],
    };
}

export function HpcClusterSummaryToJSON(value?: HpcClusterSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data_center': DataCenterToJSON(value.data_center),
        'enabled': value.enabled,
        'id': value.id,
        'name': value.name,
    };
}

