/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BatchSchedulerQueue,
    BatchSchedulerQueueFromJSON,
    BatchSchedulerQueueFromJSONTyped,
    BatchSchedulerQueueToJSON,
    DataCenter,
    DataCenterFromJSON,
    DataCenterFromJSONTyped,
    DataCenterToJSON,
} from './';

/**
 * 
 * @export
 * @interface HpcCluster
 */
export interface HpcCluster {
    /**
     * 
     * @type {DataCenter}
     * @memberof HpcCluster
     */
    data_center: DataCenter;
    /**
     * 
     * @type {string}
     * @memberof HpcCluster
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HpcCluster
     */
    documentation_url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HpcCluster
     */
    host: string;
    /**
     * 
     * @type {string}
     * @memberof HpcCluster
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HpcCluster
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof HpcCluster
     */
    port: number;
    /**
     * 
     * @type {Array<BatchSchedulerQueue>}
     * @memberof HpcCluster
     */
    queues: Array<BatchSchedulerQueue>;
}

export function HpcClusterFromJSON(json: any): HpcCluster {
    return HpcClusterFromJSONTyped(json, false);
}

export function HpcClusterFromJSONTyped(json: any, ignoreDiscriminator: boolean): HpcCluster {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data_center': DataCenterFromJSON(json['data_center']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'documentation_url': !exists(json, 'documentation_url') ? undefined : json['documentation_url'],
        'host': json['host'],
        'id': json['id'],
        'name': json['name'],
        'port': json['port'],
        'queues': ((json['queues'] as Array<any>).map(BatchSchedulerQueueFromJSON)),
    };
}

export function HpcClusterToJSON(value?: HpcCluster | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data_center': DataCenterToJSON(value.data_center),
        'description': value.description,
        'documentation_url': value.documentation_url,
        'host': value.host,
        'id': value.id,
        'name': value.name,
        'port': value.port,
        'queues': ((value.queues as Array<any>).map(BatchSchedulerQueueToJSON)),
    };
}

