/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelDeployment,
    ModelDeploymentFromJSON,
    ModelDeploymentFromJSONTyped,
    ModelDeploymentToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListModelDeploymentsResponse
 */
export interface ListModelDeploymentsResponse {
    /**
     * 
     * @type {string}
     * @memberof ListModelDeploymentsResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ListModelDeploymentsResponse
     */
    metadata: object;
    /**
     * 
     * @type {Array<ModelDeployment>}
     * @memberof ListModelDeploymentsResponse
     */
    result: Array<ModelDeployment>;
    /**
     * 
     * @type {number}
     * @memberof ListModelDeploymentsResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListModelDeploymentsResponse
     */
    version: string;
}

export function ListModelDeploymentsResponseFromJSON(json: any): ListModelDeploymentsResponse {
    return ListModelDeploymentsResponseFromJSONTyped(json, false);
}

export function ListModelDeploymentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListModelDeploymentsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ((json['result'] as Array<any>).map(ModelDeploymentFromJSON)),
        'status': json['status'],
        'version': json['version'],
    };
}

export function ListModelDeploymentsResponseToJSON(value?: ListModelDeploymentsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ((value.result as Array<any>).map(ModelDeploymentToJSON)),
        'status': value.status,
        'version': value.version,
    };
}

