/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    HpcClusterSummary,
    HpcClusterSummaryFromJSON,
    HpcClusterSummaryFromJSONTyped,
    HpcClusterSummaryToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListHpcClustersResponse
 */
export interface ListHpcClustersResponse {
    /**
     * 
     * @type {string}
     * @memberof ListHpcClustersResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ListHpcClustersResponse
     */
    metadata: object;
    /**
     * 
     * @type {Array<HpcClusterSummary>}
     * @memberof ListHpcClustersResponse
     */
    result: Array<HpcClusterSummary>;
    /**
     * 
     * @type {number}
     * @memberof ListHpcClustersResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListHpcClustersResponse
     */
    version: string;
}

export function ListHpcClustersResponseFromJSON(json: any): ListHpcClustersResponse {
    return ListHpcClustersResponseFromJSONTyped(json, false);
}

export function ListHpcClustersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListHpcClustersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ((json['result'] as Array<any>).map(HpcClusterSummaryFromJSON)),
        'status': json['status'],
        'version': json['version'],
    };
}

export function ListHpcClustersResponseToJSON(value?: ListHpcClustersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ((value.result as Array<any>).map(HpcClusterSummaryToJSON)),
        'status': value.status,
        'version': value.version,
    };
}

