/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Strategy,
    StrategyFromJSON,
    StrategyFromJSONTyped,
    StrategyToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListDeploymentStrategiesResponse
 */
export interface ListDeploymentStrategiesResponse {
    /**
     * 
     * @type {string}
     * @memberof ListDeploymentStrategiesResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ListDeploymentStrategiesResponse
     */
    metadata: object;
    /**
     * 
     * @type {Array<Strategy>}
     * @memberof ListDeploymentStrategiesResponse
     */
    result: Array<Strategy>;
    /**
     * 
     * @type {number}
     * @memberof ListDeploymentStrategiesResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListDeploymentStrategiesResponse
     */
    version: string;
}

export function ListDeploymentStrategiesResponseFromJSON(json: any): ListDeploymentStrategiesResponse {
    return ListDeploymentStrategiesResponseFromJSONTyped(json, false);
}

export function ListDeploymentStrategiesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDeploymentStrategiesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ((json['result'] as Array<any>).map(StrategyFromJSON)),
        'status': json['status'],
        'version': json['version'],
    };
}

export function ListDeploymentStrategiesResponseToJSON(value?: ListDeploymentStrategiesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ((value.result as Array<any>).map(StrategyToJSON)),
        'status': value.status,
        'version': value.version,
    };
}

