/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ModelDeploymentInterfaceOneOf,
    ModelDeploymentInterfaceOneOfFromJSONTyped,
    ModelDeploymentInterfaceOneOfToJSON,
} from './';

/**
 * @type ModelDeploymentInterface
 * 
 * @export
 */
export type ModelDeploymentInterface = ModelDeploymentInterfaceOneOf;

export function ModelDeploymentInterfaceFromJSON(json: any): ModelDeploymentInterface {
    return ModelDeploymentInterfaceFromJSONTyped(json, false);
}

export function ModelDeploymentInterfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDeploymentInterface {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ModelDeploymentInterfaceOneOfFromJSONTyped(json, true) };
}

export function ModelDeploymentInterfaceToJSON(value?: ModelDeploymentInterface | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...ModelDeploymentInterfaceOneOfToJSON(value) };
}

