/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ModelDeploymentInterfaceType {
    RestApi = 'RestApi'
}

export function ModelDeploymentInterfaceTypeFromJSON(json: any): ModelDeploymentInterfaceType {
    return ModelDeploymentInterfaceTypeFromJSONTyped(json, false);
}

export function ModelDeploymentInterfaceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDeploymentInterfaceType {
    return json as ModelDeploymentInterfaceType;
}

export function ModelDeploymentInterfaceTypeToJSON(value?: ModelDeploymentInterfaceType | null): any {
    return value as any;
}

