/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ModelDeploymentInterfaceType,
    ModelDeploymentInterfaceTypeFromJSON,
    ModelDeploymentInterfaceTypeFromJSONTyped,
    ModelDeploymentInterfaceTypeToJSON,
    RestApi,
    RestApiFromJSON,
    RestApiFromJSONTyped,
    RestApiToJSON,
} from './';

/**
 * 
 * @export
 * @interface ModelDeploymentInterface
 */
export interface ModelDeploymentInterface {
    /**
     * 
     * @type {ModelDeploymentInterfaceType}
     * @memberof ModelDeploymentInterface
     */
    interface_type: ModelDeploymentInterfaceType;
    /**
     * 
     * @type {RestApi}
     * @memberof ModelDeploymentInterface
     */
    rest_api?: RestApi;
}

export function ModelDeploymentInterfaceFromJSON(json: any): ModelDeploymentInterface {
    return ModelDeploymentInterfaceFromJSONTyped(json, false);
}

export function ModelDeploymentInterfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDeploymentInterface {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'interface_type': ModelDeploymentInterfaceTypeFromJSON(json['interface_type']),
        'rest_api': !exists(json, 'rest_api') ? undefined : RestApiFromJSON(json['rest_api']),
    };
}

export function ModelDeploymentInterfaceToJSON(value?: ModelDeploymentInterface | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'interface_type': ModelDeploymentInterfaceTypeToJSON(value.interface_type),
        'rest_api': RestApiToJSON(value.rest_api),
    };
}

