/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelReference
 */
export interface ModelReference {
    /**
     * 
     * @type {string}
     * @memberof ModelReference
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof ModelReference
     */
    name: string;
}

export function ModelReferenceFromJSON(json: any): ModelReference {
    return ModelReferenceFromJSONTyped(json, false);
}

export function ModelReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': json['author'],
        'name': json['name'],
    };
}

export function ModelReferenceToJSON(value?: ModelReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'name': value.name,
    };
}

