/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RestApi,
    RestApiFromJSON,
    RestApiFromJSONTyped,
    RestApiToJSON,
} from './';

/**
 * 
 * @export
 * @interface ModelDeploymentInterfaceOneOf
 */
export interface ModelDeploymentInterfaceOneOf {
    /**
     * 
     * @type {RestApi}
     * @memberof ModelDeploymentInterfaceOneOf
     */
    RestApi: RestApi;
}

export function ModelDeploymentInterfaceOneOfFromJSON(json: any): ModelDeploymentInterfaceOneOf {
    return ModelDeploymentInterfaceOneOfFromJSONTyped(json, false);
}

export function ModelDeploymentInterfaceOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDeploymentInterfaceOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RestApi': RestApiFromJSON(json['RestApi']),
    };
}

export function ModelDeploymentInterfaceOneOfToJSON(value?: ModelDeploymentInterfaceOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RestApi': RestApiToJSON(value.RestApi),
    };
}

