/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeploymentModality,
    DeploymentModalityFromJSON,
    DeploymentModalityFromJSONTyped,
    DeploymentModalityToJSON,
    DesiredState,
    DesiredStateFromJSON,
    DesiredStateFromJSONTyped,
    DesiredStateToJSON,
    ModelDeploymentInterface,
    ModelDeploymentInterfaceFromJSON,
    ModelDeploymentInterfaceFromJSONTyped,
    ModelDeploymentInterfaceToJSON,
    ReplicaGroup,
    ReplicaGroupFromJSON,
    ReplicaGroupFromJSONTyped,
    ReplicaGroupToJSON,
    State,
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
    Visibility,
    VisibilityFromJSON,
    VisibilityFromJSONTyped,
    VisibilityToJSON,
} from './';

/**
 * 
 * @export
 * @interface ModelDeployment
 */
export interface ModelDeployment {
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    created_at: string;
    /**
     * 
     * @type {ModelDeploymentInterface}
     * @memberof ModelDeployment
     */
    deployment_interface?: ModelDeploymentInterface;
    /**
     * 
     * @type {DeploymentModality}
     * @memberof ModelDeployment
     */
    deployment_modality: DeploymentModality;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    deployment_option_id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    description?: string | null;
    /**
     * 
     * @type {DesiredState}
     * @memberof ModelDeployment
     */
    desired_state: DesiredState;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    external_model_id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    last_desired_state_change: string;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    last_message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    last_modified: string;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    last_state_change: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ModelDeployment
     */
    metadata?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    owner: string;
    /**
     * 
     * @type {ReplicaGroup}
     * @memberof ModelDeployment
     */
    replicas: ReplicaGroup;
    /**
     * 
     * @type {number}
     * @memberof ModelDeployment
     */
    revision: number;
    /**
     * 
     * @type {State}
     * @memberof ModelDeployment
     */
    state: State;
    /**
     * 
     * @type {string}
     * @memberof ModelDeployment
     */
    tenant_id: string;
    /**
     * 
     * @type {Visibility}
     * @memberof ModelDeployment
     */
    visibility: Visibility;
}

export function ModelDeploymentFromJSON(json: any): ModelDeployment {
    return ModelDeploymentFromJSONTyped(json, false);
}

export function ModelDeploymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDeployment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'created_at': json['created_at'],
        'deployment_interface': !exists(json, 'deployment_interface') ? undefined : ModelDeploymentInterfaceFromJSON(json['deployment_interface']),
        'deployment_modality': DeploymentModalityFromJSON(json['deployment_modality']),
        'deployment_option_id': json['deployment_option_id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'desired_state': DesiredStateFromJSON(json['desired_state']),
        'external_model_id': json['external_model_id'],
        'id': json['id'],
        'last_desired_state_change': json['last_desired_state_change'],
        'last_message': !exists(json, 'last_message') ? undefined : json['last_message'],
        'last_modified': json['last_modified'],
        'last_state_change': json['last_state_change'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'name': json['name'],
        'owner': json['owner'],
        'replicas': ReplicaGroupFromJSON(json['replicas']),
        'revision': json['revision'],
        'state': StateFromJSON(json['state']),
        'tenant_id': json['tenant_id'],
        'visibility': VisibilityFromJSON(json['visibility']),
    };
}

export function ModelDeploymentToJSON(value?: ModelDeployment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.created_at,
        'deployment_interface': ModelDeploymentInterfaceToJSON(value.deployment_interface),
        'deployment_modality': DeploymentModalityToJSON(value.deployment_modality),
        'deployment_option_id': value.deployment_option_id,
        'description': value.description,
        'desired_state': DesiredStateToJSON(value.desired_state),
        'external_model_id': value.external_model_id,
        'id': value.id,
        'last_desired_state_change': value.last_desired_state_change,
        'last_message': value.last_message,
        'last_modified': value.last_modified,
        'last_state_change': value.last_state_change,
        'metadata': value.metadata,
        'name': value.name,
        'owner': value.owner,
        'replicas': ReplicaGroupToJSON(value.replicas),
        'revision': value.revision,
        'state': StateToJSON(value.state),
        'tenant_id': value.tenant_id,
        'visibility': VisibilityToJSON(value.visibility),
    };
}

