/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchedulingPolicy
 */
export interface SchedulingPolicy {
    /**
     * 
     * @type {number}
     * @memberof SchedulingPolicy
     */
    max_job_submission: number;
    /**
     * 
     * @type {number}
     * @memberof SchedulingPolicy
     */
    max_jobs_per_user: number;
    /**
     * 
     * @type {number}
     * @memberof SchedulingPolicy
     */
    max_nodes_per_job: number;
    /**
     * 
     * @type {number}
     * @memberof SchedulingPolicy
     */
    max_nodes_per_user: number;
    /**
     * 
     * @type {number}
     * @memberof SchedulingPolicy
     */
    max_wall_time_per_job_hr: number;
    /**
     * 
     * @type {number}
     * @memberof SchedulingPolicy
     */
    min_nodes_per_job: number;
}

export function SchedulingPolicyFromJSON(json: any): SchedulingPolicy {
    return SchedulingPolicyFromJSONTyped(json, false);
}

export function SchedulingPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchedulingPolicy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'max_job_submission': json['max_job_submission'],
        'max_jobs_per_user': json['max_jobs_per_user'],
        'max_nodes_per_job': json['max_nodes_per_job'],
        'max_nodes_per_user': json['max_nodes_per_user'],
        'max_wall_time_per_job_hr': json['max_wall_time_per_job_hr'],
        'min_nodes_per_job': json['min_nodes_per_job'],
    };
}

export function SchedulingPolicyToJSON(value?: SchedulingPolicy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'max_job_submission': value.max_job_submission,
        'max_jobs_per_user': value.max_jobs_per_user,
        'max_nodes_per_job': value.max_nodes_per_job,
        'max_nodes_per_user': value.max_nodes_per_user,
        'max_wall_time_per_job_hr': value.max_wall_time_per_job_hr,
        'min_nodes_per_job': value.min_nodes_per_job,
    };
}

