/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SchedulerType {
    Slurm = 'Slurm'
}

export function SchedulerTypeFromJSON(json: any): SchedulerType {
    return SchedulerTypeFromJSONTyped(json, false);
}

export function SchedulerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchedulerType {
    return json as SchedulerType;
}

export function SchedulerTypeToJSON(value?: SchedulerType | null): any {
    return value as any;
}

