/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerErrorResponse
 */
export interface ServerErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ServerErrorResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ServerErrorResponse
     */
    metadata: object;
    /**
     * 
     * @type {any}
     * @memberof ServerErrorResponse
     */
    result: any | null;
    /**
     * 
     * @type {number}
     * @memberof ServerErrorResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ServerErrorResponse
     */
    version: string;
}

export function ServerErrorResponseFromJSON(json: any): ServerErrorResponse {
    return ServerErrorResponseFromJSONTyped(json, false);
}

export function ServerErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': json['result'],
        'status': json['status'],
        'version': json['version'],
    };
}

export function ServerErrorResponseToJSON(value?: ServerErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': value.result,
        'status': value.status,
        'version': value.version,
    };
}

