/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Parameter,
    ParameterFromJSON,
    ParameterFromJSONTyped,
    ParameterToJSON,
    Platform,
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
    StrategyConfig,
    StrategyConfigFromJSON,
    StrategyConfigFromJSONTyped,
    StrategyConfigToJSON,
} from './';

/**
 * 
 * @export
 * @interface Strategy
 */
export interface Strategy {
    /**
     * 
     * @type {StrategyConfig}
     * @memberof Strategy
     */
    config: StrategyConfig;
    /**
     * 
     * @type {string}
     * @memberof Strategy
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Strategy
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof Strategy
     */
    name: string;
    /**
     * 
     * @type {Array<Parameter>}
     * @memberof Strategy
     */
    parameters: Array<Parameter>;
    /**
     * 
     * @type {Platform}
     * @memberof Strategy
     */
    platform: Platform;
}

export function StrategyFromJSON(json: any): Strategy {
    return StrategyFromJSONTyped(json, false);
}

export function StrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Strategy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': StrategyConfigFromJSON(json['config']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'enabled': json['enabled'],
        'name': json['name'],
        'parameters': ((json['parameters'] as Array<any>).map(ParameterFromJSON)),
        'platform': PlatformFromJSON(json['platform']),
    };
}

export function StrategyToJSON(value?: Strategy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': StrategyConfigToJSON(value.config),
        'description': value.description,
        'enabled': value.enabled,
        'name': value.name,
        'parameters': ((value.parameters as Array<any>).map(ParameterToJSON)),
        'platform': PlatformToJSON(value.platform),
    };
}

