/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Deployments API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeploymentModality,
    DeploymentModalityFromJSON,
    DeploymentModalityFromJSONTyped,
    DeploymentModalityToJSON,
    ParallelismStrategy,
    ParallelismStrategyFromJSON,
    ParallelismStrategyFromJSONTyped,
    ParallelismStrategyToJSON,
} from './';

/**
 * 
 * @export
 * @interface StrategyConfig
 */
export interface StrategyConfig {
    /**
     * 
     * @type {number}
     * @memberof StrategyConfig
     */
    max_replicas?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StrategyConfig
     */
    max_ttl?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StrategyConfig
     */
    min_replicas: number;
    /**
     * 
     * @type {Array<DeploymentModality>}
     * @memberof StrategyConfig
     */
    supported_deployment_modalities: Array<DeploymentModality>;
    /**
     * 
     * @type {Array<ParallelismStrategy>}
     * @memberof StrategyConfig
     */
    supported_paralellism_strategies: Array<ParallelismStrategy>;
}

export function StrategyConfigFromJSON(json: any): StrategyConfig {
    return StrategyConfigFromJSONTyped(json, false);
}

export function StrategyConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrategyConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'max_replicas': !exists(json, 'max_replicas') ? undefined : json['max_replicas'],
        'max_ttl': !exists(json, 'max_ttl') ? undefined : json['max_ttl'],
        'min_replicas': json['min_replicas'],
        'supported_deployment_modalities': ((json['supported_deployment_modalities'] as Array<any>).map(DeploymentModalityFromJSON)),
        'supported_paralellism_strategies': ((json['supported_paralellism_strategies'] as Array<any>).map(ParallelismStrategyFromJSON)),
    };
}

export function StrategyConfigToJSON(value?: StrategyConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'max_replicas': value.max_replicas,
        'max_ttl': value.max_ttl,
        'min_replicas': value.min_replicas,
        'supported_deployment_modalities': ((value.supported_deployment_modalities as Array<any>).map(DeploymentModalityToJSON)),
        'supported_paralellism_strategies': ((value.supported_paralellism_strategies as Array<any>).map(ParallelismStrategyToJSON)),
    };
}

