use crate::application::inputs::task as inputs;
use crate::domain::entities::task as entities;

impl From<entities::Task> for inputs::Task {
    fn from(value: entities::Task) -> Self {
        match value {
            entities::Task::AnyToAny => inputs::Task::AnyToAny,
            entities::Task::AutomaticSpeechRecognition => inputs::Task::AutomaticSpeechRecognition,
            entities::Task::AudioToAudio => inputs::Task::AudioToAudio,
            entities::Task::AudioClassification => inputs::Task::AudioClassification,
            entities::Task::AudioTextToText => inputs::Task::AudioTextToText,
            entities::Task::DepthEstimation => inputs::Task::DepthEstimation,
            entities::Task::DocumentQuestionAnswering => inputs::Task::DocumentQuestionAnswering,
            entities::Task::FeatureExtraction => inputs::Task::FeatureExtraction,
            entities::Task::FillMask => inputs::Task::FillMask,
            entities::Task::ImageFeatureExtraction => inputs::Task::ImageFeatureExtraction,
            entities::Task::ImageTextToText => inputs::Task::ImageTextToText,
            entities::Task::ImageToVideo => inputs::Task::ImageToVideo,
            entities::Task::ImageSegmentation => inputs::Task::ImageSegmentation,
            entities::Task::ImageClassification => inputs::Task::ImageClassification,
            entities::Task::ImageTo3d => inputs::Task::ImageTo3d,
            entities::Task::ImageToImage => inputs::Task::ImageToImage,
            entities::Task::ImageToText => inputs::Task::ImageToText,
            entities::Task::KeypointDetection => inputs::Task::KeypointDetection,
            entities::Task::MaskGeneration => inputs::Task::MaskGeneration,
            entities::Task::ObjectDetection => inputs::Task::ObjectDetection,
            entities::Task::QuestionAnswering => inputs::Task::QuestionAnswering,
            entities::Task::ReinforcementLearning => inputs::Task::ReinforcementLearning,
            entities::Task::SentenceSimilarity => inputs::Task::SentenceSimilarity,
            entities::Task::Summarization => inputs::Task::Summarization,
            entities::Task::TableQuestionAnswering => inputs::Task::TableQuestionAnswering,
            entities::Task::TextGeneration => inputs::Task::TextGeneration,
            entities::Task::TextRanking => inputs::Task::TextRanking,
            entities::Task::TabularClassification => inputs::Task::TabularClassification,
            entities::Task::TextTo3d => inputs::Task::TextTo3d,
            entities::Task::TextClassification => inputs::Task::TextClassification,
            entities::Task::TextToImage => inputs::Task::TextToImage,
            entities::Task::Translation => inputs::Task::Translation,
            entities::Task::TabularRegression => inputs::Task::TabularRegression,
            entities::Task::TextToSpeech => inputs::Task::TextToSpeech,
            entities::Task::TextToVideo => inputs::Task::TextToVideo,
            entities::Task::TokenClassification => inputs::Task::TokenClassification,
            entities::Task::UnconditionalImageGeneration => inputs::Task::UnconditionalImageGeneration,
            entities::Task::VideoClassification => inputs::Task::VideoClassification,
            entities::Task::VideoTextToText => inputs::Task::VideoTextToText,
            entities::Task::VideoToVideo => inputs::Task::VideoToVideo,
            entities::Task::VisualQuestionAnswering => inputs::Task::VisualQuestionAnswering,
            entities::Task::VisualDocumentRetrieval => inputs::Task::VisualDocumentRetrieval,
            entities::Task::ZeroShotClassification => inputs::Task::ZeroShotClassification,
            entities::Task::ZeroShotImageClassification => inputs::Task::ZeroShotClassification,
            entities::Task::ZeroShotObjectDetection => inputs::Task::ZeroShotObjectDetection,
        }
    }
}