#!/usr/bin/env bash

set -e

here=$(dirname "${BASH_SOURCE[0]}")

# Get the current version of the OASF API
version=$(curl -X 'GET' 'https://schema.oasf.outshift.com/api/version' -H 'accept: application/json' -s | jq -r '.version')

echo "OASF API v$version"

specsDir=$here/specs/v$version
latestSpecsDir=$here/specs/latest

# Create the specs dir for this version of the API and the latest.
mkdir -p $specsDir
mkdir -p $latestSpecsDir

# This array determines which APIs get called to fetch the schema
taxa=("domains" "skills" "modules")

# Fetch OASF Domains, Skills, and Modules and pretty-print them into the specs dir
for taxon in "${taxa[@]}"; do
    echo "Fetching $taxon"
    output=$(curl -X 'GET' "https://schema.oasf.outshift.com/api/main_${taxon}" -H 'accept: application/json' -s)
    echo $output | jq . > $specsDir/$taxon.json
    echo $output | jq . > $latestSpecsDir/$taxon.json
done

genDir=$here/gen/v$version
templatesDir=$here/templates

# Create the gen dir for this version of the API
mkdir -p $genDir

for taxon in "${taxa[@]}"; do
    python3 $here/scripts/v$version/generate.py $here/specs/v$version/$taxon.json $genDir $templatesDir
done

