use crate::infra::persistence::mongo::documents::task as documents;
use crate::domain::entities::task as entities;

impl From<documents::Task> for entities::Task {
    fn from(value: documents::Task) -> Self {
        match value {
            documents::Task::AnyToAny => entities::Task::AnyToAny,
            documents::Task::AutomaticSpeechRecognition => entities::Task::AutomaticSpeechRecognition,
            documents::Task::AudioToAudio => entities::Task::AudioToAudio,
            documents::Task::AudioClassification => entities::Task::AudioClassification,
            documents::Task::AudioTextToText => entities::Task::AudioTextToText,
            documents::Task::DepthEstimation => entities::Task::DepthEstimation,
            documents::Task::DocumentQuestionAnswering => entities::Task::DocumentQuestionAnswering,
            documents::Task::FeatureExtraction => entities::Task::FeatureExtraction,
            documents::Task::FillMask => entities::Task::FillMask,
            documents::Task::ImageFeatureExtraction => entities::Task::ImageFeatureExtraction,
            documents::Task::ImageTextToText => entities::Task::ImageTextToText,
            documents::Task::ImageToVideo => entities::Task::ImageToVideo,
            documents::Task::ImageSegmentation => entities::Task::ImageSegmentation,
            documents::Task::ImageClassification => entities::Task::ImageClassification,
            documents::Task::ImageTo3d => entities::Task::ImageTo3d,
            documents::Task::ImageToImage => entities::Task::ImageToImage,
            documents::Task::ImageToText => entities::Task::ImageToText,
            documents::Task::KeypointDetection => entities::Task::KeypointDetection,
            documents::Task::MaskGeneration => entities::Task::MaskGeneration,
            documents::Task::ObjectDetection => entities::Task::ObjectDetection,
            documents::Task::QuestionAnswering => entities::Task::QuestionAnswering,
            documents::Task::ReinforcementLearning => entities::Task::ReinforcementLearning,
            documents::Task::SentenceSimilarity => entities::Task::SentenceSimilarity,
            documents::Task::Summarization => entities::Task::Summarization,
            documents::Task::TableQuestionAnswering => entities::Task::TableQuestionAnswering,
            documents::Task::TextGeneration => entities::Task::TextGeneration,
            documents::Task::TextRanking => entities::Task::TextRanking,
            documents::Task::TabularClassification => entities::Task::TabularClassification,
            documents::Task::TextTo3d => entities::Task::TextTo3d,
            documents::Task::TextClassification => entities::Task::TextClassification,
            documents::Task::TextToImage => entities::Task::TextToImage,
            documents::Task::Translation => entities::Task::Translation,
            documents::Task::TabularRegression => entities::Task::TabularRegression,
            documents::Task::TextToSpeech => entities::Task::TextToSpeech,
            documents::Task::TextToVideo => entities::Task::TextToVideo,
            documents::Task::TokenClassification => entities::Task::TokenClassification,
            documents::Task::UnconditionalImageGeneration => entities::Task::UnconditionalImageGeneration,
            documents::Task::VideoClassification => entities::Task::VideoClassification,
            documents::Task::VideoTextToText => entities::Task::VideoTextToText,
            documents::Task::VideoToVideo => entities::Task::VideoToVideo,
            documents::Task::VisualQuestionAnswering => entities::Task::VisualQuestionAnswering,
            documents::Task::VisualDocumentRetrieval => entities::Task::VisualDocumentRetrieval,
            documents::Task::ZeroShotClassification => entities::Task::ZeroShotClassification,
            documents::Task::ZeroShotImageClassification => entities::Task::ZeroShotClassification,
            documents::Task::ZeroShotObjectDetection => entities::Task::ZeroShotObjectDetection,
        }
    }
}