use crate::infra::persistence::mongo::documents::task as documents;
use crate::shared_kernel::enums::Task;

impl From<documents::Task> for Task {
    fn from(value: documents::Task) -> Self {
        match value {
            documents::Task::AnyToAny => Task::AnyToAny,
            documents::Task::AutomaticSpeechRecognition => Task::AutomaticSpeechRecognition,
            documents::Task::AudioToAudio => Task::AudioToAudio,
            documents::Task::AudioClassification => Task::AudioClassification,
            documents::Task::AudioTextToText => Task::AudioTextToText,
            documents::Task::DepthEstimation => Task::DepthEstimation,
            documents::Task::DocumentQuestionAnswering => Task::DocumentQuestionAnswering,
            documents::Task::FeatureExtraction => Task::FeatureExtraction,
            documents::Task::FillMask => Task::FillMask,
            documents::Task::ImageFeatureExtraction => Task::ImageFeatureExtraction,
            documents::Task::ImageTextToText => Task::ImageTextToText,
            documents::Task::ImageToVideo => Task::ImageToVideo,
            documents::Task::ImageSegmentation => Task::ImageSegmentation,
            documents::Task::ImageClassification => Task::ImageClassification,
            documents::Task::ImageTo3d => Task::ImageTo3d,
            documents::Task::ImageToImage => Task::ImageToImage,
            documents::Task::ImageToText => Task::ImageToText,
            documents::Task::KeypointDetection => Task::KeypointDetection,
            documents::Task::MaskGeneration => Task::MaskGeneration,
            documents::Task::ObjectDetection => Task::ObjectDetection,
            documents::Task::QuestionAnswering => Task::QuestionAnswering,
            documents::Task::ReinforcementLearning => Task::ReinforcementLearning,
            documents::Task::SentenceSimilarity => Task::SentenceSimilarity,
            documents::Task::Summarization => Task::Summarization,
            documents::Task::TableQuestionAnswering => Task::TableQuestionAnswering,
            documents::Task::TextGeneration => Task::TextGeneration,
            documents::Task::TextRanking => Task::TextRanking,
            documents::Task::TabularClassification => Task::TabularClassification,
            documents::Task::TextTo3d => Task::TextTo3d,
            documents::Task::TextClassification => Task::TextClassification,
            documents::Task::TextToImage => Task::TextToImage,
            documents::Task::Translation => Task::Translation,
            documents::Task::TabularRegression => Task::TabularRegression,
            documents::Task::TextToSpeech => Task::TextToSpeech,
            documents::Task::TextToVideo => Task::TextToVideo,
            documents::Task::TokenClassification => Task::TokenClassification,
            documents::Task::UnconditionalImageGeneration => Task::UnconditionalImageGeneration,
            documents::Task::VideoClassification => Task::VideoClassification,
            documents::Task::VideoTextToText => Task::VideoTextToText,
            documents::Task::VideoToVideo => Task::VideoToVideo,
            documents::Task::VisualQuestionAnswering => Task::VisualQuestionAnswering,
            documents::Task::VisualDocumentRetrieval => Task::VisualDocumentRetrieval,
            documents::Task::ZeroShotClassification => Task::ZeroShotClassification,
            documents::Task::ZeroShotImageClassification => Task::ZeroShotClassification,
            documents::Task::ZeroShotObjectDetection => Task::ZeroShotObjectDetection,
        }
    }
}