
use crate::shared_kernel::enums::Task;
use crate::infra::persistence::mongo::documents::task as documents;

impl From<Task> for documents::Task {
    fn from(value: Task) -> Self {
        match value {
            Task::AnyToAny => documents::Task::AnyToAny,
            Task::AutomaticSpeechRecognition => documents::Task::AutomaticSpeechRecognition,
            Task::AudioToAudio => documents::Task::AudioToAudio,
            Task::AudioClassification => documents::Task::AudioClassification,
            Task::AudioTextToText => documents::Task::AudioTextToText,
            Task::DepthEstimation => documents::Task::DepthEstimation,
            Task::DocumentQuestionAnswering => documents::Task::DocumentQuestionAnswering,
            Task::FeatureExtraction => documents::Task::FeatureExtraction,
            Task::FillMask => documents::Task::FillMask,
            Task::ImageFeatureExtraction => documents::Task::ImageFeatureExtraction,
            Task::ImageTextToText => documents::Task::ImageTextToText,
            Task::ImageToVideo => documents::Task::ImageToVideo,
            Task::ImageSegmentation => documents::Task::ImageSegmentation,
            Task::ImageClassification => documents::Task::ImageClassification,
            Task::ImageTo3d => documents::Task::ImageTo3d,
            Task::ImageToImage => documents::Task::ImageToImage,
            Task::ImageToText => documents::Task::ImageToText,
            Task::KeypointDetection => documents::Task::KeypointDetection,
            Task::MaskGeneration => documents::Task::MaskGeneration,
            Task::ObjectDetection => documents::Task::ObjectDetection,
            Task::QuestionAnswering => documents::Task::QuestionAnswering,
            Task::ReinforcementLearning => documents::Task::ReinforcementLearning,
            Task::SentenceSimilarity => documents::Task::SentenceSimilarity,
            Task::Summarization => documents::Task::Summarization,
            Task::TableQuestionAnswering => documents::Task::TableQuestionAnswering,
            Task::TextGeneration => documents::Task::TextGeneration,
            Task::TextRanking => documents::Task::TextRanking,
            Task::TabularClassification => documents::Task::TabularClassification,
            Task::TextTo3d => documents::Task::TextTo3d,
            Task::TextClassification => documents::Task::TextClassification,
            Task::TextToImage => documents::Task::TextToImage,
            Task::Translation => documents::Task::Translation,
            Task::TabularRegression => documents::Task::TabularRegression,
            Task::TextToSpeech => documents::Task::TextToSpeech,
            Task::TextToVideo => documents::Task::TextToVideo,
            Task::TokenClassification => documents::Task::TokenClassification,
            Task::UnconditionalImageGeneration => documents::Task::UnconditionalImageGeneration,
            Task::VideoClassification => documents::Task::VideoClassification,
            Task::VideoTextToText => documents::Task::VideoTextToText,
            Task::VideoToVideo => documents::Task::VideoToVideo,
            Task::VisualQuestionAnswering => documents::Task::VisualQuestionAnswering,
            Task::VisualDocumentRetrieval => documents::Task::VisualDocumentRetrieval,
            Task::ZeroShotClassification => documents::Task::ZeroShotClassification,
            Task::ZeroShotImageClassification => documents::Task::ZeroShotClassification,
            Task::ZeroShotObjectDetection => documents::Task::ZeroShotObjectDetection,
        }
    }
}