
use crate::application::inputs::task as inputs;
use crate::infra::persistence::mongo::documents::task as documents;

impl From<inputs::Task> for documents::Task {
    fn from(value: inputs::Task) -> Self {
        match value {
            inputs::Task::AnyToAny => documents::Task::AnyToAny,
            inputs::Task::AutomaticSpeechRecognition => documents::Task::AutomaticSpeechRecognition,
            inputs::Task::AudioToAudio => documents::Task::AudioToAudio,
            inputs::Task::AudioClassification => documents::Task::AudioClassification,
            inputs::Task::AudioTextToText => documents::Task::AudioTextToText,
            inputs::Task::DepthEstimation => documents::Task::DepthEstimation,
            inputs::Task::DocumentQuestionAnswering => documents::Task::DocumentQuestionAnswering,
            inputs::Task::FeatureExtraction => documents::Task::FeatureExtraction,
            inputs::Task::FillMask => documents::Task::FillMask,
            inputs::Task::ImageFeatureExtraction => documents::Task::ImageFeatureExtraction,
            inputs::Task::ImageTextToText => documents::Task::ImageTextToText,
            inputs::Task::ImageToVideo => documents::Task::ImageToVideo,
            inputs::Task::ImageSegmentation => documents::Task::ImageSegmentation,
            inputs::Task::ImageClassification => documents::Task::ImageClassification,
            inputs::Task::ImageTo3d => documents::Task::ImageTo3d,
            inputs::Task::ImageToImage => documents::Task::ImageToImage,
            inputs::Task::ImageToText => documents::Task::ImageToText,
            inputs::Task::KeypointDetection => documents::Task::KeypointDetection,
            inputs::Task::MaskGeneration => documents::Task::MaskGeneration,
            inputs::Task::ObjectDetection => documents::Task::ObjectDetection,
            inputs::Task::QuestionAnswering => documents::Task::QuestionAnswering,
            inputs::Task::ReinforcementLearning => documents::Task::ReinforcementLearning,
            inputs::Task::SentenceSimilarity => documents::Task::SentenceSimilarity,
            inputs::Task::Summarization => documents::Task::Summarization,
            inputs::Task::TableQuestionAnswering => documents::Task::TableQuestionAnswering,
            inputs::Task::TextGeneration => documents::Task::TextGeneration,
            inputs::Task::TextRanking => documents::Task::TextRanking,
            inputs::Task::TabularClassification => documents::Task::TabularClassification,
            inputs::Task::TextTo3d => documents::Task::TextTo3d,
            inputs::Task::TextClassification => documents::Task::TextClassification,
            inputs::Task::TextToImage => documents::Task::TextToImage,
            inputs::Task::Translation => documents::Task::Translation,
            inputs::Task::TabularRegression => documents::Task::TabularRegression,
            inputs::Task::TextToSpeech => documents::Task::TextToSpeech,
            inputs::Task::TextToVideo => documents::Task::TextToVideo,
            inputs::Task::TokenClassification => documents::Task::TokenClassification,
            inputs::Task::UnconditionalImageGeneration => documents::Task::UnconditionalImageGeneration,
            inputs::Task::VideoClassification => documents::Task::VideoClassification,
            inputs::Task::VideoTextToText => documents::Task::VideoTextToText,
            inputs::Task::VideoToVideo => documents::Task::VideoToVideo,
            inputs::Task::VisualQuestionAnswering => documents::Task::VisualQuestionAnswering,
            inputs::Task::VisualDocumentRetrieval => documents::Task::VisualDocumentRetrieval,
            inputs::Task::ZeroShotClassification => documents::Task::ZeroShotClassification,
            inputs::Task::ZeroShotImageClassification => documents::Task::ZeroShotClassification,
            inputs::Task::ZeroShotObjectDetection => documents::Task::ZeroShotObjectDetection,
        }
    }
}