/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Agents API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateAgentBody,
    CreateAgentBodyFromJSON,
    CreateAgentBodyToJSON,
    CreateAgentRecordBody,
    CreateAgentRecordBodyFromJSON,
    CreateAgentRecordBodyToJSON,
    CreateAgentRecordResponse,
    CreateAgentRecordResponseFromJSON,
    CreateAgentRecordResponseToJSON,
    CreateAgentResponse,
    CreateAgentResponseFromJSON,
    CreateAgentResponseToJSON,
    ListAgentRecordsResponse,
    ListAgentRecordsResponseFromJSON,
    ListAgentRecordsResponseToJSON,
    ListAgentsResponse,
    ListAgentsResponseFromJSON,
    ListAgentsResponseToJSON,
} from '../models';

export interface CreateAgentRequest {
    createAgentBody: CreateAgentBody;
}

export interface CreateAgentRecordRequest {
    createAgentRecordBody: CreateAgentRecordBody;
}

export interface ListAgentRecordsRequest {
    scope: ListAgentRecordsScopeEnum;
}

export interface ListAgentsRequest {
    scope: ListAgentsScopeEnum;
    includeEndpoints: boolean;
}

/**
 * 
 */
export class AgentsApi extends runtime.BaseAPI {

    /**
     * Register an agent
     */
    async createAgentRaw(requestParameters: CreateAgentRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateAgentResponse>> {
        if (requestParameters.createAgentBody === null || requestParameters.createAgentBody === undefined) {
            throw new runtime.RequiredError('createAgentBody','Required parameter requestParameters.createAgentBody was null or undefined when calling createAgent.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/agents-api/agents`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAgentBodyToJSON(requestParameters.createAgentBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAgentResponseFromJSON(jsonValue));
    }

    /**
     * Register an agent
     */
    async createAgent(requestParameters: CreateAgentRequest, initOverrides?: RequestInit): Promise<CreateAgentResponse> {
        const response = await this.createAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an agent record
     */
    async createAgentRecordRaw(requestParameters: CreateAgentRecordRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateAgentRecordResponse>> {
        if (requestParameters.createAgentRecordBody === null || requestParameters.createAgentRecordBody === undefined) {
            throw new runtime.RequiredError('createAgentRecordBody','Required parameter requestParameters.createAgentRecordBody was null or undefined when calling createAgentRecord.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/agents-api/agent-records`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAgentRecordBodyToJSON(requestParameters.createAgentRecordBody),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAgentRecordResponseFromJSON(jsonValue));
    }

    /**
     * Create an agent record
     */
    async createAgentRecord(requestParameters: CreateAgentRecordRequest, initOverrides?: RequestInit): Promise<CreateAgentRecordResponse> {
        const response = await this.createAgentRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List agent records
     */
    async listAgentRecordsRaw(requestParameters: ListAgentRecordsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListAgentRecordsResponse>> {
        if (requestParameters.scope === null || requestParameters.scope === undefined) {
            throw new runtime.RequiredError('scope','Required parameter requestParameters.scope was null or undefined when calling listAgentRecords.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/agents-api/agent-records`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters.scope))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListAgentRecordsResponseFromJSON(jsonValue));
    }

    /**
     * List agent records
     */
    async listAgentRecords(requestParameters: ListAgentRecordsRequest, initOverrides?: RequestInit): Promise<ListAgentRecordsResponse> {
        const response = await this.listAgentRecordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List agents
     */
    async listAgentsRaw(requestParameters: ListAgentsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ListAgentsResponse>> {
        if (requestParameters.scope === null || requestParameters.scope === undefined) {
            throw new runtime.RequiredError('scope','Required parameter requestParameters.scope was null or undefined when calling listAgents.');
        }

        if (requestParameters.includeEndpoints === null || requestParameters.includeEndpoints === undefined) {
            throw new runtime.RequiredError('includeEndpoints','Required parameter requestParameters.includeEndpoints was null or undefined when calling listAgents.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/agents-api/agents`.replace(`{${"scope"}}`, encodeURIComponent(String(requestParameters.scope))).replace(`{${"include_endpoints"}}`, encodeURIComponent(String(requestParameters.includeEndpoints))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListAgentsResponseFromJSON(jsonValue));
    }

    /**
     * List agents
     */
    async listAgents(requestParameters: ListAgentsRequest, initOverrides?: RequestInit): Promise<ListAgentsResponse> {
        const response = await this.listAgentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ListAgentRecordsScopeEnum {
    Owned = 'Owned',
    Shared = 'Shared'
}
/**
    * @export
    * @enum {string}
    */
export enum ListAgentsScopeEnum {
    Owned = 'Owned',
    Shared = 'Shared'
}
