apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlhub-artifact-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlhub-artifact-mongodb-deployment
  template:
    metadata:
      labels:
        app: mlhub-artifact-mongodb-deployment
    spec:
      containers:
        - name: mongodb
          image: mongo:8
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          resources: {}
          volumeMounts:
          - name: mongodb-data
            mountPath: "/data/db"
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mlhub-artifact-mongodb-pvc