use utoipa::OpenApi;
use crate::config::VERSION;

// Here we are import the helper function generated by utoipa to generate docs for
// handlers
use super::handlers::list_strategies::__path_list_strategies;
use super::handlers::deploy_model_with_strategy::__path_deploy_model_with_strategy;
use super::handlers::get_model_deployment::__path_get_model_deployment;
use super::handlers::list_model_deployment::__path_list_model_deployments;
use super::handlers::start_model_deployment::__path_start_model_deployment;
use super::handlers::stop_model_deployment::__path_stop_model_deployment;
use super::handlers::undeploy_model_deployment::__path_undeploy_model_deployment;

#[derive(OpenApi)]
#[openapi(
    paths(
        list_strategies,
        deploy_model_with_strategy,
        get_model_deployment,
        list_model_deployments,
        start_model_deployment,
        stop_model_deployment,
        undeploy_model_deployment,
    ),
    components(
        schemas(

        )
    ),
    info(title = "MLHub Deployments API", version=VERSION)
)]
pub struct ApiDoc;