apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-api-deployment
spec:
  selector:
    matchLabels:
      app: inference-api-deployment
  template:
    metadata:
      labels:
        app: inference-api-deployment
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: mlhub-postgres-service
        - name: DB_NAME
          value: mlhub
        - name: DB_PASSWORD
          value: dev
        - name: DB_USER
          value: mlhub
        - name: RUST_LOG
          value: debug
        image: tapis/inference-api:local
        imagePullPolicy: Never
        name: inference-api
        ports:
          - containerPort: 8000
            name: webserver
        resources: {}
        tty: true
      #   volumeMounts:
      #       - name: nfs-server-mount
      #         mountPath: /srv/mlhub/
      #         subPath: inference
      # volumes:
      #   - name: nfs-server-mount
      #     nfs: 
      #       server: '{{ NFS_SERVER_COMPONENT_IP }}'
      #       path: /
