#!/usr/bin/env bash

src=$1
if [ -z "$1" ]; then
    echo ❌ Must provide a path to the source script
    exit 1
fi

destination=$2

if [ -z "$2" ]; then
    echo ❌ Must provide a path for the destination script
    exit 1
fi

here=$(dirname "${BASH_SOURCE[0]}")

python3 "${here}/transform.py" $src $destination