pub use shared::models::presentation::http::v1::dto::{
    ListModelsPath,
    ListModelsRequest,
    GetModelPath,
    GetModelRequest,
    PublishArtifactPath,
    PublishArtifactRequest,
    PublishArtifactBody,
    DiscoverModelsPath,
    DiscoverModelsRequest,
    DiscoveryCriteriaBody,
    IngestArtifactBody,
    IngestModelPath,
    IngestModelRequest,
    DownloadModelPath,
    DownloadModelRequest,
    UploadModelRequest,
    Headers
};