apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlhub-nfs-server-deployment
spec:
  selector:
    matchLabels:
      app: mlhub-nfs-server-deployment
  template:
    metadata:
      labels:
        app: mlhub-nfs-server-deployment
    spec:
      containers:
      - name: nfsshare
        image: itsthenetwork/nfs-server-alpine:latest
        securityContext:
          privileged: true
        env:
        - name: SHARED_DIRECTORY
          value: "/nfsshare"
        ports:
        - name: nfs
          containerPort: 2049
        volumeMounts:
        - name: nfs-data
          mountPath: "/nfsshare"
        resources: {}
      volumes:
      - name: nfs-data
        persistentVolumeClaim:
          claimName: mlhub-nfs-server-pvc

