openapi: 3.1.0
info:
  title: MLHub Agents API
  description: ''
  license:
    name: ''
  version: 0.1.0
paths:
  /agents-api/agent-records:
    get:
      tags:
        - Agents
      summary: List agent records
      operationId: list_agent_records
      parameters:
        - name: scope
          in: path
          required: true
          schema:
            type: string
            enum:
              - Owned
              - Shared
      responses:
        '200':
          description: A list of agent records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAgentRecordsResponse'
        '500':
          description: Unable to list agent records
    post:
      tags:
        - Agents
      summary: Create an agent record
      operationId: create_agent_record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAgentRecordBody'
        required: true
      responses:
        '200':
          description: Agent record created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAgentRecordResponse'
        '500':
          description: Unable to create agent record
  /agents-api/agents:
    get:
      tags:
        - Agents
      summary: List agents
      operationId: list_agents
      parameters:
        - name: scope
          in: path
          required: true
          schema:
            type: string
            enum:
              - Owned
              - Shared
        - name: include_endpoints
          in: path
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: A list of agents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAgentsResponse'
        '500':
          description: Unable to list agents
    post:
      tags:
        - Agents
      summary: Register an agent
      operationId: create_agent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAgentBody'
        required: true
      responses:
        '200':
          description: Agent registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAgentResponse'
        '500':
          description: Unable to register agent
  /agents-api/healthcheck:
    get:
      tags:
        - Health
      summary: Check service health
      operationId: healthcheck
      responses:
        '200':
          description: Service is healthy
components:
  schemas:
    Agent:
      type: object
      required:
        - id
        - name
        - tenant_id
        - owner
        - description
        - deployment_modality
        - liveness
        - consecutive_missed_heartbeats
        - rest_http_endpoints
        - rpc_endpoints
        - stdio_endpoints
        - endpoints
        - tags
        - visibility
        - created_at
        - last_modified
      properties:
        agent_record_id:
          type:
            - string
            - 'null'
          format: uuid
        consecutive_missed_heartbeats:
          type: integer
          format: int32
          minimum: 0
        created_at:
          type: string
        deployment_modality:
          $ref: '#/components/schemas/AgentDeploymentModality'
        description:
          type: string
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/Endpoint'
        id:
          type: string
          format: uuid
        last_missed_heartbeat:
          type:
            - string
            - 'null'
        last_modified:
          type: string
        liveness:
          $ref: '#/components/schemas/AgentLiveness'
        name:
          type: string
        owner:
          type: string
        rest_http_endpoints:
          type: array
          items:
            $ref: '#/components/schemas/RestHttpAgentEndpoint'
        rpc_endpoints:
          type: array
          items:
            $ref: '#/components/schemas/RpcAgentEndpoint'
        stdio_endpoints:
          type: array
          items:
            $ref: '#/components/schemas/StdioAgentEndpoint'
        tags:
          type: array
          items:
            type: string
        tenant_id:
          type: string
        visibility:
          $ref: '#/components/schemas/Visibility'
    AgentArtifactType:
      type: string
      enum:
        - Binary
        - DockerImage
        - HelmChart
        - PythonPackage
        - SourceCode
        - Unspecified
    AgentDeploymentModality:
      type: string
      enum:
        - Persistent
        - OnDemand
    AgentLiveness:
      type: string
      enum:
        - Alive
        - Dead
    AgentProvider:
      type: object
      required:
        - organization
        - url
      properties:
        organization:
          type: string
        url:
          type: string
    AgentRecord:
      type: object
      required:
        - id
        - name
        - tenant_id
        - owner
        - description
        - rest_http_interfaces
        - rpc_interfaces
        - stdio_interfaces
        - capabilities
        - version
        - artifact_locators
        - skills
        - tags
        - visibility
      properties:
        artifact_locators:
          type: array
          items:
            $ref: '#/components/schemas/ArtifactLocator'
        capabilities:
          $ref: '#/components/schemas/Capabilities'
        description:
          type: string
        documentation_url:
          type:
            - string
            - 'null'
        icon_url:
          type:
            - string
            - 'null'
        id:
          type: string
          format: uuid
        name:
          type: string
        owner:
          type: string
        provider:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/AgentProvider'
        rest_http_interfaces:
          type: array
          items:
            $ref: '#/components/schemas/RestHttpAgentInterface'
        rpc_interfaces:
          type: array
          items:
            $ref: '#/components/schemas/RpcAgentInterface'
        skills:
          type: array
          items:
            $ref: '#/components/schemas/AgentSkill'
        stdio_interfaces:
          type: array
          items:
            $ref: '#/components/schemas/StdioAgentInterface'
        tags:
          type: array
          items:
            type: string
        tenant_id:
          type: string
        version:
          type: string
        visibility:
          $ref: '#/components/schemas/Visibility'
    AgentSkill:
      type: object
      required:
        - id
        - name
        - description
        - tags
        - examples
      properties:
        description:
          type: string
        examples:
          type: array
          items:
            type: string
        id:
          type: string
        name:
          type: string
        tags:
          type: array
          items:
            type: string
    ArtifactLocator:
      type: object
      required:
        - artifact_type
        - url
      properties:
        artifact_type:
          $ref: '#/components/schemas/AgentArtifactType'
        url:
          type: string
    Capabilities:
      type: object
      required:
        - streaming
        - push_notifications
      properties:
        push_notifications:
          type: boolean
        streaming:
          type: boolean
    CreateAgentBody:
      type: object
      required:
        - name
        - description
        - deployment_modality
      properties:
        agent_record_id:
          type:
            - string
            - 'null'
          format: uuid
        deployment_modality:
          $ref: '#/components/schemas/AgentDeploymentModality'
        description:
          type: string
        name:
          type: string
        rest_http_endpoints:
          type: array
          items:
            $ref: '#/components/schemas/RestHttpAgentEndpoint'
        rpc_endpoints:
          type: array
          items:
            $ref: '#/components/schemas/RpcAgentEndpoint'
        stdio_endpoints:
          type: array
          items:
            $ref: '#/components/schemas/StdioAgentEndpoint'
        tags:
          type: array
          items:
            type: string
        visibility:
          $ref: '#/components/schemas/Visibility'
      additionalProperties: false
    CreateAgentRecordBody:
      type: object
      required:
        - name
        - description
        - capabilities
        - version
      properties:
        artifact_locators:
          type:
            - array
            - 'null'
          items:
            $ref: '#/components/schemas/ArtifactLocator'
          default: []
        capabilities:
          $ref: '#/components/schemas/Capabilities'
        description:
          type: string
        documentation_url:
          type:
            - string
            - 'null'
        icon_url:
          type:
            - string
            - 'null'
        name:
          type: string
        provider:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/AgentProvider'
        rest_http_interfaces:
          type: array
          items:
            $ref: '#/components/schemas/RestHttpAgentInterface'
        rpc_interfaces:
          type: array
          items:
            $ref: '#/components/schemas/RpcAgentInterface'
        skills:
          type: array
          items:
            $ref: '#/components/schemas/AgentSkill'
        stdio_interfaces:
          type: array
          items:
            $ref: '#/components/schemas/StdioAgentInterface'
        tags:
          type: array
          items:
            type: string
        version:
          type: string
        visibility:
          $ref: '#/components/schemas/Visibility'
      additionalProperties: false
    CreateAgentRecordResponse:
      type: object
      required:
        - result
        - status
        - message
        - metadata
        - version
      properties:
        message:
          type: string
        metadata:
          type: object
        result:
          $ref: '#/components/schemas/AgentRecord'
        status:
          type: integer
          format: int32
          minimum: 0
        version:
          type: string
    CreateAgentResponse:
      type: object
      required:
        - result
        - status
        - message
        - metadata
        - version
      properties:
        message:
          type: string
        metadata:
          type: object
        result:
          $ref: '#/components/schemas/Agent'
        status:
          type: integer
          format: int32
          minimum: 0
        version:
          type: string
    Endpoint:
      type: object
      required:
        - id
        - tenant_id
        - target_resource_urn
        - target_name
        - slug
        - target_base_url
      properties:
        id:
          type: string
          format: uuid
        slug:
          type: string
        target_base_url:
          type: string
        target_name:
          type: string
        target_resource_urn:
          type: string
        tenant_id:
          type: string
    ListAgentRecordsResponse:
      type: object
      required:
        - result
        - status
        - message
        - metadata
        - version
      properties:
        message:
          type: string
        metadata:
          type: object
        result:
          type: array
          items:
            $ref: '#/components/schemas/AgentRecord'
        status:
          type: integer
          format: int32
          minimum: 0
        version:
          type: string
    ListAgentsResponse:
      type: object
      required:
        - result
        - status
        - message
        - metadata
        - version
      properties:
        message:
          type: string
        metadata:
          type: object
        result:
          type: array
          items:
            $ref: '#/components/schemas/Agent'
        status:
          type: integer
          format: int32
          minimum: 0
        version:
          type: string
    MessageBinding:
      type: string
      enum:
        - HttpJson
        - JsonRpc2_0
        - Grpc
    RestHttpAgentEndpoint:
      type: object
      properties:
        base_url:
          type:
            - string
            - 'null'
        liveness_probe:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/RestHttpLivenessProbe'
        message_binding:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/MessageBinding'
        name:
          type:
            - string
            - 'null'
    RestHttpAgentInterface:
      type: object
      required:
        - name
      properties:
        description:
          type:
            - string
            - 'null'
        liveness_probe_config:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/RestHttpLivenessProbe'
        message_binding:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/MessageBinding'
        name:
          type: string
    RestHttpLivenessProbe:
      type: object
      required:
        - route
        - interval_seconds
        - timeout_seconds
        - missed_heartbeat_threshold
        - initial_delay_seconds
      properties:
        initial_delay_seconds:
          type: integer
          format: int32
          minimum: 0
        interval_seconds:
          type: integer
          format: int32
          minimum: 0
        missed_heartbeat_threshold:
          type: integer
          format: int32
          minimum: 0
        route:
          type: string
        timeout_seconds:
          type: integer
          format: int32
          minimum: 0
    RpcAgentEndpoint:
      type: object
      properties:
        base_url:
          type:
            - string
            - 'null'
        message_binding:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/MessageBinding'
        name:
          type:
            - string
            - 'null'
    RpcAgentInterface:
      type: object
      required:
        - name
      properties:
        description:
          type:
            - string
            - 'null'
        message_binding:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/MessageBinding'
        name:
          type: string
    StdioAgentEndpoint:
      type: object
      properties:
        base_url:
          type:
            - string
            - 'null'
        message_binding:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/MessageBinding'
        name:
          type:
            - string
            - 'null'
    StdioAgentInterface:
      type: object
      required:
        - name
      properties:
        description:
          type:
            - string
            - 'null'
        message_binding:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/MessageBinding'
        name:
          type: string
    Visibility:
      type: string
      enum:
        - Public
        - Private
