
use crate::domain::entities::task as entities;
use crate::domain::external::huggingface::task;

impl From<task::Task> for entities::Task {
    fn from(value: task::Task) -> Self {
        match value {
            task::Task::AnyToAny => entities::Task::AnyToAny,
            task::Task::AutomaticSpeechRecognition => entities::Task::AutomaticSpeechRecognition,
            task::Task::AudioToAudio => entities::Task::AudioToAudio,
            task::Task::AudioClassification => entities::Task::AudioClassification,
            task::Task::AudioTextToText => entities::Task::AudioTextToText,
            task::Task::DepthEstimation => entities::Task::DepthEstimation,
            task::Task::DocumentQuestionAnswering => entities::Task::DocumentQuestionAnswering,
            task::Task::FeatureExtraction => entities::Task::FeatureExtraction,
            task::Task::FillMask => entities::Task::FillMask,
            task::Task::ImageFeatureExtraction => entities::Task::ImageFeatureExtraction,
            task::Task::ImageTextToText => entities::Task::ImageTextToText,
            task::Task::ImageToVideo => entities::Task::ImageToVideo,
            task::Task::ImageSegmentation => entities::Task::ImageSegmentation,
            task::Task::ImageClassification => entities::Task::ImageClassification,
            task::Task::ImageTo3d => entities::Task::ImageTo3d,
            task::Task::ImageToImage => entities::Task::ImageToImage,
            task::Task::ImageToText => entities::Task::ImageToText,
            task::Task::KeypointDetection => entities::Task::KeypointDetection,
            task::Task::MaskGeneration => entities::Task::MaskGeneration,
            task::Task::ObjectDetection => entities::Task::ObjectDetection,
            task::Task::QuestionAnswering => entities::Task::QuestionAnswering,
            task::Task::ReinforcementLearning => entities::Task::ReinforcementLearning,
            task::Task::SentenceSimilarity => entities::Task::SentenceSimilarity,
            task::Task::Summarization => entities::Task::Summarization,
            task::Task::TableQuestionAnswering => entities::Task::TableQuestionAnswering,
            task::Task::TextGeneration => entities::Task::TextGeneration,
            task::Task::TextRanking => entities::Task::TextRanking,
            task::Task::TabularClassification => entities::Task::TabularClassification,
            task::Task::TextTo3d => entities::Task::TextTo3d,
            task::Task::TextClassification => entities::Task::TextClassification,
            task::Task::TextToImage => entities::Task::TextToImage,
            task::Task::Translation => entities::Task::Translation,
            task::Task::TabularRegression => entities::Task::TabularRegression,
            task::Task::TextToSpeech => entities::Task::TextToSpeech,
            task::Task::TextToVideo => entities::Task::TextToVideo,
            task::Task::TokenClassification => entities::Task::TokenClassification,
            task::Task::UnconditionalImageGeneration => entities::Task::UnconditionalImageGeneration,
            task::Task::VideoClassification => entities::Task::VideoClassification,
            task::Task::VideoTextToText => entities::Task::VideoTextToText,
            task::Task::VideoToVideo => entities::Task::VideoToVideo,
            task::Task::VisualQuestionAnswering => entities::Task::VisualQuestionAnswering,
            task::Task::VisualDocumentRetrieval => entities::Task::VisualDocumentRetrieval,
            task::Task::ZeroShotClassification => entities::Task::ZeroShotClassification,
            task::Task::ZeroShotImageClassification => entities::Task::ZeroShotClassification,
            task::Task::ZeroShotObjectDetection => entities::Task::ZeroShotObjectDetection,
        }
    }
}