pub const ARTIFACT_INGESTION_COLLECTION: &str = "ARTIFACT_INGESTIONS";
pub const MODEL_METADATA_COLLECTION: &str = "MODEL_METADATA";
pub const ARTIFACT_PUBLICATION_COLLECTION: &str = "ARTIFACT_PUBLICATIONS";
pub const MODEL_DEPLOYMENT_COLLECTION: &str = "MODEL_DEPLOYMENTS";
pub const AGENT_RECORD_COLLECTION: &str = "AGENT_RECORDS";
pub const AGENT_COLLECTION: &str = "AGENTS";
pub const ENDPOINT_COLLECTION: &str = "ENDPOINTS";
pub const DEPLOYMENT_ARGUMENT_COLLECTION: &str = "DEPLOYMENT_ARGUMENTS";
