use crate::presentation::http::v1::requests::common::tasks as request;
use crate::shared_kernel::enums::Task;

impl From<request::Task> for Task {
    fn from(value: request::Task) -> Self {
        match value {
            request::Task::AnyToAny => Task::AnyToAny,
            request::Task::AutomaticSpeechRecognition => Task::AutomaticSpeechRecognition,
            request::Task::AudioToAudio => Task::AudioToAudio,
            request::Task::AudioClassification => Task::AudioClassification,
            request::Task::AudioTextToText => Task::AudioTextToText,
            request::Task::DepthEstimation => Task::DepthEstimation,
            request::Task::DocumentQuestionAnswering => Task::DocumentQuestionAnswering,
            request::Task::FeatureExtraction => Task::FeatureExtraction,
            request::Task::FillMask => Task::FillMask,
            request::Task::ImageFeatureExtraction => Task::ImageFeatureExtraction,
            request::Task::ImageTextToText => Task::ImageTextToText,
            request::Task::ImageToVideo => Task::ImageToVideo,
            request::Task::ImageSegmentation => Task::ImageSegmentation,
            request::Task::ImageClassification => Task::ImageClassification,
            request::Task::ImageTo3d => Task::ImageTo3d,
            request::Task::ImageToImage => Task::ImageToImage,
            request::Task::ImageToText => Task::ImageToText,
            request::Task::KeypointDetection => Task::KeypointDetection,
            request::Task::MaskGeneration => Task::MaskGeneration,
            request::Task::ObjectDetection => Task::ObjectDetection,
            request::Task::QuestionAnswering => Task::QuestionAnswering,
            request::Task::ReinforcementLearning => Task::ReinforcementLearning,
            request::Task::SentenceSimilarity => Task::SentenceSimilarity,
            request::Task::Summarization => Task::Summarization,
            request::Task::TableQuestionAnswering => Task::TableQuestionAnswering,
            request::Task::TextGeneration => Task::TextGeneration,
            request::Task::TextRanking => Task::TextRanking,
            request::Task::TabularClassification => Task::TabularClassification,
            request::Task::TextTo3d => Task::TextTo3d,
            request::Task::TextClassification => Task::TextClassification,
            request::Task::TextToImage => Task::TextToImage,
            request::Task::Translation => Task::Translation,
            request::Task::TabularRegression => Task::TabularRegression,
            request::Task::TextToSpeech => Task::TextToSpeech,
            request::Task::TextToVideo => Task::TextToVideo,
            request::Task::TokenClassification => Task::TokenClassification,
            request::Task::UnconditionalImageGeneration => Task::UnconditionalImageGeneration,
            request::Task::VideoClassification => Task::VideoClassification,
            request::Task::VideoTextToText => Task::VideoTextToText,
            request::Task::VideoToVideo => Task::VideoToVideo,
            request::Task::VisualQuestionAnswering => Task::VisualQuestionAnswering,
            request::Task::VisualDocumentRetrieval => Task::VisualDocumentRetrieval,
            request::Task::ZeroShotClassification => Task::ZeroShotClassification,
            request::Task::ZeroShotImageClassification => Task::ZeroShotClassification,
            request::Task::ZeroShotObjectDetection => Task::ZeroShotObjectDetection,
        }
    }
}