use crate::presentation::http::v1::requests::common::tasks as request;
use crate::application::inputs::task as input;

impl From<request::Task> for input::Task {
    fn from(value: request::Task) -> Self {
        match value {
            request::Task::AnyToAny => input::Task::AnyToAny,
            request::Task::AutomaticSpeechRecognition => input::Task::AutomaticSpeechRecognition,
            request::Task::AudioToAudio => input::Task::AudioToAudio,
            request::Task::AudioClassification => input::Task::AudioClassification,
            request::Task::AudioTextToText => input::Task::AudioTextToText,
            request::Task::DepthEstimation => input::Task::DepthEstimation,
            request::Task::DocumentQuestionAnswering => input::Task::DocumentQuestionAnswering,
            request::Task::FeatureExtraction => input::Task::FeatureExtraction,
            request::Task::FillMask => input::Task::FillMask,
            request::Task::ImageFeatureExtraction => input::Task::ImageFeatureExtraction,
            request::Task::ImageTextToText => input::Task::ImageTextToText,
            request::Task::ImageToVideo => input::Task::ImageToVideo,
            request::Task::ImageSegmentation => input::Task::ImageSegmentation,
            request::Task::ImageClassification => input::Task::ImageClassification,
            request::Task::ImageTo3d => input::Task::ImageTo3d,
            request::Task::ImageToImage => input::Task::ImageToImage,
            request::Task::ImageToText => input::Task::ImageToText,
            request::Task::KeypointDetection => input::Task::KeypointDetection,
            request::Task::MaskGeneration => input::Task::MaskGeneration,
            request::Task::ObjectDetection => input::Task::ObjectDetection,
            request::Task::QuestionAnswering => input::Task::QuestionAnswering,
            request::Task::ReinforcementLearning => input::Task::ReinforcementLearning,
            request::Task::SentenceSimilarity => input::Task::SentenceSimilarity,
            request::Task::Summarization => input::Task::Summarization,
            request::Task::TableQuestionAnswering => input::Task::TableQuestionAnswering,
            request::Task::TextGeneration => input::Task::TextGeneration,
            request::Task::TextRanking => input::Task::TextRanking,
            request::Task::TabularClassification => input::Task::TabularClassification,
            request::Task::TextTo3d => input::Task::TextTo3d,
            request::Task::TextClassification => input::Task::TextClassification,
            request::Task::TextToImage => input::Task::TextToImage,
            request::Task::Translation => input::Task::Translation,
            request::Task::TabularRegression => input::Task::TabularRegression,
            request::Task::TextToSpeech => input::Task::TextToSpeech,
            request::Task::TextToVideo => input::Task::TextToVideo,
            request::Task::TokenClassification => input::Task::TokenClassification,
            request::Task::UnconditionalImageGeneration => input::Task::UnconditionalImageGeneration,
            request::Task::VideoClassification => input::Task::VideoClassification,
            request::Task::VideoTextToText => input::Task::VideoTextToText,
            request::Task::VideoToVideo => input::Task::VideoToVideo,
            request::Task::VisualQuestionAnswering => input::Task::VisualQuestionAnswering,
            request::Task::VisualDocumentRetrieval => input::Task::VisualDocumentRetrieval,
            request::Task::ZeroShotClassification => input::Task::ZeroShotClassification,
            request::Task::ZeroShotImageClassification => input::Task::ZeroShotClassification,
            request::Task::ZeroShotObjectDetection => input::Task::ZeroShotObjectDetection,
        }
    }
}