
use crate::domain::entities::task as entities;
use crate::presentation::http::v1::requests::common::tasks as dto;

impl From<entities::Task> for dto::Task {
    fn from(value: entities::Task) -> Self {
        match value {
            entities::Task::AnyToAny => dto::Task::AnyToAny,
            entities::Task::AutomaticSpeechRecognition => dto::Task::AutomaticSpeechRecognition,
            entities::Task::AudioToAudio => dto::Task::AudioToAudio,
            entities::Task::AudioClassification => dto::Task::AudioClassification,
            entities::Task::AudioTextToText => dto::Task::AudioTextToText,
            entities::Task::DepthEstimation => dto::Task::DepthEstimation,
            entities::Task::DocumentQuestionAnswering => dto::Task::DocumentQuestionAnswering,
            entities::Task::FeatureExtraction => dto::Task::FeatureExtraction,
            entities::Task::FillMask => dto::Task::FillMask,
            entities::Task::ImageFeatureExtraction => dto::Task::ImageFeatureExtraction,
            entities::Task::ImageTextToText => dto::Task::ImageTextToText,
            entities::Task::ImageToVideo => dto::Task::ImageToVideo,
            entities::Task::ImageSegmentation => dto::Task::ImageSegmentation,
            entities::Task::ImageClassification => dto::Task::ImageClassification,
            entities::Task::ImageTo3d => dto::Task::ImageTo3d,
            entities::Task::ImageToImage => dto::Task::ImageToImage,
            entities::Task::ImageToText => dto::Task::ImageToText,
            entities::Task::KeypointDetection => dto::Task::KeypointDetection,
            entities::Task::MaskGeneration => dto::Task::MaskGeneration,
            entities::Task::ObjectDetection => dto::Task::ObjectDetection,
            entities::Task::QuestionAnswering => dto::Task::QuestionAnswering,
            entities::Task::ReinforcementLearning => dto::Task::ReinforcementLearning,
            entities::Task::SentenceSimilarity => dto::Task::SentenceSimilarity,
            entities::Task::Summarization => dto::Task::Summarization,
            entities::Task::TableQuestionAnswering => dto::Task::TableQuestionAnswering,
            entities::Task::TextGeneration => dto::Task::TextGeneration,
            entities::Task::TextRanking => dto::Task::TextRanking,
            entities::Task::TabularClassification => dto::Task::TabularClassification,
            entities::Task::TextTo3d => dto::Task::TextTo3d,
            entities::Task::TextClassification => dto::Task::TextClassification,
            entities::Task::TextToImage => dto::Task::TextToImage,
            entities::Task::Translation => dto::Task::Translation,
            entities::Task::TabularRegression => dto::Task::TabularRegression,
            entities::Task::TextToSpeech => dto::Task::TextToSpeech,
            entities::Task::TextToVideo => dto::Task::TextToVideo,
            entities::Task::TokenClassification => dto::Task::TokenClassification,
            entities::Task::UnconditionalImageGeneration => dto::Task::UnconditionalImageGeneration,
            entities::Task::VideoClassification => dto::Task::VideoClassification,
            entities::Task::VideoTextToText => dto::Task::VideoTextToText,
            entities::Task::VideoToVideo => dto::Task::VideoToVideo,
            entities::Task::VisualQuestionAnswering => dto::Task::VisualQuestionAnswering,
            entities::Task::VisualDocumentRetrieval => dto::Task::VisualDocumentRetrieval,
            entities::Task::ZeroShotClassification => dto::Task::ZeroShotClassification,
            entities::Task::ZeroShotImageClassification => dto::Task::ZeroShotClassification,
            entities::Task::ZeroShotObjectDetection => dto::Task::ZeroShotObjectDetection,
        }
    }
}