/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssociateModelBody
 */
export interface AssociateModelBody {
    /**
     * 
     * @type {string}
     * @memberof AssociateModelBody
     */
    model_id: string;
}

export function AssociateModelBodyFromJSON(json: any): AssociateModelBody {
    return AssociateModelBodyFromJSONTyped(json, false);
}

export function AssociateModelBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssociateModelBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'model_id': json['model_id'],
    };
}

export function AssociateModelBodyToJSON(value?: AssociateModelBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model_id': value.model_id,
    };
}

