/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Locator,
    LocatorFromJSON,
    LocatorFromJSONTyped,
    LocatorToJSON,
    Platform,
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
} from './';

/**
 * 
 * @export
 * @interface Canonical
 */
export interface Canonical {
    /**
     * 
     * @type {string}
     * @memberof Canonical
     */
    author?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Canonical
     */
    downloads?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Canonical
     */
    gated?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof Canonical
     */
    likes?: number | null;
    /**
     * 
     * @type {Locator}
     * @memberof Canonical
     */
    locator: Locator;
    /**
     * 
     * @type {string}
     * @memberof Canonical
     */
    model_id: string;
    /**
     * 
     * @type {Platform}
     * @memberof Canonical
     */
    platform: Platform;
    /**
     * 
     * @type {boolean}
     * @memberof Canonical
     */
    _private?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof Canonical
     */
    sha?: string | null;
}

export function CanonicalFromJSON(json: any): Canonical {
    return CanonicalFromJSONTyped(json, false);
}

export function CanonicalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Canonical {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': !exists(json, 'author') ? undefined : json['author'],
        'downloads': !exists(json, 'downloads') ? undefined : json['downloads'],
        'gated': !exists(json, 'gated') ? undefined : json['gated'],
        'likes': !exists(json, 'likes') ? undefined : json['likes'],
        'locator': LocatorFromJSON(json['locator']),
        'model_id': json['model_id'],
        'platform': PlatformFromJSON(json['platform']),
        '_private': !exists(json, 'private') ? undefined : json['private'],
        'sha': !exists(json, 'sha') ? undefined : json['sha'],
    };
}

export function CanonicalToJSON(value?: Canonical | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'downloads': value.downloads,
        'gated': value.gated,
        'likes': value.likes,
        'locator': LocatorToJSON(value.locator),
        'model_id': value.model_id,
        'platform': PlatformToJSON(value.platform),
        'private': value._private,
        'sha': value.sha,
    };
}

