/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConflictResponse
 */
export interface ConflictResponse {
    /**
     * 
     * @type {string}
     * @memberof ConflictResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ConflictResponse
     */
    metadata: object;
    /**
     * 
     * @type {any}
     * @memberof ConflictResponse
     */
    result: any | null;
    /**
     * 
     * @type {number}
     * @memberof ConflictResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ConflictResponse
     */
    version: string;
}

export function ConflictResponseFromJSON(json: any): ConflictResponse {
    return ConflictResponseFromJSONTyped(json, false);
}

export function ConflictResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConflictResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': json['result'],
        'status': json['status'],
        'version': json['version'],
    };
}

export function ConflictResponseToJSON(value?: ConflictResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': value.result,
        'status': value.status,
        'version': value.version,
    };
}

