/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Task,
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateModelBody
 */
export interface CreateModelBody {
    /**
     * 
     * @type {string}
     * @memberof CreateModelBody
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateModelBody
     */
    libraries?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateModelBody
     */
    license?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateModelBody
     */
    model_type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateModelBody
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateModelBody
     */
    regulatory?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateModelBody
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {Array<Task>}
     * @memberof CreateModelBody
     */
    task_types?: Array<Task> | null;
}

export function CreateModelBodyFromJSON(json: any): CreateModelBody {
    return CreateModelBodyFromJSONTyped(json, false);
}

export function CreateModelBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateModelBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'libraries': !exists(json, 'libraries') ? undefined : json['libraries'],
        'license': !exists(json, 'license') ? undefined : json['license'],
        'model_type': !exists(json, 'model_type') ? undefined : json['model_type'],
        'name': json['name'],
        'regulatory': !exists(json, 'regulatory') ? undefined : json['regulatory'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'task_types': !exists(json, 'task_types') ? undefined : (json['task_types'] === null ? null : (json['task_types'] as Array<any>).map(TaskFromJSON)),
    };
}

export function CreateModelBodyToJSON(value?: CreateModelBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'libraries': value.libraries,
        'license': value.license,
        'model_type': value.model_type,
        'name': value.name,
        'regulatory': value.regulatory,
        'tags': value.tags,
        'task_types': value.task_types === undefined ? undefined : (value.task_types === null ? null : (value.task_types as Array<any>).map(TaskToJSON)),
    };
}

