/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Visibility,
    VisibilityFromJSON,
    VisibilityFromJSONTyped,
    VisibilityToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateModelBody
 */
export interface CreateModelBody {
    /**
     * 
     * @type {string}
     * @memberof CreateModelBody
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateModelBody
     */
    external_model_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateModelBody
     */
    name: string;
    /**
     * 
     * @type {Visibility}
     * @memberof CreateModelBody
     */
    visibility?: Visibility;
}

export function CreateModelBodyFromJSON(json: any): CreateModelBody {
    return CreateModelBodyFromJSONTyped(json, false);
}

export function CreateModelBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateModelBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'external_model_id': json['external_model_id'],
        'name': json['name'],
        'visibility': !exists(json, 'visibility') ? undefined : VisibilityFromJSON(json['visibility']),
    };
}

export function CreateModelBodyToJSON(value?: CreateModelBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'external_model_id': value.external_model_id,
        'name': value.name,
        'visibility': VisibilityToJSON(value.visibility),
    };
}

