/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DeploymentTargetType {
    HpcClusterQueue = 'HpcClusterQueue'
}

export function DeploymentTargetTypeFromJSON(json: any): DeploymentTargetType {
    return DeploymentTargetTypeFromJSONTyped(json, false);
}

export function DeploymentTargetTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentTargetType {
    return json as DeploymentTargetType;
}

export function DeploymentTargetTypeToJSON(value?: DeploymentTargetType | null): any {
    return value as any;
}

