/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeploymentParameterChoice,
    DeploymentParameterChoiceFromJSON,
    DeploymentParameterChoiceFromJSONTyped,
    DeploymentParameterChoiceToJSON,
    DeploymentParameterType,
    DeploymentParameterTypeFromJSON,
    DeploymentParameterTypeFromJSONTyped,
    DeploymentParameterTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeploymentParameter
 */
export interface DeploymentParameter {
    /**
     * 
     * @type {Array<DeploymentParameterChoice>}
     * @memberof DeploymentParameter
     */
    choices?: Array<DeploymentParameterChoice> | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentParameter
     */
    _default?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentParameter
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentParameter
     */
    name: string;
    /**
     * 
     * @type {DeploymentParameterType}
     * @memberof DeploymentParameter
     */
    parameter_type: DeploymentParameterType;
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentParameter
     */
    required: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentParameter
     */
    secret: boolean;
}

export function DeploymentParameterFromJSON(json: any): DeploymentParameter {
    return DeploymentParameterFromJSONTyped(json, false);
}

export function DeploymentParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentParameter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'choices': !exists(json, 'choices') ? undefined : (json['choices'] === null ? null : (json['choices'] as Array<any>).map(DeploymentParameterChoiceFromJSON)),
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        'parameter_type': DeploymentParameterTypeFromJSON(json['parameter_type']),
        'required': json['required'],
        'secret': json['secret'],
    };
}

export function DeploymentParameterToJSON(value?: DeploymentParameter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'choices': value.choices === undefined ? undefined : (value.choices === null ? null : (value.choices as Array<any>).map(DeploymentParameterChoiceToJSON)),
        'default': value._default,
        'description': value.description,
        'name': value.name,
        'parameter_type': DeploymentParameterTypeToJSON(value.parameter_type),
        'required': value.required,
        'secret': value.secret,
    };
}

