/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DeploymentParameterType {
    String = 'String',
    Integer = 'Integer',
    Float = 'Float',
    Boolean = 'Boolean'
}

export function DeploymentParameterTypeFromJSON(json: any): DeploymentParameterType {
    return DeploymentParameterTypeFromJSONTyped(json, false);
}

export function DeploymentParameterTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentParameterType {
    return json as DeploymentParameterType;
}

export function DeploymentParameterTypeToJSON(value?: DeploymentParameterType | null): any {
    return value as any;
}

