/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeploymentModality,
    DeploymentModalityFromJSON,
    DeploymentModalityFromJSONTyped,
    DeploymentModalityToJSON,
    DeploymentTargetType,
    DeploymentTargetTypeFromJSON,
    DeploymentTargetTypeFromJSONTyped,
    DeploymentTargetTypeToJSON,
    HpcClusterQueueTarget,
    HpcClusterQueueTargetFromJSON,
    HpcClusterQueueTargetFromJSONTyped,
    HpcClusterQueueTargetToJSON,
    ServingRuntime,
    ServingRuntimeFromJSON,
    ServingRuntimeFromJSONTyped,
    ServingRuntimeToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeploymentOption
 */
export interface DeploymentOption {
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentOption
     */
    available: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeploymentOption
     */
    created_at: string;
    /**
     * 
     * @type {DeploymentTargetType}
     * @memberof DeploymentOption
     */
    deployment_target_type: DeploymentTargetType;
    /**
     * 
     * @type {string}
     * @memberof DeploymentOption
     */
    external_model_id: string;
    /**
     * 
     * @type {HpcClusterQueueTarget}
     * @memberof DeploymentOption
     */
    hpc_cluster_queue?: HpcClusterQueueTarget;
    /**
     * 
     * @type {string}
     * @memberof DeploymentOption
     */
    id: string;
    /**
     * 
     * @type {ServingRuntime}
     * @memberof DeploymentOption
     */
    serving_runtime: ServingRuntime;
    /**
     * 
     * @type {Array<DeploymentModality>}
     * @memberof DeploymentOption
     */
    supported_deployment_modalities: Array<DeploymentModality>;
    /**
     * 
     * @type {string}
     * @memberof DeploymentOption
     */
    updated_at: string;
}

export function DeploymentOptionFromJSON(json: any): DeploymentOption {
    return DeploymentOptionFromJSONTyped(json, false);
}

export function DeploymentOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'available': json['available'],
        'created_at': json['created_at'],
        'deployment_target_type': DeploymentTargetTypeFromJSON(json['deployment_target_type']),
        'external_model_id': json['external_model_id'],
        'hpc_cluster_queue': !exists(json, 'hpc_cluster_queue') ? undefined : HpcClusterQueueTargetFromJSON(json['hpc_cluster_queue']),
        'id': json['id'],
        'serving_runtime': ServingRuntimeFromJSON(json['serving_runtime']),
        'supported_deployment_modalities': ((json['supported_deployment_modalities'] as Array<any>).map(DeploymentModalityFromJSON)),
        'updated_at': json['updated_at'],
    };
}

export function DeploymentOptionToJSON(value?: DeploymentOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'available': value.available,
        'created_at': value.created_at,
        'deployment_target_type': DeploymentTargetTypeToJSON(value.deployment_target_type),
        'external_model_id': value.external_model_id,
        'hpc_cluster_queue': HpcClusterQueueTargetToJSON(value.hpc_cluster_queue),
        'id': value.id,
        'serving_runtime': ServingRuntimeToJSON(value.serving_runtime),
        'supported_deployment_modalities': ((value.supported_deployment_modalities as Array<any>).map(DeploymentModalityToJSON)),
        'updated_at': value.updated_at,
    };
}

