/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeploymentParameter,
    DeploymentParameterFromJSON,
    DeploymentParameterFromJSONTyped,
    DeploymentParameterToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeploymentOptionDetailAllOf
 */
export interface DeploymentOptionDetailAllOf {
    /**
     * 
     * @type {Array<DeploymentParameter>}
     * @memberof DeploymentOptionDetailAllOf
     */
    parameters: Array<DeploymentParameter>;
}

export function DeploymentOptionDetailAllOfFromJSON(json: any): DeploymentOptionDetailAllOf {
    return DeploymentOptionDetailAllOfFromJSONTyped(json, false);
}

export function DeploymentOptionDetailAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentOptionDetailAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parameters': ((json['parameters'] as Array<any>).map(DeploymentParameterFromJSON)),
    };
}

export function DeploymentOptionDetailAllOfToJSON(value?: DeploymentOptionDetailAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parameters': ((value.parameters as Array<any>).map(DeploymentParameterToJSON)),
    };
}

