/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeploymentParameterChoice
 */
export interface DeploymentParameterChoice {
    /**
     * 
     * @type {string}
     * @memberof DeploymentParameterChoice
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentParameterChoice
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeploymentParameterChoice
     */
    value: string;
}

export function DeploymentParameterChoiceFromJSON(json: any): DeploymentParameterChoice {
    return DeploymentParameterChoiceFromJSONTyped(json, false);
}

export function DeploymentParameterChoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentParameterChoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'enabled': json['enabled'],
        'value': json['value'],
    };
}

export function DeploymentParameterChoiceToJSON(value?: DeploymentParameterChoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'enabled': value.enabled,
        'value': value.value,
    };
}

