/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Platform,
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeploymentStrategyCriterion
 */
export interface DeploymentStrategyCriterion {
    /**
     * 
     * @type {string}
     * @memberof DeploymentStrategyCriterion
     */
    name: string;
    /**
     * 
     * @type {Platform}
     * @memberof DeploymentStrategyCriterion
     */
    platform: Platform;
}

export function DeploymentStrategyCriterionFromJSON(json: any): DeploymentStrategyCriterion {
    return DeploymentStrategyCriterionFromJSONTyped(json, false);
}

export function DeploymentStrategyCriterionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentStrategyCriterion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'platform': PlatformFromJSON(json['platform']),
    };
}

export function DeploymentStrategyCriterionToJSON(value?: DeploymentStrategyCriterion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'platform': PlatformToJSON(value.platform),
    };
}

