/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Platform,
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeploymentStrategyReference
 */
export interface DeploymentStrategyReference {
    /**
     * 
     * @type {string}
     * @memberof DeploymentStrategyReference
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentStrategyReference
     */
    name: string;
    /**
     * 
     * @type {Platform}
     * @memberof DeploymentStrategyReference
     */
    platform: Platform;
}

export function DeploymentStrategyReferenceFromJSON(json: any): DeploymentStrategyReference {
    return DeploymentStrategyReferenceFromJSONTyped(json, false);
}

export function DeploymentStrategyReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentStrategyReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        'platform': PlatformFromJSON(json['platform']),
    };
}

export function DeploymentStrategyReferenceToJSON(value?: DeploymentStrategyReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
        'platform': PlatformToJSON(value.platform),
    };
}

