/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeploymentStrategyReference,
    DeploymentStrategyReferenceFromJSON,
    DeploymentStrategyReferenceFromJSONTyped,
    DeploymentStrategyReferenceToJSON,
    Task,
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './';

/**
 * 
 * @export
 * @interface DerivedModelMetadata
 */
export interface DerivedModelMetadata {
    /**
     * 
     * @type {string}
     * @memberof DerivedModelMetadata
     */
    author?: string | null;
    /**
     * 
     * @type {Array<DeploymentStrategyReference>}
     * @memberof DerivedModelMetadata
     */
    deployment_strategies: Array<DeploymentStrategyReference>;
    /**
     * 
     * @type {number}
     * @memberof DerivedModelMetadata
     */
    downloads?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof DerivedModelMetadata
     */
    gated: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof DerivedModelMetadata
     */
    inference_runtimes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DerivedModelMetadata
     */
    license?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DerivedModelMetadata
     */
    likes?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DerivedModelMetadata
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DerivedModelMetadata
     */
    _private: boolean;
    /**
     * 
     * @type {number}
     * @memberof DerivedModelMetadata
     */
    size: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DerivedModelMetadata
     */
    tags: Array<string>;
    /**
     * 
     * @type {Array<Task>}
     * @memberof DerivedModelMetadata
     */
    task_types: Array<Task>;
}

export function DerivedModelMetadataFromJSON(json: any): DerivedModelMetadata {
    return DerivedModelMetadataFromJSONTyped(json, false);
}

export function DerivedModelMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DerivedModelMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': !exists(json, 'author') ? undefined : json['author'],
        'deployment_strategies': ((json['deployment_strategies'] as Array<any>).map(DeploymentStrategyReferenceFromJSON)),
        'downloads': !exists(json, 'downloads') ? undefined : json['downloads'],
        'gated': json['gated'],
        'inference_runtimes': json['inference_runtimes'],
        'license': !exists(json, 'license') ? undefined : json['license'],
        'likes': !exists(json, 'likes') ? undefined : json['likes'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        '_private': json['private'],
        'size': json['size'],
        'tags': json['tags'],
        'task_types': ((json['task_types'] as Array<any>).map(TaskFromJSON)),
    };
}

export function DerivedModelMetadataToJSON(value?: DerivedModelMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'deployment_strategies': ((value.deployment_strategies as Array<any>).map(DeploymentStrategyReferenceToJSON)),
        'downloads': value.downloads,
        'gated': value.gated,
        'inference_runtimes': value.inference_runtimes,
        'license': value.license,
        'likes': value.likes,
        'name': value.name,
        'private': value._private,
        'size': value.size,
        'tags': value.tags,
        'task_types': ((value.task_types as Array<any>).map(TaskToJSON)),
    };
}

