/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeploymentModality,
    DeploymentModalityFromJSON,
    DeploymentModalityFromJSONTyped,
    DeploymentModalityToJSON,
    ModelProvider,
    ModelProviderFromJSON,
    ModelProviderFromJSONTyped,
    ModelProviderToJSON,
    ServingRuntime,
    ServingRuntimeFromJSON,
    ServingRuntimeFromJSONTyped,
    ServingRuntimeToJSON,
    Task,
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './';

/**
 * 
 * @export
 * @interface DiscoveryCriterion
 */
export interface DiscoveryCriterion {
    /**
     * 
     * @type {string}
     * @memberof DiscoveryCriterion
     */
    author?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryCriterion
     */
    batch_scheduler_queue_ids?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof DiscoveryCriterion
     */
    has_deployment_options?: boolean | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryCriterion
     */
    hpc_cluster_ids?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryCriterion
     */
    inference_runtimes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryCriterion
     */
    license?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryCriterion
     */
    max_downloads?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryCriterion
     */
    max_likes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryCriterion
     */
    max_size?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryCriterion
     */
    min_downloads?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryCriterion
     */
    min_likes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiscoveryCriterion
     */
    min_size?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DiscoveryCriterion
     */
    name?: string | null;
    /**
     * 
     * @type {ModelProvider}
     * @memberof DiscoveryCriterion
     */
    provider?: ModelProvider;
    /**
     * 
     * @type {Array<ServingRuntime>}
     * @memberof DiscoveryCriterion
     */
    serving_runtimes?: Array<ServingRuntime>;
    /**
     * 
     * @type {Array<DeploymentModality>}
     * @memberof DiscoveryCriterion
     */
    supported_deployment_modalities?: Array<DeploymentModality>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DiscoveryCriterion
     */
    tags?: Array<string>;
    /**
     * 
     * @type {Array<Task>}
     * @memberof DiscoveryCriterion
     */
    task_types?: Array<Task>;
}

export function DiscoveryCriterionFromJSON(json: any): DiscoveryCriterion {
    return DiscoveryCriterionFromJSONTyped(json, false);
}

export function DiscoveryCriterionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoveryCriterion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': !exists(json, 'author') ? undefined : json['author'],
        'batch_scheduler_queue_ids': !exists(json, 'batch_scheduler_queue_ids') ? undefined : json['batch_scheduler_queue_ids'],
        'has_deployment_options': !exists(json, 'has_deployment_options') ? undefined : json['has_deployment_options'],
        'hpc_cluster_ids': !exists(json, 'hpc_cluster_ids') ? undefined : json['hpc_cluster_ids'],
        'inference_runtimes': !exists(json, 'inference_runtimes') ? undefined : json['inference_runtimes'],
        'license': !exists(json, 'license') ? undefined : json['license'],
        'max_downloads': !exists(json, 'max_downloads') ? undefined : json['max_downloads'],
        'max_likes': !exists(json, 'max_likes') ? undefined : json['max_likes'],
        'max_size': !exists(json, 'max_size') ? undefined : json['max_size'],
        'min_downloads': !exists(json, 'min_downloads') ? undefined : json['min_downloads'],
        'min_likes': !exists(json, 'min_likes') ? undefined : json['min_likes'],
        'min_size': !exists(json, 'min_size') ? undefined : json['min_size'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'provider': !exists(json, 'provider') ? undefined : ModelProviderFromJSON(json['provider']),
        'serving_runtimes': !exists(json, 'serving_runtimes') ? undefined : ((json['serving_runtimes'] as Array<any>).map(ServingRuntimeFromJSON)),
        'supported_deployment_modalities': !exists(json, 'supported_deployment_modalities') ? undefined : ((json['supported_deployment_modalities'] as Array<any>).map(DeploymentModalityFromJSON)),
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'task_types': !exists(json, 'task_types') ? undefined : ((json['task_types'] as Array<any>).map(TaskFromJSON)),
    };
}

export function DiscoveryCriterionToJSON(value?: DiscoveryCriterion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'batch_scheduler_queue_ids': value.batch_scheduler_queue_ids,
        'has_deployment_options': value.has_deployment_options,
        'hpc_cluster_ids': value.hpc_cluster_ids,
        'inference_runtimes': value.inference_runtimes,
        'license': value.license,
        'max_downloads': value.max_downloads,
        'max_likes': value.max_likes,
        'max_size': value.max_size,
        'min_downloads': value.min_downloads,
        'min_likes': value.min_likes,
        'min_size': value.min_size,
        'name': value.name,
        'provider': ModelProviderToJSON(value.provider),
        'serving_runtimes': value.serving_runtimes === undefined ? undefined : ((value.serving_runtimes as Array<any>).map(ServingRuntimeToJSON)),
        'supported_deployment_modalities': value.supported_deployment_modalities === undefined ? undefined : ((value.supported_deployment_modalities as Array<any>).map(DeploymentModalityToJSON)),
        'tags': value.tags,
        'task_types': value.task_types === undefined ? undefined : ((value.task_types as Array<any>).map(TaskToJSON)),
    };
}

