/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DiscoveryCriterion,
    DiscoveryCriterionFromJSON,
    DiscoveryCriterionFromJSONTyped,
    DiscoveryCriterionToJSON,
} from './';

/**
 * 
 * @export
 * @interface DiscoverExternalModelsBody
 */
export interface DiscoverExternalModelsBody {
    /**
     * 
     * @type {Array<DiscoveryCriterion>}
     * @memberof DiscoverExternalModelsBody
     */
    criteria?: Array<DiscoveryCriterion>;
}

export function DiscoverExternalModelsBodyFromJSON(json: any): DiscoverExternalModelsBody {
    return DiscoverExternalModelsBodyFromJSONTyped(json, false);
}

export function DiscoverExternalModelsBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoverExternalModelsBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'criteria': !exists(json, 'criteria') ? undefined : ((json['criteria'] as Array<any>).map(DiscoveryCriterionFromJSON)),
    };
}

export function DiscoverExternalModelsBodyToJSON(value?: DiscoverExternalModelsBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'criteria': value.criteria === undefined ? undefined : ((value.criteria as Array<any>).map(DiscoveryCriterionToJSON)),
    };
}

