/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalModel,
    ExternalModelFromJSON,
    ExternalModelFromJSONTyped,
    ExternalModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface DiscoverExternalModelsResponse
 */
export interface DiscoverExternalModelsResponse {
    /**
     * 
     * @type {string}
     * @memberof DiscoverExternalModelsResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof DiscoverExternalModelsResponse
     */
    metadata: object;
    /**
     * 
     * @type {Array<ExternalModel>}
     * @memberof DiscoverExternalModelsResponse
     */
    result: Array<ExternalModel>;
    /**
     * 
     * @type {number}
     * @memberof DiscoverExternalModelsResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof DiscoverExternalModelsResponse
     */
    version: string;
}

export function DiscoverExternalModelsResponseFromJSON(json: any): DiscoverExternalModelsResponse {
    return DiscoverExternalModelsResponseFromJSONTyped(json, false);
}

export function DiscoverExternalModelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoverExternalModelsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ((json['result'] as Array<any>).map(ExternalModelFromJSON)),
        'status': json['status'],
        'version': json['version'],
    };
}

export function DiscoverExternalModelsResponseToJSON(value?: DiscoverExternalModelsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ((value.result as Array<any>).map(ExternalModelToJSON)),
        'status': value.status,
        'version': value.version,
    };
}

