/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DerivedModelMetadata,
    DerivedModelMetadataFromJSON,
    DerivedModelMetadataFromJSONTyped,
    DerivedModelMetadataToJSON,
} from './';

/**
 * 
 * @export
 * @interface ExternalModelMetadata
 */
export interface ExternalModelMetadata {
    /**
     * 
     * @type {DerivedModelMetadata}
     * @memberof ExternalModelMetadata
     */
    derived: DerivedModelMetadata;
}

export function ExternalModelMetadataFromJSON(json: any): ExternalModelMetadata {
    return ExternalModelMetadataFromJSONTyped(json, false);
}

export function ExternalModelMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalModelMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'derived': DerivedModelMetadataFromJSON(json['derived']),
    };
}

export function ExternalModelMetadataToJSON(value?: ExternalModelMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'derived': DerivedModelMetadataToJSON(value.derived),
    };
}

