/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalModelMetadata,
    ExternalModelMetadataFromJSON,
    ExternalModelMetadataFromJSONTyped,
    ExternalModelMetadataToJSON,
    HuggingFaceRepoLocator,
    HuggingFaceRepoLocatorFromJSON,
    HuggingFaceRepoLocatorFromJSONTyped,
    HuggingFaceRepoLocatorToJSON,
    ModelProvider,
    ModelProviderFromJSON,
    ModelProviderFromJSONTyped,
    ModelProviderToJSON,
    TapisSystemLocator,
    TapisSystemLocatorFromJSON,
    TapisSystemLocatorFromJSONTyped,
    TapisSystemLocatorToJSON,
} from './';

/**
 * 
 * @export
 * @interface ExternalModel
 */
export interface ExternalModel {
    /**
     * 
     * @type {string}
     * @memberof ExternalModel
     */
    created_at: string;
    /**
     * 
     * @type {HuggingFaceRepoLocator}
     * @memberof ExternalModel
     */
    huggingface_repo_locator?: HuggingFaceRepoLocator;
    /**
     * 
     * @type {string}
     * @memberof ExternalModel
     */
    id: string;
    /**
     * 
     * @type {ExternalModelMetadata}
     * @memberof ExternalModel
     */
    metadata: ExternalModelMetadata;
    /**
     * 
     * @type {ModelProvider}
     * @memberof ExternalModel
     */
    provider: ModelProvider;
    /**
     * 
     * @type {TapisSystemLocator}
     * @memberof ExternalModel
     */
    tapis_system_locator?: TapisSystemLocator;
    /**
     * 
     * @type {string}
     * @memberof ExternalModel
     */
    updated_at: string;
}

export function ExternalModelFromJSON(json: any): ExternalModel {
    return ExternalModelFromJSONTyped(json, false);
}

export function ExternalModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'created_at': json['created_at'],
        'huggingface_repo_locator': !exists(json, 'huggingface_repo_locator') ? undefined : HuggingFaceRepoLocatorFromJSON(json['huggingface_repo_locator']),
        'id': json['id'],
        'metadata': ExternalModelMetadataFromJSON(json['metadata']),
        'provider': ModelProviderFromJSON(json['provider']),
        'tapis_system_locator': !exists(json, 'tapis_system_locator') ? undefined : TapisSystemLocatorFromJSON(json['tapis_system_locator']),
        'updated_at': json['updated_at'],
    };
}

export function ExternalModelToJSON(value?: ExternalModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.created_at,
        'huggingface_repo_locator': HuggingFaceRepoLocatorToJSON(value.huggingface_repo_locator),
        'id': value.id,
        'metadata': ExternalModelMetadataToJSON(value.metadata),
        'provider': ModelProviderToJSON(value.provider),
        'tapis_system_locator': TapisSystemLocatorToJSON(value.tapis_system_locator),
        'updated_at': value.updated_at,
    };
}

