/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeploymentOptionDetail,
    DeploymentOptionDetailFromJSON,
    DeploymentOptionDetailFromJSONTyped,
    DeploymentOptionDetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetExternalModelDeploymentOptionResponse
 */
export interface GetExternalModelDeploymentOptionResponse {
    /**
     * 
     * @type {string}
     * @memberof GetExternalModelDeploymentOptionResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof GetExternalModelDeploymentOptionResponse
     */
    metadata: object;
    /**
     * 
     * @type {DeploymentOptionDetail}
     * @memberof GetExternalModelDeploymentOptionResponse
     */
    result: DeploymentOptionDetail;
    /**
     * 
     * @type {number}
     * @memberof GetExternalModelDeploymentOptionResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof GetExternalModelDeploymentOptionResponse
     */
    version: string;
}

export function GetExternalModelDeploymentOptionResponseFromJSON(json: any): GetExternalModelDeploymentOptionResponse {
    return GetExternalModelDeploymentOptionResponseFromJSONTyped(json, false);
}

export function GetExternalModelDeploymentOptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExternalModelDeploymentOptionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': DeploymentOptionDetailFromJSON(json['result']),
        'status': json['status'],
        'version': json['version'],
    };
}

export function GetExternalModelDeploymentOptionResponseToJSON(value?: GetExternalModelDeploymentOptionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': DeploymentOptionDetailToJSON(value.result),
        'status': value.status,
        'version': value.version,
    };
}

