/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalModel,
    ExternalModelFromJSON,
    ExternalModelFromJSONTyped,
    ExternalModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetExternalModelResponse
 */
export interface GetExternalModelResponse {
    /**
     * 
     * @type {string}
     * @memberof GetExternalModelResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof GetExternalModelResponse
     */
    metadata: object;
    /**
     * 
     * @type {ExternalModel}
     * @memberof GetExternalModelResponse
     */
    result: ExternalModel;
    /**
     * 
     * @type {number}
     * @memberof GetExternalModelResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof GetExternalModelResponse
     */
    version: string;
}

export function GetExternalModelResponseFromJSON(json: any): GetExternalModelResponse {
    return GetExternalModelResponseFromJSONTyped(json, false);
}

export function GetExternalModelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExternalModelResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ExternalModelFromJSON(json['result']),
        'status': json['status'],
        'version': json['version'],
    };
}

export function GetExternalModelResponseToJSON(value?: GetExternalModelResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ExternalModelToJSON(value.result),
        'status': value.status,
        'version': value.version,
    };
}

