/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DataCenter,
    DataCenterFromJSON,
    DataCenterFromJSONTyped,
    DataCenterToJSON,
} from './';

/**
 * 
 * @export
 * @interface HpcClusterQueueTarget
 */
export interface HpcClusterQueueTarget {
    /**
     * 
     * @type {boolean}
     * @memberof HpcClusterQueueTarget
     */
    batch_scheduler_queue_enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof HpcClusterQueueTarget
     */
    batch_scheduler_queue_id: string;
    /**
     * 
     * @type {string}
     * @memberof HpcClusterQueueTarget
     */
    batch_scheduler_queue_name: string;
    /**
     * 
     * @type {DataCenter}
     * @memberof HpcClusterQueueTarget
     */
    data_center: DataCenter;
    /**
     * 
     * @type {boolean}
     * @memberof HpcClusterQueueTarget
     */
    hpc_cluster_enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof HpcClusterQueueTarget
     */
    hpc_cluster_id: string;
    /**
     * 
     * @type {string}
     * @memberof HpcClusterQueueTarget
     */
    hpc_cluster_name: string;
}

export function HpcClusterQueueTargetFromJSON(json: any): HpcClusterQueueTarget {
    return HpcClusterQueueTargetFromJSONTyped(json, false);
}

export function HpcClusterQueueTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): HpcClusterQueueTarget {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'batch_scheduler_queue_enabled': json['batch_scheduler_queue_enabled'],
        'batch_scheduler_queue_id': json['batch_scheduler_queue_id'],
        'batch_scheduler_queue_name': json['batch_scheduler_queue_name'],
        'data_center': DataCenterFromJSON(json['data_center']),
        'hpc_cluster_enabled': json['hpc_cluster_enabled'],
        'hpc_cluster_id': json['hpc_cluster_id'],
        'hpc_cluster_name': json['hpc_cluster_name'],
    };
}

export function HpcClusterQueueTargetToJSON(value?: HpcClusterQueueTarget | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'batch_scheduler_queue_enabled': value.batch_scheduler_queue_enabled,
        'batch_scheduler_queue_id': value.batch_scheduler_queue_id,
        'batch_scheduler_queue_name': value.batch_scheduler_queue_name,
        'data_center': DataCenterToJSON(value.data_center),
        'hpc_cluster_enabled': value.hpc_cluster_enabled,
        'hpc_cluster_id': value.hpc_cluster_id,
        'hpc_cluster_name': value.hpc_cluster_name,
    };
}

