/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ArtifactIngestion,
    ArtifactIngestionFromJSON,
    ArtifactIngestionFromJSONTyped,
    ArtifactIngestionToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListModelIngestionsResponse
 */
export interface ListModelIngestionsResponse {
    /**
     * 
     * @type {string}
     * @memberof ListModelIngestionsResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ListModelIngestionsResponse
     */
    metadata: object;
    /**
     * 
     * @type {Array<ArtifactIngestion>}
     * @memberof ListModelIngestionsResponse
     */
    result: Array<ArtifactIngestion>;
    /**
     * 
     * @type {number}
     * @memberof ListModelIngestionsResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListModelIngestionsResponse
     */
    version: string;
}

export function ListModelIngestionsResponseFromJSON(json: any): ListModelIngestionsResponse {
    return ListModelIngestionsResponseFromJSONTyped(json, false);
}

export function ListModelIngestionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListModelIngestionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ((json['result'] as Array<any>).map(ArtifactIngestionFromJSON)),
        'status': json['status'],
        'version': json['version'],
    };
}

export function ListModelIngestionsResponseToJSON(value?: ListModelIngestionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ((value.result as Array<any>).map(ArtifactIngestionToJSON)),
        'status': value.status,
        'version': value.version,
    };
}

