/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ArtifactPublication,
    ArtifactPublicationFromJSON,
    ArtifactPublicationFromJSONTyped,
    ArtifactPublicationToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListModelPublicationsResponse
 */
export interface ListModelPublicationsResponse {
    /**
     * 
     * @type {string}
     * @memberof ListModelPublicationsResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ListModelPublicationsResponse
     */
    metadata: object;
    /**
     * 
     * @type {Array<ArtifactPublication>}
     * @memberof ListModelPublicationsResponse
     */
    result: Array<ArtifactPublication>;
    /**
     * 
     * @type {number}
     * @memberof ListModelPublicationsResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListModelPublicationsResponse
     */
    version: string;
}

export function ListModelPublicationsResponseFromJSON(json: any): ListModelPublicationsResponse {
    return ListModelPublicationsResponseFromJSONTyped(json, false);
}

export function ListModelPublicationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListModelPublicationsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ((json['result'] as Array<any>).map(ArtifactPublicationFromJSON)),
        'status': json['status'],
        'version': json['version'],
    };
}

export function ListModelPublicationsResponseToJSON(value?: ListModelPublicationsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ((value.result as Array<any>).map(ArtifactPublicationToJSON)),
        'status': value.status,
        'version': value.version,
    };
}

