/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeploymentOption,
    DeploymentOptionFromJSON,
    DeploymentOptionFromJSONTyped,
    DeploymentOptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListExternalModelDeploymentOptionsResponse
 */
export interface ListExternalModelDeploymentOptionsResponse {
    /**
     * 
     * @type {string}
     * @memberof ListExternalModelDeploymentOptionsResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof ListExternalModelDeploymentOptionsResponse
     */
    metadata: object;
    /**
     * 
     * @type {Array<DeploymentOption>}
     * @memberof ListExternalModelDeploymentOptionsResponse
     */
    result: Array<DeploymentOption>;
    /**
     * 
     * @type {number}
     * @memberof ListExternalModelDeploymentOptionsResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ListExternalModelDeploymentOptionsResponse
     */
    version: string;
}

export function ListExternalModelDeploymentOptionsResponseFromJSON(json: any): ListExternalModelDeploymentOptionsResponse {
    return ListExternalModelDeploymentOptionsResponseFromJSONTyped(json, false);
}

export function ListExternalModelDeploymentOptionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListExternalModelDeploymentOptionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ((json['result'] as Array<any>).map(DeploymentOptionFromJSON)),
        'status': json['status'],
        'version': json['version'],
    };
}

export function ListExternalModelDeploymentOptionsResponseToJSON(value?: ListExternalModelDeploymentOptionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ((value.result as Array<any>).map(DeploymentOptionToJSON)),
        'status': value.status,
        'version': value.version,
    };
}

