/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Locator
 */
export interface Locator {
    /**
     * 
     * @type {string}
     * @memberof Locator
     */
    url: string;
}

export function LocatorFromJSON(json: any): Locator {
    return LocatorFromJSONTyped(json, false);
}

export function LocatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Locator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function LocatorToJSON(value?: Locator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

