/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ModelProvider {
    HuggingFace = 'HuggingFace',
    Tapis = 'Tapis'
}

export function ModelProviderFromJSON(json: any): ModelProvider {
    return ModelProviderFromJSONTyped(json, false);
}

export function ModelProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelProvider {
    return json as ModelProvider;
}

export function ModelProviderToJSON(value?: ModelProvider | null): any {
    return value as any;
}

