/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalModel,
    ExternalModelFromJSON,
    ExternalModelFromJSONTyped,
    ExternalModelToJSON,
    Visibility,
    VisibilityFromJSON,
    VisibilityFromJSONTyped,
    VisibilityToJSON,
} from './';

/**
 * 
 * @export
 * @interface Model
 */
export interface Model {
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    artifact_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    created_at: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    description?: string | null;
    /**
     * 
     * @type {ExternalModel}
     * @memberof Model
     */
    external_model: ExternalModel;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    external_model_id: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    owner: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    tenant_id: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    updated_at: string;
    /**
     * 
     * @type {Visibility}
     * @memberof Model
     */
    visibility: Visibility;
}

export function ModelFromJSON(json: any): Model {
    return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'artifact_id': !exists(json, 'artifact_id') ? undefined : json['artifact_id'],
        'created_at': json['created_at'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'external_model': ExternalModelFromJSON(json['external_model']),
        'external_model_id': json['external_model_id'],
        'id': json['id'],
        'name': json['name'],
        'owner': json['owner'],
        'tenant_id': json['tenant_id'],
        'updated_at': json['updated_at'],
        'visibility': VisibilityFromJSON(json['visibility']),
    };
}

export function ModelToJSON(value?: Model | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'artifact_id': value.artifact_id,
        'created_at': value.created_at,
        'description': value.description,
        'external_model': ExternalModelToJSON(value.external_model),
        'external_model_id': value.external_model_id,
        'id': value.id,
        'name': value.name,
        'owner': value.owner,
        'tenant_id': value.tenant_id,
        'updated_at': value.updated_at,
        'visibility': VisibilityToJSON(value.visibility),
    };
}

