/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Canonical,
    CanonicalFromJSON,
    CanonicalFromJSONTyped,
    CanonicalToJSON,
    DeploymentStrategyReference,
    DeploymentStrategyReferenceFromJSON,
    DeploymentStrategyReferenceFromJSONTyped,
    DeploymentStrategyReferenceToJSON,
    Task,
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './';

/**
 * 
 * @export
 * @interface Model
 */
export interface Model {
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    author: string;
    /**
     * 
     * @type {Canonical}
     * @memberof Model
     */
    canonical?: Canonical;
    /**
     * Deployment strategy references
     * @type {Array<DeploymentStrategyReference>}
     * @memberof Model
     */
    deployment_strategy_refs: Array<DeploymentStrategyReference>;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model
     */
    libraries?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    license?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    model_type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model
     */
    regulatory?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {Array<Task>}
     * @memberof Model
     */
    task_types?: Array<Task> | null;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    tenant_id: string;
}

export function ModelFromJSON(json: any): Model {
    return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': json['author'],
        'canonical': !exists(json, 'canonical') ? undefined : CanonicalFromJSON(json['canonical']),
        'deployment_strategy_refs': ((json['deployment_strategy_refs'] as Array<any>).map(DeploymentStrategyReferenceFromJSON)),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'libraries': !exists(json, 'libraries') ? undefined : json['libraries'],
        'license': !exists(json, 'license') ? undefined : json['license'],
        'model_type': !exists(json, 'model_type') ? undefined : json['model_type'],
        'name': json['name'],
        'regulatory': !exists(json, 'regulatory') ? undefined : json['regulatory'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'task_types': !exists(json, 'task_types') ? undefined : (json['task_types'] === null ? null : (json['task_types'] as Array<any>).map(TaskFromJSON)),
        'tenant_id': json['tenant_id'],
    };
}

export function ModelToJSON(value?: Model | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'canonical': CanonicalToJSON(value.canonical),
        'deployment_strategy_refs': ((value.deployment_strategy_refs as Array<any>).map(DeploymentStrategyReferenceToJSON)),
        'description': value.description,
        'libraries': value.libraries,
        'license': value.license,
        'model_type': value.model_type,
        'name': value.name,
        'regulatory': value.regulatory,
        'tags': value.tags,
        'task_types': value.task_types === undefined ? undefined : (value.task_types === null ? null : (value.task_types as Array<any>).map(TaskToJSON)),
        'tenant_id': value.tenant_id,
    };
}

