/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelArtifact
 */
export interface ModelArtifact {
    /**
     * 
     * @type {string}
     * @memberof ModelArtifact
     */
    created_at: string;
    /**
     * 
     * @type {string}
     * @memberof ModelArtifact
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelArtifact
     */
    last_modified: string;
}

export function ModelArtifactFromJSON(json: any): ModelArtifact {
    return ModelArtifactFromJSONTyped(json, false);
}

export function ModelArtifactFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelArtifact {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'created_at': json['created_at'],
        'id': json['id'],
        'last_modified': json['last_modified'],
    };
}

export function ModelArtifactToJSON(value?: ModelArtifact | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.created_at,
        'id': value.id,
        'last_modified': value.last_modified,
    };
}

