/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Platform,
    PlatformFromJSON,
    PlatformFromJSONTyped,
    PlatformToJSON,
} from './';

/**
 * 
 * @export
 * @interface PlatformDetails
 */
export interface PlatformDetails {
    /**
     * 
     * @type {Array<string>}
     * @memberof PlatformDetails
     */
    capabilities: Array<string>;
    /**
     * 
     * @type {Platform}
     * @memberof PlatformDetails
     */
    name: Platform;
}

export function PlatformDetailsFromJSON(json: any): PlatformDetails {
    return PlatformDetailsFromJSONTyped(json, false);
}

export function PlatformDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'capabilities': json['capabilities'],
        'name': PlatformFromJSON(json['name']),
    };
}

export function PlatformDetailsToJSON(value?: PlatformDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'capabilities': value.capabilities,
        'name': PlatformToJSON(value.name),
    };
}

