/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ArtifactPublication,
    ArtifactPublicationFromJSON,
    ArtifactPublicationFromJSONTyped,
    ArtifactPublicationToJSON,
} from './';

/**
 * 
 * @export
 * @interface PublishModelArtifactResponse
 */
export interface PublishModelArtifactResponse {
    /**
     * 
     * @type {string}
     * @memberof PublishModelArtifactResponse
     */
    message: string;
    /**
     * 
     * @type {object}
     * @memberof PublishModelArtifactResponse
     */
    metadata: object;
    /**
     * 
     * @type {ArtifactPublication}
     * @memberof PublishModelArtifactResponse
     */
    result: ArtifactPublication;
    /**
     * 
     * @type {number}
     * @memberof PublishModelArtifactResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof PublishModelArtifactResponse
     */
    version: string;
}

export function PublishModelArtifactResponseFromJSON(json: any): PublishModelArtifactResponse {
    return PublishModelArtifactResponseFromJSONTyped(json, false);
}

export function PublishModelArtifactResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishModelArtifactResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'metadata': json['metadata'],
        'result': ArtifactPublicationFromJSON(json['result']),
        'status': json['status'],
        'version': json['version'],
    };
}

export function PublishModelArtifactResponseToJSON(value?: PublishModelArtifactResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'metadata': value.metadata,
        'result': ArtifactPublicationToJSON(value.result),
        'status': value.status,
        'version': value.version,
    };
}

