/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ServingRuntime {
    FlexServ = 'FlexServ'
}

export function ServingRuntimeFromJSON(json: any): ServingRuntime {
    return ServingRuntimeFromJSONTyped(json, false);
}

export function ServingRuntimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServingRuntime {
    return json as ServingRuntime;
}

export function ServingRuntimeToJSON(value?: ServingRuntime | null): any {
    return value as any;
}

