/* tslint:disable */
/* eslint-disable */
/**
 * MLHub Models API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enum of all task types available on Huggingface
 * @export
 * @enum {string}
 */
export enum Task {
    AnyToAny = 'AnyToAny',
    AudioClassification = 'AudioClassification',
    AudioToAudio = 'AudioToAudio',
    AudioTextToText = 'AudioTextToText',
    AutomaticSpeechRecognition = 'AutomaticSpeechRecognition',
    DepthEstimation = 'DepthEstimation',
    DocumentQuestionAnswering = 'DocumentQuestionAnswering',
    VisualDocumentRetrieval = 'VisualDocumentRetrieval',
    FeatureExtraction = 'FeatureExtraction',
    FillMask = 'FillMask',
    ImageClassification = 'ImageClassification',
    ImageFeatureExtraction = 'ImageFeatureExtraction',
    ImageSegmentation = 'ImageSegmentation',
    ImageToImage = 'ImageToImage',
    ImageTextToText = 'ImageTextToText',
    ImageToText = 'ImageToText',
    ImageToVideo = 'ImageToVideo',
    KeypointDetection = 'KeypointDetection',
    MaskGeneration = 'MaskGeneration',
    ObjectDetection = 'ObjectDetection',
    VideoClassification = 'VideoClassification',
    QuestionAnswering = 'QuestionAnswering',
    ReinforcementLearning = 'ReinforcementLearning',
    SentenceSimilarity = 'SentenceSimilarity',
    Summarization = 'Summarization',
    TableQuestionAnswering = 'TableQuestionAnswering',
    TabularClassification = 'TabularClassification',
    TabularRegression = 'TabularRegression',
    TextClassification = 'TextClassification',
    TextGeneration = 'TextGeneration',
    TextRanking = 'TextRanking',
    TextToImage = 'TextToImage',
    TextToSpeech = 'TextToSpeech',
    TextToVideo = 'TextToVideo',
    TokenClassification = 'TokenClassification',
    Translation = 'Translation',
    UnconditionalImageGeneration = 'UnconditionalImageGeneration',
    VideoTextToText = 'VideoTextToText',
    VideoToVideo = 'VideoToVideo',
    VisualQuestionAnswering = 'VisualQuestionAnswering',
    ZeroShotClassification = 'ZeroShotClassification',
    ZeroShotImageClassification = 'ZeroShotImageClassification',
    ZeroShotObjectDetection = 'ZeroShotObjectDetection',
    TextTo3d = 'TextTo3d',
    ImageTo3d = 'ImageTo3d'
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    return json as Task;
}

export function TaskToJSON(value?: Task | null): any {
    return value as any;
}

