name: Tapis MLHub CI

on:
  push:
    branches: [ dev, staging, main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ dev, staging, main ]

jobs:
  Set_Image_Tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_image_tag.outputs.image_tag }}
    steps:
      - id: set_image_tag
        name: Set_image
        shell: bash
        run: |
          # If the $GITHUB_REF contains "/refs/tags/v", then the "v" needs to be
          # removed from the $GITHUB_REF_NAME to form a proper image tag
          if [[ $GITHUB_REF =~ "/refs/tags/v"  ]]; then 
            echo version=$(echo $GITHUB_REF_NAME | sed -e 's!v!!') >> $GITHUB_OUTPUT
          else
            echo "image_tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT;
          fi

  Models_API:
    needs:
      - Set_Image_Tag
    name: Models_Compile_Test_Build_Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: git-diff
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            src/models/**/*
      - name: Rust setup
        run: rustup toolchain install stable
        # if: steps.git-diff.outputs.diff
      # - name: Test
      #   run: "./manage test models"
      #   # if: steps.git-diff.outputs.diff
      - name: Compile
        run: "./manage install models"
        # if: steps.git-diff.outputs.diff
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CIC_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CIC_DOCKERHUB_ACCESS_TOKEN }}
        # if: steps.git-diff.outputs.diff
      - name: Delete docker ignore
        run: rm src/models/.dockerignore
        # if: steps.git-diff.outputs.diff
      - name: Build_Image
        run: ./manage build models -t scope .gh-actions
        # if: steps.git-diff.outputs.diff
      - name: Push_All_Tags
        run: "docker push --all-tags tapis/models-api:${{ needs.Set_Image_Tag.outputs.image_tag }}"
        # if: steps.git-diff.outputs.diff
      