name: Tapis MLHub CI

on:
  workflow_dispatch:
    inputs:
      force_rebuild_all:
        type: boolean
        default: true
  push:
    branches: [ dev, staging, test, main ]
    tags:
      - 'v*.*.*'
      - 'v*'
  pull_request:
    branches: [ dev, staging, test, main ]

jobs:
  resolve_image_tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.resolve.outputs.image_tag }}
    steps:
      - id: resolve
        name: Set_image
        shell: bash
        run: |
          # If the $GITHUB_REF contains "/refs/tags/v", then the "v" needs to be
          # removed from the $GITHUB_REF_NAME to form a proper image tag
          if [[ $GITHUB_REF =~ "/refs/tags/v"  ]]; then 
            echo image_tag=$(echo $GITHUB_REF_NAME | sed -e 's!v!!') >> $GITHUB_OUTPUT
          else
            echo "image_tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT;
          fi

  diffs:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect_changes.outputs.services }}
      has_lib_diff: ${{ steps.detect_changes.outputs.has_lib_diff }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/detect-service-diffs

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run Tests
        run: cargo test --workspace
        

  models:
    if: |
      contains(fromJson(needs.diffs.outputs.services), 'models') ||
      needs.diffs.outputs.has_lib_diff == 'true' ||
      github.event.inputs.force_rebuild_all == 'true'
    needs:
      - resolve_image_tag
      - diffs
      - tests
    secrets: inherit
    uses: ./.github/workflows/models.yml
    with:
      image_name: tapis/mlhub-models-api
      image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}
  
  
  deployments:
    if: contains(fromJson(needs.diffs.outputs.services), 'deployments') || needs.diffs.outputs.has_lib_diff == 'true' || github.event.inputs.force_rebuild_all == 'true'
    needs:
      - resolve_image_tag
      - diffs
      - tests
    secrets: inherit
    uses: ./.github/workflows/deployments.yml
    with:
      image_name: tapis/mlhub-deployments-api
      image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}

  model-deployment-controller:
    if: contains(fromJson(needs.diffs.outputs.services), 'model-deployment-controller') || needs.diffs.outputs.has_lib_diff == 'true' || github.event.inputs.force_rebuild_all == 'true'
    needs:
      - resolve_image_tag
      - diffs
      - tests
    secrets: inherit
    uses: ./.github/workflows/model-deployment-controller.yml
    with:
      image_name: tapis/mlhub-model-deployment-controller
      image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}

  artifact-ingester:
    if: contains(fromJson(needs.diffs.outputs.services), 'artifact-ingester') || needs.diffs.outputs.has_lib_diff == 'true' || github.event.inputs.force_rebuild_all == 'true'
    needs:
      - resolve_image_tag
      - diffs
      - tests
    secrets: inherit
    uses: ./.github/workflows/artifact-ingester.yml
    with:
      image_name: tapis/mlhub-artifact-publisher
      image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}

  artifact-publisher:
    if: contains(fromJson(needs.diffs.outputs.services), 'artifact-publisher') || needs.diffs.outputs.has_lib_diff == 'true' || github.event.inputs.force_rebuild_all == 'true'
    needs:
      - resolve_image_tag
      - diffs
      - tests
    secrets: inherit
    uses: ./.github/workflows/artifact-publisher.yml
    with:
      image_name: tapis/mlhub-artifact-ingester
      image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}

  models-migrator:
    if: contains(fromJson(needs.diffs.outputs.services), 'models-migrator') || needs.diffs.outputs.has_lib_diff == 'true' || github.event.inputs.force_rebuild_all == 'true'
    needs:
      - resolve_image_tag
      - diffs
      - tests
    secrets: inherit
    uses: ./.github/workflows/models-migrator.yml
    with:
      image_name: tapis/mlhub-models-migrator
      image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}

  federated-identities-migrator:
    if: contains(fromJson(needs.diffs.outputs.services), 'federated-identities-migrator') || needs.diffs.outputs.has_lib_diff == 'true' || github.event.inputs.force_rebuild_all == 'true'
    needs:
      - resolve_image_tag
      - diffs
      - tests
    secrets: inherit
    uses: ./.github/workflows/federated-identities-migrator.yml
    with:
      image_name: tapis/mlhub-federated-identities-migrator
      image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}
  
  principals-migrator:
    if: contains(fromJson(needs.diffs.outputs.services), 'principals-migrator') || needs.diffs.outputs.has_lib_diff == 'true' || github.event.inputs.force_rebuild_all == 'true'
    needs:
      - resolve_image_tag
      - diffs
      - tests
    secrets: inherit
    uses: ./.github/workflows/principals-migrator.yml
    with:
      image_name: tapis/mlhub-principals-migrator
      image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}

  hf-model-etl:
    if: contains(fromJson(needs.diffs.outputs.services), 'hf-model-etl') || needs.diffs.outputs.has_lib_diff == 'true' || github.event.inputs.force_rebuild_all == 'true'
    needs:
      - resolve_image_tag
      - diffs
      - tests
    secrets: inherit
    uses: ./.github/workflows/huggingface-model-metadata-etl.yml
    with:
      extract_stage_image_name: tapis/mlhub-hf-model-etl-extract
      extract_stage_image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}
      transform_load_stage_image_name: tapis/mlhub-hf-model-etl-transform-load
      transform_load_stage_image_tag:  ${{ needs.resolve_image_tag.outputs.image_tag }}