name: Models API

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  compile-run-openapi-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Compile/Run binary
        run: cargo run --bin models-openapi > models-openapi.json
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: models-openapi
          path: models-openapi.json
          retention-days: 1

  run-openapi-downgrader:
    runs-on: ubuntu-latest
    needs: compile-run-openapi-binary  # IMPORTANT: Job 2 must wait for Job 1 to finish
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: models-openapi
      - name: Echo openapi spec test
        run: cat models-openapi.json

  generate-mlhub-models-sdk:
    needs:
      - run-openapi-downgrader
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4
      - name: Update and Install Java Runtime Environment
        run: apt-get update && apt-get install -y default-jre
      - name: Install OpenAPI Generator CLI
        run: npm install -g @openapitools/openapi-generator-cli
      - name: NPM install 
        working-directory: ./sdks/typescript-sdk
        run: npm install
    
  build-push-api-image:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.CIC_DOCKERHUB_USERNAME }}
        password: ${{ secrets.CIC_DOCKERHUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Compile
      run: cargo install --path services/models
    - name: Build Image
      run: docker buildx build --platform linux/x86_64 --no-cache --progress=plain -f services/models/Dockerfile.gh-actions -t ${{ inputs.image_name }}:${{ inputs.image_tag }} --build-arg SERVICE_NAME=models --build-arg SERVICE_DIR="services/models" --build-arg LIBS_DIR="libs" .
    - name: Push Image
      run: docker push --all-tags ${{ inputs.image_name }}