name: Models API

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/build-service.yml
    with:
      compile_cmd: ./manage install models -sv
      build_cmd: ./manage build models -sv -t env gh-actions -t tag ${{ inputs.image_tag }}
      push_cmd: ./manage models models -sv